#!/bin/sh
echo $@  > /root/applyfw
cd /TopStor
TopStor='/TopStor'
tmpdir='/root'
pace='/pace'
web='/var/www/html/des20/'
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
currentfw=`git branch | grep \* | awk '{print $2}'`
realfw=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Uploadch";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Start upgrading from version '$currentfw' to version '$realfw;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsa1010@@@$currentfw@$realfw`;
 echo Upsa1010@$datenow@$timenow@$currentfw@$realfw > ${logging}2;
 dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
 echo $datenow $timenow info $userreq  Upsa1010@@@$currentfw@$realfw $dtn>> $glog
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;

 cd $web
 git commit -am"changing to $realfw" ; git checkout $realfw
 cd $pace
 git commit -am"changing to $realfw" ; git checkout $realfw
 cd $TopStor 
 git commit -am"changing to $realfw" ; git checkout $realfw
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Success upgrading from version '$currentfw' to version '$realfw;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsu1010@@@$currentfw@$realfw`;
 echo Upsu1010@$datenow@$timenow@$currentfw@$realfw > ${logging}2;
 dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
 echo $datenow $timenow info $userreq  Upsu1010@@@$currentfw@$realfw $dtn>> $glog
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
