#!/bin/sh
echo $@  > /root/applyfw
cd /TopStor
TopStor='/TopStor'
tmpdir='/root'
pace='/pace'
web='/var/www/html/des20/'
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
currentfw=`git branch | grep \* | awk '{print $2}'`
realfw=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Uploadch";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 ETCDCTL_API=3 /TopStor/logmsg.py Upsa1010 info $userreq $currentfw $realfw
 cd $web
 git commit -am"changing to $realfw" ; git checkout $realfw
 cd $pace
 git commit -am"changing to $realfw" ; git checkout $realfw
 cd $TopStor 
 git commit -am"changing to $realfw" ; git checkout $realfw
 ETCDCTL_API=3 /pace/etcddel.py md --prefix
 ETCDCTL_API=3 /TopStor/logmsg.py Upsu1010 info $userreq $currentfw $realfw
fi
