#!/usr/local/bin/zsh
echo starting reply > tmpreply
so=`echo  $@ | awk '{print $1}'`;
dst=`echo  $@ | awk '{print $2}'`;
pp=`echo  $@ | awk '{print $3}'`;
localrep=`echo  $@ | awk '{print $4}'`;
res=`echo  $@ | awk '{$1=$2=$3=$4="";print substr($0,5)}'`;
stamp=`date +%s`
# packet : sender stamp command
if [[ $localrep == "proxy" ]];
then
# echo $so $stamp $res \| nc -w 4  $dst $pp >> tmpreply
 echo $so $stamp $res | nc -w 4  $dst $pp 2>/dev/null
 echo finished >> tmpreply
else
# echo $so $stamp $res \| openssl enc -a -A -aes-256-cbc -k SuperSecretPWD \| gzip -cf \| nc -w 4  $dst $pp >tmpreply
 echo $so $stamp $res | openssl enc -a -A -aes-256-cbc -k SuperSecretPWD | gzip -cf | nc -w 4 $dst $pp 2>/dev/null
# echo finisehd >> tmpreply
fi
