#!/usr/local/bin/zsh
#cd /root/scripts
cd /TopStor
TopStor='TopStor'
tmpdir='/root'
pace='pace'
web='var/www/html/des20/'
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
currentfw=`git branch | grep \* | awk '{print $2}'`
webfile='/var/www/html/des20/Data';
userreq='system'
cd /TopStordata
mkdir fw &>/dev/null
cd fw
rm -rf * &>/dev/null
#wget ftp://10.11.11.124/pub/current/
wget ftp://ftp.quickstor.net/download/current/ --user=anonymous@quickstor.net
if [ ! -f index.html ];
 then 
 cd /TopStor
  ETCDCTL_API=3 /TopStor/logmsg.py Upcr1010 warning $userreq
 exit
fi
realfw=`cat index.html | grep qsfw | awk -F'current/' '{print $2}' | awk -F'.qsfw' '{print $1}'`

newfw=`echo -e ${realfw}'\n'$currentfw | sort -nr | head -1`
cd /TopStor
echo $newfw | grep $currentfw
if [ $? -eq 0 ]; 
then
  ETCDCTL_API=3 /TopStor/logmsg.py Upnu1010 info $userreq
else
  ETCDCTL_API=3 /TopStor/logmsg.py Updo1010 info $userreqi $realfw
 cd $webfile
# wget ftp://10.11.11.124/pub/current/${newfw}.qsfw
 wget ftp://ftp.quickstor.net/download/current/${newfw}.qsfw --user=anonymous@quickstor.net
 cd /TopStor
  ETCDCTL_API=3 /TopStor/logmsg.py Upfd1010 info $userreqi $realfw
 ./GenPatch ${newfw}.qsfw system 
fi
