#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/dgset
importpools=` zpool import | grep 'pool:' | awk '{print $2}'`;   
 echo "${importpools[@]}" | while read  l;
 do 
  echo $preimport $l > /root/Checkpoolimport
  /TopStor/etcdput.py activepool/$l preimport
 done
