#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
echo $@ > /root/VolumeDeleteISCSI 
perfmon=`cat /pacedata/perfmon`
volname=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $3}'`;
DG=`echo $pDG `;
myhost=`hostname -s`
txtres='/TopStordata/'`basename $0`$userreq
rm -rf $txtres &>/dev/null
privilege='ISCSI';
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 disk=`ls -l /dev/zvol/$DG/$volname | awk -F'/' '{print $NF}'`
 echo $disk
 echo targetcli backstores/block delete ${disk}-${myhost}-$volname
 targetcli backstores/block delete ${disk}-${myhost}-$volname
fi
