#!/usr/bin/sh
cd /TopStor/
echo $@ > /root/tmp
web="/var/www/html/des20/Data/DGstatus.log";
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log'
pool=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="DISK_Groups";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.sh DGst5 info $userreq $pool
 zpool destroy -f $pool &>/dev/null 
 if [ $? -ne 0 ]; then
  /TopStor/logmsg.sh DGfa5 error $userreq $pool
 else
  crontab -l | grep -v Snap > /TopStordata/cronfile
  crontab -r 
  crontab /TopStordata/cronfile

  echo > /etc/exports
  /TopStor/logmsg.sh DGsu5 info $userreq $pool
 fi 
 rm txt/${0:2}$userreq.txt
fi
sed -i "/p${nextpool}/c\\" $runningpools
ETCDCTL_API=3 /pace/putzpool.py
