#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/tmp
web="/var/www/html/des20/Data/DGstatus.log";
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log'
pool=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
privilege="DiskGroups";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 myhost=`hostname -s`
 currentreq=`/pace/etcdget.py requests/DGdestroypool --prefix`
 echo $currentreq | grep $myhost
 if [ $? -eq 0 ];
 then
  exit
 else
  /pace/etcdput.py requests/DGdestroypool/$myhost $myhost/$userreq
 fi
  /TopStor/logmsg.py DGst5 info $userreq $pool
 zpool destroy -f $pool &>/dev/null 
 if [ $? -ne 0 ]; then
   /TopStor/logmsg.py DGfa5 error $userreq $pool
 else
  crontab -l | grep -v Snap > /TopStordata/cronfile
  crontab -r 
  crontab /TopStordata/cronfile
  ETCDCTL_API=3 /pace/etcddel.py pools $pool

  echo > /etc/exports
   /TopStor/logmsg.py DGsu5 info $userreq $pool
 fi 
 rm txt/${0:2}$userreq.txt
fi
sed -i "/p${nextpool}/c\\" $runningpools
/pace/etcddel.py requests/DGdestroypool/$myhost $myhost/$userreq
 /pace/putzpool.py
