#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/dgset
web="/var/www/html/des20/Data/DGstatus.log";
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
iscsimapping='/pacedata/iscsimapping'
raid=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
host=` echo $@ | awk '{print $3}'`;
hostnam=` echo $@ | awk '{print $3}'`;
disk1=` echo $@ | awk '{print $4}'`;
diskn1=` echo $@ | awk '{print $5}'`;
#disk1=`ls /dev/disk/by-id/ | grep -v part | grep $disk1`
msgraid="nothing";
myhost=`hostname -s`
privilege="DiskGroups";
contrun=`./privthis.sh $privilege $userreq`;
declare -a params=(`echo $@`);
declare -a hostparam=();
declare -a diskparam=();
if [[ $contrun == 'true' ]];
then
 currentreq=`/pace/etcdget.py requests/DGsetpool --prefix`
 echo $currentreq | grep $myhost
 if [ $? -eq 0 ];
 then
  exit
 else
  /pace/etcdput.py requests/DGsetpool/$myhost $myhost/$userreq
 fi
 diskargs=${#params[@]};
 diskargs=$((diskargs-1));
 nextpool=${params[$diskargs]};
 msgraid=$raid
 if [[ $raid == "readcache" ]]; then msgraid="readcache"; fi;
 if [[ $raid == "readwritecache" ]]; then msgraid="readwritecache"; fi;
 if [[ $raid == "mirror" ]]; then msgraid="Mirror"; fi;
 if [[ $raid == "raidz1" ]]; then msgraid="RAID5"; fi;
 if [[ $raid == "raidz2" ]]; then msgraid="Enhanced RAID6"; fi;
 disks=('obsoletecode')
 noofdisks=`echo $disks | wc -w | awk '{print $1}'`;
 disksarr=(${disks});
 if [[ $raid == "addmirror" ]]; then
  diskargs=$((diskargs-1));
  i=2
  disk1=" ";
  diskns="";
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   echo /sbin/zpool labelclear /dev/disk/by-id/$disk;
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
    echo $disk1, $diskns, $p${nextpool}
   /TopStor/logmsg.py DGst20 info $userreq ${nextpool} $diskns .
  /sbin/zpool add -f ${nextpool} mirror ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu20 info $userreq ${nextpool} $diskns .
  else
    /TopStor/logmsg.py DGfa20 error $userreq ${nextpool} $diskns .
  fi
 fi 
 if [[ $raid == "attachmirror" ]]; then
  disk2=` echo $@ | awk '{print $6}'`;
  #disk2=`ls /dev/disk/by-id/ | grep -v part | grep $disk2`
  diskn2=` echo $@ | awk '{print $7}'`;
  /TopStor/logmsg.py DGst7 info $userreq $diskn2 $grpn
  /sbin/zpool labelclear /dev/disk/by-id/${disk2};
  echo /sbin/zpool attach -f ${nextpool} ${disk1} ${disk2} > /root/tmp
  /sbin/zpool attach -f ${nextpool} ${disk1} ${disk2}
  if [ $? -ne 0 ]; then
    /TopStor/logmsg.py DGfa7 error $userreq $diskn2 stripe
  else
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu7 info $userreq $diskn2 stripe 
  fi
 fi
 if [[ $raid == "delspecial" ]]; then
   /TopStor/logmsg.py DGst9 info $userreq $diskn1 
  /sbin/zpool remove  ${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu9 info $userreq $diskn1 
  else 
     /TopStor/logmsg.py DGfa9 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "addcache" ]]; then
   /TopStor/logmsg.py DGst10 info $userreq $diskn1 
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  echo /sbin/zpool add -f ${nextpool} cache ${disk1} 
  /sbin/zpool add -f ${nextpool} cache ${disk1} 
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu10 info $userreq $diskn1 
  else 
    /TopStor/logmsg.py DGfa10 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "addlog" ]]; then
   /TopStor/logmsg.py DGst11 info $userreq $diskn1 
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  /sbin/zpool add -f ${nextpool} log ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu11 info $userreq $diskn1 
  else 
    /TopStor/logmsg.py DGfa11 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "addspare" ]]; then
  #diskn=`grep -nr $disk1 $iscsimapping | awk -F':' '{print $1}'`
   /TopStor/logmsg.py DGst8 info $userreq $diskn1 
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  echo /sbin/zpool add -f ${nextpool} spare ${disk1}

  /sbin/zpool add -f ${nextpool} spare ${disk1}
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu8 info $userreq $diskn1 
  else 
    /TopStor/logmsg.py DGfa8 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "Single" ]]; then
   nextpool='dhcp'${RANDOM}$RANDOM;
   /TopStor/logmsg.py DG1st6 info $userreq ${nextpool} $diskn1
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  /sbin/zpool create -o cachefile=/TopStordata/p${nextpool} -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} ${disk1}
  
  if [ $? -ne 0 ]; then
    /TopStor/logmsg.py DG1fa6 error $userreq ${nextpool} $diskn1 
  else 
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
     ETCDCTL_API=3 /pace/etcdput.py 'balancetype/'p$nextpool Availability 
    /TopStor/logmsg.py DG1su6 info $userreq ${nextpool} $diskn1 
  fi
 fi 
 if [[ $raid == "addparity3" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" ";
  diskns="";
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst12 info $userreq p${nextpool} $diskns
  /sbin/zpool add -f  ${nextpool} raidz3 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu12 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa12 error $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "parity3" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst13 info $userreq p${nextpool} $diskns
  nextpool='dhcp'${RANDOM}$RANDOM;
  /sbin/zpool create -o cachefile=/TopStordata/p${nextpool} -o ashift=12 -o autoexpand=on -o autoreplace=on -f ${nextpool} raidz3 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
     ETCDCTL_API=3 /pace/etcdput.py 'balancetype/'p$nextpool Availability 
    /TopStor/logmsg.py DGsu13 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa13 info $userreq p${nextpool} $diskns
  fi
 fi  
 if [[ $raid == "addparity2" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-2));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst14 info $userreq p${nextpool} $diskns
  /sbin/zpool add -f ${nextpool} raidz2 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu14 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa14 error $userreq p${nextpool} $diskns
  fi
 fi  
 if [[ $raid == "parity2" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns="";
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst15 info $userreq p${nextpool} $diskns
  nextpool='dhcp'${RANDOM}$RANDOM;
  /sbin/zpool create -o cachefile=/TopStordata/p${nextpool} -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} raidz2 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
     ETCDCTL_API=3 /pace/etcdput.py 'balancetype/'p$nextpool Availability 
    /TopStor/logmsg.py DGsu15 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa15 info $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "addparity" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-2));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst16 info $userreq p${nextpool} $diskns
  /sbin/zpool add -f ${nextpool} raidz1 ${disk1} 
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu16 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa16 info $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "parity" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-2));
  i=2
  disk1=" "
  diskns=""
  nextpool='dhcp'${RANDOM}$RANDOM;
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst17 info $userreq ${nextpool} $diskns
  echo /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on cachefile=/TopStordata/p${nextpool} -f p${nextpool} raidz1 ${disk1} >/root/tmp
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o cachefile=/TopStordata/p${nextpool} -o autoreplace=on -f p${nextpool} raidz1 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
     ETCDCTL_API=3 /pace/etcdput.py 'balancetype/'p$nextpool Availability 
    /TopStor/logmsg.py DGsu17 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa17 error $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "add" ]]; then
   echo adding $disk1
   /TopStor/logmsg.py DGst18 info $userreq ${nextpool} $diskn1
  /sbin/zpool add  -f ${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
    /TopStor/logmsg.py DGsu18 info $userreq ${nextpool} $diskn1
  else
    /TopStor/logmsg.py DGfa18 info $userreq ${nextpool} $diskn1
  fi
 fi 
 if [[ $raid == "stripeset" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst21 info $userreq p${nextpool} $diskns
  nextpool='dhcp'${RANDOM}$RANDOM;
  /sbin/zpool create -o cachefile=/TopStordata/p${nextpool} -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
     ETCDCTL_API=3 /pace/etcdput.py 'balancetype/'p$nextpool Availability 
    /TopStor/logmsg.py DGsu21 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa21 error $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "mirror" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
   /TopStor/logmsg.py DGst19 info $userreq p${nextpool} $diskns
  nextpool='dhcp'${RANDOM}$RANDOM;
  /sbin/zpool create -o cachefile=/TopStordata/p${nextpool} -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} mirror ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
     ETCDCTL_API=3 /pace/etcdput.py 'pools/'p$nextpool $myhost
     ETCDCTL_API=3 /pace/etcdput.py 'balancetype/'p$nextpool Availability 
    /TopStor/logmsg.py DGsu19 info $userreq p${nextpool} $diskns
  else
    /TopStor/logmsg.py DGfa19  error $userreq p${nextpool} $diskns
  fi
 fi 
fi
rm txt/${0:2}$userreq.txt
sed -i "/p${nextpool}/c\\" $runningpools
/pace/etcddel.py requests/DGsetpool/$myhost $myhost/$userreq
/pace/putzpool.py 
