#!/usr/bin/sh
cd /TopStor/
echo $@ > /root/dgset
web="/var/www/html/des20/Data/DGstatus.log";
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
iscsimapping='/pacedata/iscsimapping'
raid=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
host=` echo $@ | awk '{print $3}'`;
hostnam=` echo $@ | awk '{print $3}'`;
disk1=` echo $@ | awk '{print $4}'`;
diskn1=` echo $@ | awk '{print $5}'`;
disk1=`ls /dev/disk/by-id/ | grep -v part | grep $disk1`
msgraid="nothing";
myhost=`hostname -s`
nextpool=$myhost;
privilege="DISK_Groups"
contrun=`./privthis.sh $privilege $userreq`;
declare -a params=(`echo $@`);
declare -a hostparam=();
declare -a diskparam=();
if [[ $contrun == 'true' ]];
then
 msgraid=$raid
 if [[ $raid == "readcache" ]]; then msgraid="readcache"; fi;
 if [[ $raid == "readwritecache" ]]; then msgraid="readwritecache"; fi;
 if [[ $raid == "mirror" ]]; then msgraid="Mirror"; fi;
 if [[ $raid == "raidz1" ]]; then msgraid="RAID5"; fi;
 if [[ $raid == "raidz2" ]]; then msgraid="Enhanced RAID6"; fi;
 disks=('obsoletecode')
 noofdisks=`echo $disks | wc -w | awk '{print $1}'`;
 disksarr=(${disks});
 if [[ $raid == "addmirror" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" ";
  diskns="";
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst20 info $userreq p${nextpool} $diskns .
  /sbin/zpool add -f p${nextpool} mirror ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu20 info $userreq p${nextpool} $diskns .
  else
   /TopStor/logmsg.sh DGsu20 error $userreq p${nextpool} $diskns .
  fi
 fi 
 if [[ $raid == "attachmirror" ]]; then
  disk2=` echo $@ | awk '{print $5}'`;
  disk2=`ls /dev/disk/by-id/ | grep -v part | grep $disk2`
  diskn2=` echo $@ | awk '{print $6}'`;
  grpn=` echo $@ | awk '{print $7}'`;
  /TopStor/logmsg.sh DGst7 info $userreq $diskn2 $grpn
  /sbin/zpool labelclear /dev/disk/by-id/${disk2};
  /sbin/zpool attach -f p${nextpool} ${disk1} ${disk2}
  if [ $? -ne 0 ]; then
   /TopStor/logmsg.sh DGfa7 error $userreq $diskn2 $grpn
  else
   /TopStor/logmsg.sh DGsu7 info $userreq $diskn2 $grpn
  fi
 fi
 if [[ $raid == "delspecial" ]]; then
  /TopStor/logmsg.sh DGst9 info $userreq $diskn1 
  /sbin/zpool remove  p${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu9 info $userreq $diskn1 
  else 
    /TopStor/logmsg.sh DGfa9 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "addcache" ]]; then
  /TopStor/logmsg.sh DGst10 info $userreq $diskn1 
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  #/sbin/zpool add -f p${nextpool} cache ${disk1} 2>txt/${0:2}$userreq.txt
  echo /sbin/zpool add -f p${nextpool} cache ${disk1} 
  /sbin/zpool add -f p${nextpool} cache ${disk1} 
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu10 info $userreq $diskn1 
  else 
   /TopStor/logmsg.sh DGfa10 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "addlog" ]]; then
  /TopStor/logmsg.sh DGst11 info $userreq $diskn1 
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  /sbin/zpool add -f p${nextpool} log ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu11 info $userreq $diskn1 
  else 
   /TopStor/logmsg.sh DGfa11 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "addspare" ]]; then
  #diskn=`grep -nr $disk1 $iscsimapping | awk -F':' '{print $1}'`
  /TopStor/logmsg.sh DGst8 info $userreq $diskn1 
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  /sbin/zpool add -f p${nextpool} spare ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu8 info $userreq $diskn1 
  else 
   /TopStor/logmsg.sh DGfa8 error $userreq $diskn1 
  fi
 fi 
 if [[ $raid == "Single" ]]; then
  /TopStor/logmsg.sh DG1st6 info $userreq ${nextpool} $diskn1
  /sbin/zpool labelclear /dev/disk/by-id/${disk1};
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -ne 0 ]; then
   /TopStor/logmsg.sh DG1fa6 error $userreq ${nextpool} $diskn1 
  else 
   /TopStor/logmsg.sh DG1su6 info $userreq ${nextpool} $diskn1 
  fi
 fi 
 if [[ $raid == "addparity3" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" ";
  diskns="";
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst12 info $userreq p${nextpool} $diskns
  /sbin/zpool add -f  p${nextpool} raidz3 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu12 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa12 error $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "parity3" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst13 info $userreq p${nextpool} $diskns
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} raidz3 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu13 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa13 info $userreq p${nextpool} $diskns
  fi
 fi  
 if [[ $raid == "addparity2" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst14 info $userreq p${nextpool} $diskns
  /sbin/zpool add -f p${nextpool} raidz2 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu14 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa14 error $userreq p${nextpool} $diskns
  fi
 fi  
 if [[ $raid == "parity2" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns="";
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst15 info $userreq p${nextpool} $diskns
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} raidz2 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu15 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa15 info $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "addparity" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst16 info $userreq p${nextpool} $diskns
  /sbin/zpool add -f p${nextpool} raidz1 ${disk1} 
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu16 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa16 info $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "parity" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst17 info $userreq p${nextpool} $diskns
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} raidz1 ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu17 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa17 error $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "add" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst18 info $userreq p${nextpool} $diskns
  /sbin/zpool add  -f p${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu18 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa18 info $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "stripeset" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst21 info $userreq p${nextpool} $diskns
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu21 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa21 error $userreq p${nextpool} $diskns
  fi
 fi 
 if [[ $raid == "mirror" ]]; then
  diskargs=${#params[@]};
  diskargs=$((diskargs-1));
  i=2
  disk1=" "
  diskns=""
  while [ $i -lt $diskargs ]; do
   i=$((i+1));
   disk=`echo ${params[$i]} | awk -F':' '{print $1}'`
   diskn=`echo ${params[$i]} | awk -F':' '{print $2}'`
   disk=`ls /dev/disk/by-id/ | grep -v part | grep $disk`
   /sbin/zpool labelclear /dev/disk/by-id/$disk;
   disk1=${disk1}$disk" "
   diskns=${diskns}$diskn","
  done;
  /TopStor/logmsg.sh DGst19 info $userreq p${nextpool} $diskns
  /sbin/zpool create -o ashift=12 -o autoexpand=on -o autoreplace=on -f p${nextpool} mirror ${disk1} 2>txt/${0:2}$userreq.txt
  if [ $? -eq 0 ]; then
   /TopStor/logmsg.sh DGsu19 info $userreq p${nextpool} $diskns
  else
   /TopStor/logmsg.sh DGfa19  error $userreq p${nextpool} $diskns
  fi
 fi 
fi
rm txt/${0:2}$userreq.txt
sed -i "/p${nextpool}/c\\" $runningpools
ETCDCTL_API=3 /pace/etcddel.py run disk 
ETCDCTL_API=3 /pace/putzpool.py
