#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/'`basename $0`'status.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
domain=`echo $@ | awk '{ print $1 }' `;
domc=`echo $domain | tr '[:lower:]' '[:upper:]'`;
doms=`echo $domain | tr '[:upper:]' '[:lower:]'`;
domshort=` echo $domc | awk -F. '{ print $1 }'`;
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
domcont=` host -t SRV _ldap._tcp.$doms | awk '{print $NF}' | head -1 | rev | cut -c 2- | rev `;
#domcont=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
privilege="Active_Directory";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == "true" ]];
then
echo contrun $contrun
domcontip=` host $domcont | head -1 |  awk '{print $NF}'`
ip1=` echo $domcontip | awk -F. '{print $1}'`;
ip2=` echo $domcontip | awk -F. '{print $2}'`;
ip3=` echo $domcontip | awk -F. '{print $3}'`;
ip4=` echo $domcontip | awk -F. '{print $4}'`;
echo Domain1000:$domain > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Domain_change:'$domain;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1003@@@$domain`;
echo Domain1003@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Domain1003@@@$domain $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
hostn=`hostname -s`;
cat $runningpools | grep $hostn
if [ $? -ne 0 ]; then
 echo pls configure storage first.;
	echo Domain1014:$domain > $web;
	cat $txtres  > ${web}internal;
	logdata='failed_joining_domain:'$domain;
        code='Domain1004@@@'$domain
 echo Domain1015@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
 echo $datenow $timenow error $userreq Domain1015@@@$domain $dtn>> $glog
	datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code $code`;
	oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
 
 exit;
fi
poolis=`cat $runningpools | grep $hostn | awk '{print $2}'`
hostname $hostn.$doms;
/usr/bin/sed -e "s/DOMSMALL/${doms}/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" dhclient.conf > /TopStordata/dhclient.conf 
cp /TopStordata/dhclient.conf /etc/dhclient.conf
sed -e "s/HOME/$poolis/g" -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMC/$domc/g" -e "s/DOMSH/$domshort/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" smb4.confDomain > /TopStordata/smb.conf 
cat /TopStordata/CIFSshares.txt >> /TopStordata/smb.conf;
cp /TopStordata/smb.conf /etc/samba/smb.conf;
#sed -e "s/DOMC/$domc/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMSH/$domshort/g" -e "s/CONT/$domcont/g" krb5.conf > /TopStordata/krb5.conf;
sed -i "/default\_realm/c\default\_realm \= $domc" /etc/krb5.conf
#cp /TopStordata/krb5.conf /etc/ ;
sed -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" ntp.conf > /TopStordata/ntp.conf ;
systemctl restart smb;
securessh=$(expect -c "
 set timeout 10
 spawn kinit $admin  ;
expect \"*assword*\"
send \"$pass\r\"
expect eof
")
realm leave $doms;
sleep 2;
realm leave $doms;
echo here
realm discover $doms   &>/dev/null
if [ $? -ne 0  ]; then
	echo Domain1101:$domain > $web;
	cat $txtres  > ${web}internal;
	logdata='Domain:'$domain'is_not_found';
        code='Domain1104@@@'$domain
echo Domain1104@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Domain1104@@@$domain $dtn>> $glog
else
 realm join $doms  2> $txtres ;
 if [ $? -ne 0  ]; then
	echo Domain1001:$domain > $web;
	cat $txtres  > ${web}internal;
	logdata='failed_joining_domain:'$domain;
        code='Domain1004@@@'$domain
 echo Domain1004@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
 echo $datenow $timenow error $userreq Domain1004@@@$domain $dtn>> $glog
 else 
  realm permit --all
  rm -rf /etc/samba/smb.conf &>/dev/null
  cp /TopStordata/smb.conf /etc/samba/smb.conf;
  systemctl enable smb
  systemctl restart smb
  sed -i "/fallback/c\fallback_homedir = \/$poolis\/\%u\@\%d" /etc/sssd/sssd.conf
  systemctl restart sssd
#  mkdir /$poolis/common
#  chmod 777 /$poolis/common
  echo Domain1002:$domain > $web; 
  logdata='success_changing_domain:'$domain;
  code='Domain1005@@@'$domain
  echo Domain1005@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
  echo $datenow $timenow info $userreq Domain1005@@@$domain $dtn>> $glog
 fi;
fi;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code $code`;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
