#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/DomainChangestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
domain=`echo $@ | awk '{ print $1 }' `;
domc=`echo $domain | tr '[:lower:]' '[:upper:]'`;
doms=`echo $domain | tr '[:upper:]' '[:lower:]'`;
domshort=` echo $domc | awk -F. '{ print $1 }'`;
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
domcont=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
echo $@ > /TopStordata/domworkgrp
privilege="Active_Directory";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == "true" ]];
then
echo contrun $contrun
domcontip='127.0.0.1' 
ip1=` echo $domcontip | awk -F. '{print $1}'`;
ip2=` echo $domcontip | awk -F. '{print $2}'`;
ip3=` echo $domcontip | awk -F. '{print $3}'`;
ip4=` echo $domcontip | awk -F. '{print $4}'`;
echo Domain1010:$domain > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Domain_change:'$domain;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1012@@@$domain`;
echo Domain1012@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Domain1012@@@$domain $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
hostn=`hostname | awk -F. '{print $1}'`;
hostnc=`echo $hostn | tr '[:lower:]' '[:upper:]'`;
hostname $hostn.$doms;
sed -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMC/$domc/g" -e "s/DOMSH/$domshort/g" -e "s/MYNAME/$hostnc/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" smb4.confWorkgrp > /TopStordata/smb.conf
cat CIFSshares.txt >> /TopStordata/smb.conf;
cp /TopStordata/smb.conf /etc/samba/smb.conf;
systemctl restart smb
echo Domain1011:$domain  > $web;
logdata='success_changing_Wrokgroup:'$domain;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info data $logdata user $userreq code Domain1013@@@$domain`;
echo Domain1013@$datenow@$timenow@$domain > ${logging}2 
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Domain1013@@@$domain $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
