#!/usr/local/bin/zsh
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/DomainChangestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
domain=`echo $@ | awk '{ print $1 }' `;
domc=`echo $domain | tr '[:lower:]' '[:upper:]'`;
doms=`echo $domain | tr '[:upper:]' '[:lower:]'`;
domshort=` echo $domc | awk -F. '{ print $1 }'`;
admin=`echo $@ | awk '{ print $2 }'`;
pass=`echo $@ | awk '{ print $3 }'`;
domcont=` echo $@ | awk '{ print $4 }'`
userreq=` echo $@ | awk '{ print $5 }'`;
echo $@ > /TopStordata/domworkgrp
privilege="Active_Directory";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == "true" ]];
then
echo contrun $contrun
domcontip='127.0.0.1' 
ip1=` echo $domcontip | awk -F. '{print $1}'`;
ip2=` echo $domcontip | awk -F. '{print $2}'`;
ip3=` echo $domcontip | awk -F. '{print $3}'`;
ip4=` echo $domcontip | awk -F. '{print $4}'`;
 /TopStor/logmsg.py Domain1012 info $userreq $domain
hostn=`hostname | awk -F. '{print $1}'`;
hostnc=`echo $hostn | tr '[:lower:]' '[:upper:]'`;
hostname $hostn.$doms;
sed -e "s/CONT/$domcont/g" -e "s/DOMSMALL/$doms/g" -e "s/DOMC/$domc/g" -e "s/DOMSH/$domshort/g" -e "s/MYNAME/$hostnc/g" -e "s/DOMIPCONT/$ip1\.$ip2\.$ip3\.$ip4/g" smb4.confWorkgrp > /TopStordata/smb.conf
cat CIFSshares.txt >> /TopStordata/smb.conf;
cp /TopStordata/smb.conf /etc/samba/smb.conf;
systemctl restart smb
 /TopStor/logmsg.py Domain1013 info $userreq $domain
fi
