#!/usr/local/bin/zsh
#cd /root/scripts
echo $@ > ~/tmp
TopStor='TopStor'
tmpdir='/root'
pace='pace'
web='var/www/html/des20/'
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
currentfw=`git branch | grep \* | awk '{print $2}'`
webfile='/var/www/html/des20/Data';
cd /$TopStor
newfw=`echo $@ | awk '{print $1}'`;
realfw=`echo $newfw | awk -F'.' '{print $1"."$2}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Uploadch";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 gpg --list-keys | grep Fwkey
 if [[ $? -ne 0 ]]; then
  cp /TopStor/key/*.gpg /root/.gnupg/
  gpg --import-ownertrust /TopStor/key/gpgowner.txt
 fi
 newd=$tmpdir/${newfw}.d
 mkdir $newd
 chmod 700 $newd
 gpg --batch --passphrase YousefNadody -d  $webfile/$newfw > ${newd}/${newfw}.tar.gz
 if [ $? -ne 0 ]; then 
  cd /$TopStor
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Upgrade file is not really valid ';
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Upnv1010@@`;
 echo Upnv1010@$datenow@$timenow > ${logging}2;
 dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
 echo $datenow $timenow error $userreq  Upnv1010@@ $dtn>> $glog
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
# rm -rf $newd
 exit
 fi
  cd /$TopStor
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 logdata='Start upgrading from version '$currentfw' to version '$realfw;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsa1010@@@$currentfw@$realfw`;
 echo Upsa1010@$datenow@$timenow@$currentfw@$realfw > ${logging}2;
 dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
 echo $datenow $timenow info $userreq  Upsa1010@@@$currentfw@$realfw $dtn>> $glog
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
 echo newfw=$newfw
 cd $newd
 tar -xvzf ${newfw}.tar.gz
 if [ $? -eq 0 ];
 then
  cd /$TopStor
  #git commit -am "prep to apply fw ${newfw}"
  #git checkout master
  #git checkout -b ${newfw}
  #git apply ${newd}/TopStordata/TopStor.p 
  rm -rf /$TopStor/.git
  rm -rf /$pace/.git
  rm -rf /$web/.git
  rsync -rt ${newd}/$TopStor/ /$TopStor/
  rsync -rt ${newd}/$pace/ /$pace/
  rsync -rt ${newd}/$web/ /$web/
  git checkout $newfw
  cd /$pace
  git checkout $newfw
  cd /$web
  git commit -am "changing to new fw" && git checkout $newfw
  cd /$TopStor
  datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
  logdata='Success upgrading from version '$currentfw' to version '$realfw;
  logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsu1010@@@$currentfw@$realfw`;
  echo Upsu1010@$datenow@$timenow@$currentfw@$realfw > ${logging}2;
  dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
  echo $datenow $timenow info $userreq  Upsu1010@@@$currentfw@$realfw $dtn>> $glog
  oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
 else
  datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
  logdata='Failed upgrading from version '$currentfw' to version '$realfw;
  logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Upfa1010@@@$currentfw@$realfw`;
  echo Upfa1010@$datenow@$timenow@$currentfw@$realfw > ${logging}2;
  dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
  echo $datenow $timenow error $userreq  Upfa1010@@@$currentfw@$realfw $dtn>> $glog
  oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
 fi
 # rm -rf $newd
fi
