#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des19/Data/Vollist.txtCIFS';
quota=`/sbin/zfs get -t filesystem -Hp quota | grep Data/  | awk -v CONVFMT=%2.5f '{gsub($3,$3/1048576); print $1" "$3}'`;
logicalused=`/sbin/zfs get -t filesystem -Hp logicalused | grep Data/ | awk -v CONVFMT=%.5g '{gsub($3,$3/1048576); print $1" "$3}'`
avail=`/sbin/zfs get -t filesystem -Hp avail | grep Data/ | awk -v CONVFMT=%.5g '{gsub($3,$3/1048576); print $1" "$3}'`;
used=`/sbin/zfs get -t filesystem -Hp used | grep Data/ | awk -v CONVFMT=%.5g '{gsub($3,$3/1048576); print $1" "$3}'` 
creation=`/sbin/zfs get -t filesystem -H creation | grep Data/  | awk  '{$3=$5"-"$4"-"$7; print $1" "$3}'`;
compressratio=`/sbin/zfs get -t filesystem -Hp compressratio | grep Data/ | awk  '{print $1" "$3}'`;
dedup=`/sbin/zfs get -t filesystem -Hp dedup | grep Data/ | awk '{print $1" "$3}'`;
NFSshare=`/sbin/zfs get -t filesystem -Hp sharenfs | grep Data/ | grep off | awk '{print $1}'`;
alllist="";
echo $NFSshare | while read -r line; do
	q=` echo $quota | grep $line | awk '{print $2}'`;
	lo=`echo $logicalused | grep $line | awk '{print $2}'`;
	av=`echo $avail | grep $line | awk '{print $2}'`;
	us=`echo $used | grep $line | awk '{print $2}'`;
	cr=`echo $creation | grep $line | awk '{print $2}'`;
	co=`echo $compressratio | grep $line | awk '{print $2}'`;
	de=`echo $dedup | grep $line | awk '{print $2}'`;
	line2=`echo $line | awk -F/ '{print $2}'`;
	alllist=$alllist$line2" "$q"_"$us"_"$snaps"_"$lo"_"$cr"_"$av"_"$co"_"$de" ";
done;
nameforjson=`echo $alllist | tr -d '\n'` ;
jsonname=`./jsonthis2.sh $nameforjson`;
echo $jsonname > $websnaps 2>txt/err.txt

