#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des19/Data/Minutelylist.txt';
list=`crontab -l | awk -F"now" '{print $2}' 2>/dev/null`;
echo $list;
result='[';
echo $list | while read -r line;
do
 father=`echo $line | awk '{print $1}' | awk -F/ '{print $2}' `;
 echo $father;
 ts=` echo $line | awk '{print $2}'`;
 period=`echo $ts | awk -F. '{print $1}' `;
 t1=` echo $ts  | awk -F. '{print $2}'`;	 
 t2=` echo $ts | awk -F. '{print $3}'`;
 t3=` echo $ts | awk -F. '{print $4}'`;
 t4=` echo $ts | awk -F. '{print $5}'`;
 subres=` /usr/local/bin/zsh jsonthis3.sh period $period father $father t1 $t1 t2 $t2 t3 $t3 t4 $t4`;
 result=$result$subres,
done
result=${result%?}]
echo $result
echo $result > $websnaps 2>txt/err.txt

