#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/var/www/html/des20/Data/periodlist.txt';
resweb='/var/www/html/des20/Data/periodlist.txtupdated';
list=`/usr/bin/crontab -l | grep -w Snapshotnowhost | awk -F"nowhost" '{print $2}' 2>/dev/null`;
result='[';
echo $list | while read -r line;
do
 father2=`echo $line | awk '{print $1}' | awk -F/ '{print $2}' `;
 father=`echo $line | awk '{print $1}' | awk -F/ '{print $3}' `;
 stamp=`echo $line | awk '{print $NF}'`
echo $father2 $line
 ts=` echo $line | awk '{print $2}'`;
 period2=`echo $ts | awk -F. '{print $1}' `;
 t1=` echo $ts  | awk -F. '{print $2}'`;	 
 t2=` echo $ts | awk -F. '{print $3}'`;
 t3=` echo $ts | awk -F. '{print $4}'`;
 t4=` echo $ts | awk -F. '{print $5}'`;
 subres=` /usr/local/bin/zsh jsonthis3.sh stamp $stamp period $period2 father $father pool $father2 t1 $t1 t2 $t2 t3 $t3 t4 $t4` ;
 result=$result$subres,
done
result=` echo $result | rev | cut -c 2- | rev`];
echo $result > $websnaps ;
resdate=`date +%s`;
res=`./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
