#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des19/Data/Vollist.txt';
quota=`/sbin/zfs get -Hp quota | grep Data/ | grep -v @ | awk -v CONVFMT=%.3g '{gsub($3,$3/1000000000); print $1" "$3}'`;
logicalused=`/sbin/zfs get -Hp logicalused | grep Data/ | grep -v @ | awk -v CONVFMT=%.3g '{gsub($3,$3/1000000000); print $1" "$3}'`
avail=`/sbin/zfs get -Hp avail | grep Data/ | grep -v @ | awk -v CONVFMT=%.3g '{gsub($3,$3/1000000000); print $1" "$3}'`;
used=`/sbin/zfs get -Hp used | grep Data/ | grep -v @ | awk -v CONVFMT=%.3g '{gsub($3,$3/1000000000); print $1" "$3}'` 
creation=`/sbin/zfs get -H creation | grep Data/ | grep -v @ | awk  '{$3=$5"-"$4"-"$7; print $1" "$3}'`;
compressratio=`/sbin/zfs get -Hp compressratio | grep Data/ | grep -v @ | awk  '{print $1" "$3}'`;
dedup=`/sbin/zfs get -Hp dedup | grep Data/ | grep -v @ | awk '{print $1" "$3}'`;
echo q=$quota 
echo lo=$logicalused
echo av=$avail
echo us=$used
echo cr=$creation
echo co=$compressratio
echo ded=$dedup
alllist="";
echo $avail | awk '{print $1}' | while read -r line; do
	snaps=`/sbin/zfs list -t snapshot | grep "$line" | wc -l | sed 's/ //g'`
	q=` echo $quota | grep $line | awk '{print $2}'`;
	lo=`echo $logicalused | grep $line | awk '{print $2}'`;
	av=`echo $avail | grep $line | awk '{print $2}'`;
	us=`echo $used | grep $line | awk '{print $2}'`;
	cr=`echo $creation | grep $line | awk '{print $2}'`;
	co=`echo $compressratio | grep $line | awk '{print $2}'`;
	de=`echo $dedup | grep $line | awk '{print $2}'`;
	line2=`echo $line | awk -F/ '{print $2}'`;
	alllist=$alllist$line2" "$q"_"$us"_"$snaps"_"$lo"_"$cr"_"$av"_"$co"_"$de" ";
done;
echo alllist=$alllist
nameforjson=`echo $alllist | tr -d '\n'` ;
echo $nameforjson; 
jsonname=`./jsonthis2.sh $nameforjson`;
echo $jsonname > $websnaps 2>txt/err.txt

