#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/usr/local/www/apache24/data/des19/Data/Weeklylist.txt';
list1=`crontab -l | awk -F"now" '{print $2}' | grep Weekly 2>/dev/null`; 
list2=`echo $list1 | awk '{print $1"@"$2" "$2" "}'`;  
nameforjson=`echo $list2 | tr -d '\n'` ;
jsonname=`./jsonthis2.sh $nameforjson`;
echo $jsonname > $websnaps 2>txt/err.txt

