#!/bin/python3.6

import subprocess

def getversions():
 cmdline='git branch'
 versions = []
 verdict = dict()
 result=subprocess.run(cmdline.split(),stdout=subprocess.PIPE).stdout
 for res in result.decode('utf-8').split('\n'):
  if 'QS' in res:
   if '*' in res:
    cversion = res.split('QS')[1]
   versions.append(res.split('QS')[1])
 verdict = { 'versions': versions, 'current': cversion } 
 return verdict 

if __name__=='__main__':
 getversions()
