#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
hostname=`hostname -s`
dev='enp0s8'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
leader=`./etcdget.py leader --prefix | awk -F'/' '{print $2}' | awk -F"'" '{print $1}'`
myip=`./etcdget.py ready/$hostname`
gateway=`./etcdget.py dnssearch/$leader`
./etcdput.py dnsname/$hostname $gateway
./broadcasttolocal.py dnssearch/$hostname $gateway
echo search $gateway > >/etc/resolv.conf
