#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/mgmtip
leader=`echo $@ | awk '{print $1}'`
leaderip=`echo $@ | awk '{print $2}'`
myhost=`echo $@ | awk '{print $3}'`
hostip=`echo $@ | awk '{print $4}'`
myclusterdev='enp0s8'
newip=`/TopStor/etcdget.py $leaderip namespace/mgmtip`
nmcli conn mod mycluster ipv4.addresses $newip 
echo checking $leader $myhost >> /root/tmpnamespace
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
 echo addingpls >> /root/tmpnamespace
 ./etcdput.py $leaderip rebootme/$myhost pls
fi
#/sbin/reboot
