#!/usr/local/bin/zsh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
hostname=`hostname -s`
rm -rf $txtres &>/dev/null
hostn=`echo $@ | awk '{ print $1 }' `;
hostip=`echo $@ | awk '{ print $2 }'`;
hostrout=`echo $@ | awk '{ print $3 }'`;
hostdns=` echo $@ | awk '{ print $4 }'`
subnet=` echo $@ | awk '{ print $5 }'`;
userreq=` echo $@ | awk '{ print $6 }'`;
privilege="Error";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]];
then
  /TopStor/logmsg.py HostManual1002 info $userreq
chattr -i /etc/resolv.conf
sed -i "/nameserver/c\nameserver $hostdns" /etc/resolv.conf
chattr +i /etc/resolv.conf
grep GATEWAY /etc/sysconfig/network-scripts/ifcf* | awk -F: '{print $1}' | sort -u | xargs sed -i "/GATEWAYc\GATEWAY\=$hostrout"  2>/dev/null
#sed -e "s/HOSTNAME/$hostn/g" -e "s/IPADD/$hostip/g" -e "s/ROUTE/$hostrout/g" rc.conf > txt/rc.conf
#sed -ri  "s/(https:\/\/)[^=]*$/\1$hostip\//g" /etc/httpd/conf.d/sshhttp.conf 
sed -e "s/HOSTY/$hostip/g" /TopStor/sshhttp.conf > /etc/httpd/conf.d/sshhttp.conf
CC=`pcs resource | grep IPaddr2 | awk '{print $1}' | grep -v cluster`
echo CCis $CC
oldip=`pcs resource show $CC | grep Attrib | awk '{print $2}' | awk -F'=' '{print $2}'`
oldsubnet=`pcs resource show $CC | grep Attrib | awk '{print $4}' | awk -F'=' '{print $2}'`
dev=`pcs resource show $CC | grep Attrib | awk '{print $3}' | awk -F'=' '{print $2}'`
pcs resource update $CC ip=$hostip
pcs resource update $CC cidr_netmask=$subnet
pcs resource debug-stop $CC
pcs resource debug-start $CC
/sbin/ip addr del ${oldip}/$oldsubnet dev $dev
oldhostn=`cat /TopStordata/hostname`
/pace/keysend.sh
echo $hostn > /TopStordata/hostname
#sed -i "s/$oldhostn/$hostn/g" $runningpools
sed -i "/$hostname/s/\w*\$//" $runningpools
sed -i "/$hostname/s/\$/$hostn/" $runningpools
/pace/keysend.sh
  /TopStor/logmsg.py HostManual1003 info $userreq $hostn ${hostip}'/'${subnet} $hostrout $hostdns
fi
/pace/keysend.sh
