#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/alias
hostname=`hostname -s`
dev='enp0s8'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
gateway=`ETCDCTL_API=3 /TopStor/etcdget.py gw/$hostname`
myhost=$hostname
stamp=`date +%s%N`
./etcdput.py sync/Alias/$myhost $stamp 
./broadcasttolocal.py sync/Alias/$myhost $stamp 
