#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
dev='eno1'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
hostname=`hostname -s`
rm -rf $txtres &>/dev/null
hostip=`echo $@ | awk '{ print $1 }'`;
subnet=` echo $@ | awk '{ print $3 }'`;
oldip=`echo $@ | awk '{ print $2 }'`;
oldsubnet=` echo $@ | awk '{ print $4 }'`;
/sbin/pcs resource | grep dataip
if [ $? -eq 0 ];
then 
 dev=`/sbin/pcs resource show dataip | grep Attrib | awk -F'nic=' '{print $2}' | awk '{print $1}'`
 /sbin/pcs resource update dataip ip=$hostip
 /sbin/pcs resource update dataip cidr_netmask=$subnet
 /sbin/ip addr del ${oldip}/$oldsubnet dev $dev
else
 /sbin/pcs resource create dataip ocf:heartbeat:IPaddr2 ip=$hostip nic=$dev cidr_netmask=$subnet op monitor interval=5s on-fail=restart
#/sbin/reboot
fi
ETCDCTL_API=3 /pace/etcdput.py dataip $hostip/$subnet/$dev
ETCDCTL_API=3 /pace/broadcasttolocal.py dataip $hostip/$subnet/$dev
