#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/cftmp
cf=`echo $@ | awk '{print $1}'`
myhost=`hostname`
myip=`./etcdget.py ready/$myhost`
leader=`./etcdget.py leader --prefix`
echo $leader | grep $myip 
if [ $? -eq 0 ];
then
 ./etcdput.py configured $cf
else
 ./etcdput.py $myip configured $cf
fi
