#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
leader=`echo $@ | awk '{print $1}'`
leaderip=`echo $@ | awk '{print $2}'`
myhost=`echo $@ | awk '{print $3}'`
myip=`echo $@ | awk '{print $4}'`
hostname=$myhost
dev='enp0s8'
gateway=`ETCDCTL_API=3 /TopStor/etcdget.py $leaderip gw/$leader`
oldgateway=`ip route | grep default | awk '{print $3}'`
echo $gateway | grep '\.'
if [ $? -ne 0 ];
then
 echo $oldgateway | grep '\.'
 if [ $? -ne 0 ];
 then
  oldgateway='NoGateway'
 fi
else
 ./etcdput.py $myip gw/$hostname $gateway
 ./etcdput.py $leaderip gw/$hostname $gateway
 echo $oldgateway | grep '\.'
 if [ $? -eq 0 ];
 then
  route del default gw $oldgateway 
 fi
 route add default gw $gateway
fi
