#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 ./logqueue.py HostManaulconfigTZ running system 
fi
hostname=`hostname -s`
dev='enp0s8'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
tz=`ETCDCTL_API=3 ./etcdget.py tz/$hostname | awk -F'%' '{print $1}' `
tzone=`timedatectl list-timezones | grep $tz` 
timedatectl set-timezone $tzone
ctz=`timedatectl | grep zone | awk -F'zone:' '{print $2}' | awk '{print $1}'`
echo ctz=$ctz  tzone=$tzone etcdtz=$tz
echo $tzone | grep $ctz
if [ $? -ne 0 ];
then 
 echo init
 tzone='Africa/Cairo'
 timedatectl set-timezone $tzone
 ./etcdput.py tz/$hostname $tzone 
 
fi
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 ./logqueue.py HostManaulconfigTZ stop system 
fi
