#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
hostname=`hostname -s`
dev='enp0s8'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
leader=`./etcdget.py leader --prefix | awk -F'/' '{print $2}' | awk -F"'" '{print $1}'`
myip=`./etcdget.py ready/$hostname`
gateway=`./etcdget.py gw/$leader`
./etcdput.py gw/$hostname $gateway
#./broadcasttolocal.py gw/$hostname $gateway
oldgateway=`ip route | grep default | awk '{print $3}'`
echo $gateway | grep '\.'
if [ $? -ne 0 ];
then
 echo $oldgateway | grep '\.'
 if [ $? -ne 0 ];
 then
  oldgateway='NoGateway'
 fi
 ./etcdput.py gw/$hostname $oldgateway
# ./broadcasttolocal.py gw/$hostname $oldgateway
else
 echo $oldgateway | grep '\.'
 if [ $? -eq 0 ];
 then
  route del default gw $oldgateway 
 fi
 route add default gw $gateway
fi
