#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
hostname=`hostname -s`
dev='enp0s8'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
gateway=`ETCDCTL_API=3 /TopStor/etcdget.py gw/$hostname`
oldgateway=`ip route | grep default | awk '{print $3}'`
leader=`./etcdget.py leader --prefix`
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
echo $leader | grep $hostname
if [ $? -eq 0 ];
then
 local=''
  myip=''
else
 local='local'
fi

echo $gateway | grep '\.'
if [ $? -ne 0 ];
then
 echo $oldgateway | grep '\.'
 if [ $? -ne 0 ];
 then
  oldgateway='NoGateway'
 fi
 ./etcdput.py${local} $myip gw/$hostname $oldgateway
 
else
 echo $oldgateway | grep '\.'
 if [ $? -eq 0 ];
 then
  route del default gw $oldgateway 
 fi
 route add default gw $gateway
fi
