#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
dev='enp0s8'
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
hostname=`hostname -s `
myip=`echo $@ | awk '{print $1}'`
leader=`echo $@ | awk '{print $2}'`
tz=`ETCDCTL_API=3 ./etcdget.py tz/$leader | awk -F'%' '{print $1}' `
tzone=`timedatectl list-timezones | grep $tz` 
timedatectl set-timezone $tzone
./etcdput.py tz/$hostname $tzone 
./etcdputlocal.py $myip tz/$hostname $tzone 
ctz=`date +%Z`
echo ctz=$ctz  tzone=$tzone etcdtz=$tz
echo $tzone | grep $ctz
if [ $? -ne 0 ];
then 
 tzone='Africa/Cairo'
 timedatectl set-timezone $tzone
fi
