#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
hostname=`hostname -s`
rm -rf $txtres &>/dev/null
hostip=`echo $@ | awk '{ print $1 }'`;
subnet=` echo $@ | awk '{ print $3 }'`;
oldip=`echo $@ | awk '{ print $2 }'`;
oldsubnet=` echo $@ | awk '{ print $4 }'`;
dev=`/sbin/pcs resource show mgmtip | grep Attrib | awk -F'nic=' '{print $2}' | awk '{print $1}'`
/sbin/pcs resource update mgmtip ip=$hostip
/sbin/pcs resource update mgmtip cidr_netmask=$subnet
/sbin/ip addr del ${oldip}/$oldsubnet dev $dev
#/sbin/reboot
