#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Hostprop.txt';
Topweb='/TopStordata/Hostprop.txt';
hostname=`hostname`
hostn=`/TopStor/etcdget.py alias/$hostname`
hostip=`pcs resource show CC | grep Attributes | awk -F'ip=' '{print $2}' | awk '{print $1}'`
hostsubnet=`pcs resource show CC | grep Attributes | awk -F'netmask=' '{print $2}' | awk -F= '{print $1}'`

mgmtip=`pcs resource show mgmtip | grep Attributes | awk -F'ip=' '{print $2}' | awk '{print $1}'`
mgmtsubnet=`pcs resource show mgmtip | grep Attributes | awk -F'netmask=' '{print $2}' | awk -F= '{print $1}'`
hostrout=`netstat -rn | awk '{print $2}' | grep -v "Gateway" | grep -v "IP" | grep -v "0.0.0.0"`;
hostdns=` cat /etc/resolv.conf | grep nameserver | awk '{print $2}'`;
jsonips=`/usr/local/bin/zsh jsonthis3.sh hostname $hostname name $hostn addr $hostip hostsubnet $hostsubnet rout $hostrout dns $hostdns mgmtip $mgmtip mgmtsubnet $mgmtsubnet`;
ETCDCTL_API=3 /pace/etcdput.py prop/$hostname $jsonips
echo $jsonips > $web; 
echo $jsonips > $Topweb; 
