#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/mgmtip
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
myhost=`hostname -s`
rm -rf $txtres &>/dev/null
hostip=`echo $@ | awk '{ print $1 }'`;
subnet=` echo $@ | awk '{ print $3 }'`;
oldip=`echo $@ | awk '{ print $2 }'`;
oldsubnet=` echo $@ | awk '{ print $4 }'`;
dev=`/sbin/pcs resource show mgmtip | grep Attrib | awk -F'nic=' '{print $2}' | awk '{print $1}'`
/sbin/pcs resource update mgmtip ip=$hostip
/sbin/pcs resource update mgmtip cidr_netmask=$subnet
/sbin/ip addr del ${oldip}/$oldsubnet dev $dev
configured=`ETCDCTL_API=3 ./etcdget.py configured/$myhost`
echo $configured  | grep no
if [ $? -eq 0 ];
then
 ./etcdput.py configured/$myhost semiName
else
 echo $configured | grep semi | grep -v Name 
 if [ $? -eq 0 ];
 then
  ./etcdput.py configured/$myhost yes
  echo $myhost $hostip > /TopStordata/members 
  ./etcdget.py frstnode | grep dhcp
  if [ $? -ne 0 ];
  then
   ./etcdget.py frstnode $myhost
  fi
 fi
fi
echo $configured | grep yes 
if [ $? -eq 0 ];
then
 ./UpdateHosts $myhost $hostip
fi
stamp=`date +%s%N`
./etcdput.py sync/namespace/$myhost $stamp 
./broadcasttolocal.py sync/namespace/$myhost $stamp 

#/sbin/reboot
