#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
leader=`echo $@ | awk '{print $1}'`
leaderip=`echo $@ | awk '{print $2}'`
myhost=`echo $@ | awk '{print $3}'`
myip=`echo $@ | awk '{print $4}'`
hostname=$myhost
dev='enp0s8'
dns=`ETCDCTL_API=3 /TopStor/etcdget.py $leaderip dnsname/$leader`
searchdns=`ETCDCTL_API=3 /TopStor/etcdget.py $leaderip dnssearch/$leader`
olddns=`cat /etc/resolv.conf | grep nameserver | head -1 | awk '{print $2}'`
olddnssearch=`cat /etc/resolv.conf | grep search | head -1 | awk '{print $2}'`
echo $dns | grep .
if [ $? -ne 0 ];
then
echo leader=$leader, dns=$dns, searchdns=$searchdns
 echo $olddns | grep '\.'
 if [ $? -ne 0 ];
 then
  olddns='NoDNS'
 fi
else
 ./etcdput.py $myip dnssearch/$hostname $searchdns
 ./etcdput.py $myip dnsname/$hostname $dns
 ./etcdput.py $leaderip dnssearch/$hostname $searchdns
 ./etcdput.py $leaderip dnsname/$hostname $dns
 echo 'supersede domain-name-server '$dns';' > /etc/dhcp/dhclient.conf
 echo nameserver $dns > /etc/resolv.conf
 echo $searchdns | grep '\-1'
 if [ $? -ne 0 ];
 then
  echo 'supersede domain-search "'$searchdns'";' >> /etc/dhcp/dhclient.conf
  echo search $searchdns >> /etc/resolv.conf
  nmcli con mod mynode ipv4.dns-search $searchdns 
  nmcli con mod cmynode ipv4.dns-search $searchdns
  nmcli con mod mycluster ipv4.dns-search $searchdns 
 else
  sed -i '/search/d' /root/resolv.conf 
  nmcli con mod mynode ipv4.dns-search '' 
  nmcli con mod cmynode ipv4.dns-search '' 
  nmcli con mod mycluster ipv4.dns-search '' 
 fi
 nmcli con mod mynode ipv4.dns $dns 
 nmcli con mod cmynode ipv4.dns $dns 
 nmcli con mod mycluster ipv4.dns $dns 
 #systemctl restart network
fi
