#!/usr/local/bin/zsh
web='/usr/local/www/apache24/data/des19/Data/status.log';
rm txt/err; 
hostn=`echo $@ | awk '{ print $1 }' `;
sed -e "N;s/hostname.*/hostname\=\"$hostn\"/g" /etc/rc.conf > txt/rc.conf
cp txt/rc.conf /etc/rc.conf
sysctl kern.hostname=$hostn
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...user $hostn is added > $web; 
fi;
