#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/`basename "$0"`
hostname=`hostname -s`
dev='enp0s8'
leader=`./etcdget.py leader --prefix | awk -F'/' '{print $2}' | awk -F"'" '{print $1}'`
dns=`ETCDCTL_API=3 /TopStor/etcdget.py dnsname/$leader`
searchdns=`ETCDCTL_API=3 /TopStor/etcdget.py dnssearch/$leader`
olddns=`cat /etc/resolv.conf | grep nameserver | head -1 | awk '{print $2}'`
olddnssearch=`cat /etc/resolv.conf | grep search | head -1 | awk '{print $2}'`
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
echo $leader | grep $hostname
if [ $? -eq 0 ];
then
 local=''
 myip=''
else
 local='local'
fi
echo $dns | grep .
if [ $? -ne 0 ];
then
echo leader=$leader, dns=$dns, searchdns=$searchdns
 echo $olddns | grep '\.'
 if [ $? -ne 0 ];
 then
  olddns='NoDNS'
 fi
else
 ./etcdput.py $myip dnssearch/$hostname $searchdns
 ./etcdput.py $myip dnsname/$hostname $dns
 ./etcdput.py $leaderip dnssearch/$hostname $searchdns
 ./etcdput.py $leaderip dnsname/$hostname $dns
 echo 'supersede domain-name-server '$dns';' > /etc/dhcp/dhclient.conf
 echo nameserver $dns > /etc/resolv.conf
 echo $searchdns | grep '\-1'
 if [ $? -ne 0 ];
 then
  echo 'supersede domain-search "'$searchdns'";' >> /etc/dhcp/dhclient.conf
  echo search $searchdns >> /etc/resolv.conf
 fi
 nmcli con mod mynode ipv4.dns $dns 
 nmcli con mod cmynode ipv4.dns $dns 
 nmcli con mod mycluster ipv4.dns $dns 
 nmcli connection reload
 #systemctl restart network
fi
