#!/usr/local/bin/zsh
cd /TopStor/;
resfile=`echo $@ | awk '{print $1}'`;
websnaps='/var/www/html/des20/Data/listsnaps.txt';
resweb='/var/www/html/des20/Data/listsnaps.txtupdated';
namearray=`/sbin/zfs list -t snapshot -H -o name,creation,repli:sender,repli:receiver`; 
result='[';
echo "$namearray" | while read -r line 
do
 name=` echo $line | awk '{print $1}'`;
 onlyname=` echo $name | awk -F@ '{print $2}'`;
 father2=` echo $name | awk -F@ '{print $1}' | awk -F/ '{print $2}'`;
 revcreat=` echo $line | awk '{print $2" "$3" "$4"  "$5" "$6}' | rev`; 
 creat=`echo ${revcreat:0:5}':'${revcreat:5} | rev`
 creall=`/bin/date -j -f %c $creat +%m/%d/%y_%R`;
 creatform=` echo $creall | awk -F_ '{print $1}'`;
 time2=` echo $creall | awk -F_ '{print $2}'`;
 sender=`echo $line | awk '{print $7}'`;
 receiver=`echo $line | awk '{print $8}'`;
 subres=`/usr/local/bin/zsh jsonthis3.sh name $name onlyname $onlyname father $father2 creation $creatform time $time2 sender $sender receiver $receiver `;
 result=$result$subres,;
done
 result=`echo $result | rev | cut -c 2- | rev`];
echo $result >$websnaps;
resdate=`date +%s`;
res=` ./jsonthis3.sh updated $resdate`;
#echo $res > $resweb;
echo ready > $resfile
