#!/usr/local/bin/zsh
webpartner='/var/www/html/des20/Data/Partnerslist.txt';
resweb='/var/www/html/des20/Data/Partnerslist.txtupdated'
web='/var/www/html/des20/Data/Partnersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
partners='/TopStordata/partners.txt'
Partnername=`echo $@ | awk '{print $1}'`;
type=`echo $@ | awk '{print $2}'`;
Proxy=`echo $@  | awk '{print $3}'`;
passphrase=`echo $@  | awk '{print $4}'`;
portused=`echo $@  | awk '{print $5}'`;
userreq=`echo $@  | awk '{print $6}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 ETCDCTL_API=3 /TopStor/logmsg.py Partner1007 info $userreq $Partnername
isthere=`cat $partners | grep "$Partnername $type" | wc -c `
isthere=$((isthere+0));
if [[ $isthere -ge 2 ]]; then
 ETCDCTL_API=3 /TopStor/logmsg.py Partner1008 warning $userreq $Partnername
else
partnerlist=`cat $partners `;
istherpartners=` echo $partnerlist | wc -c`;
istherpartners=$((istherpartners+0));
if [[ $istherpartners -ge 2 ]]; then
echo $partnerlist | grep -v "$Partnername" > $partners 
fi
newtype=$type;
oldtype=`echo $partnerlist | grep "$Partnername" | awk '{print $2}'`;
if [[ $oldtype == "sender" && $type == "receiver" ]]; then newtype="DualWay";fi
if [[ $oldtype == "receiver" && $type == "sender" ]]; then newtype="DualWay";fi
echo $Partnername $newtype $Proxy $passphrase $portused >> $partners
./Partnerprep $Partnername
touch /TopStordata/$portused;
result="[";
cat $partners | while read -r line ; do
  n=` echo $line | awk '{print $1}'`; 
  t=`echo $line | awk '{print $2}'`;
  p=`echo $line | awk '{print $3}'`;
  pass=`echo $line | awk '{print $4}'`;
  subres=`./jsonthis3.sh name $n type $t proxy $p passphrase $pass`;
  result=$result$subres,
done;
result=`echo $result | rev | cut -c 2- | rev`];
echo $result >$webpartner;
resdate=`date +%s`;
res=` ./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
 ETCDCTL_API=3 /TopStor/logmsg.py Partner1009 info $userreq $Partnername $newtype
fi
fi
