#!/usr/local/bin/zsh
cd /TopStor
webpartner='/var/www/html/des20/Data/Partnerslist.txt';
resweb='/var/www/html/des20/Data/Partnerslist.txtupdated'
web='/var/www/html/des20/Data/Partnersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
partners='/TopStordata/partners.txt'
echo $@ >> tmppartner
Partnername=`echo $@ | awk '{print $1}'`;
#type=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $2}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Partner1003:$Partnername > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_partner:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Partner1005@@@$Partnername`;
echo Partner1005@$datenow@$timenow@$Partnername > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Partner1005@@@$Partnername $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
partnerlist=`cat $partners `;
echo $partnerlist | grep "$Partnername" > /TopStordata/PartnerDel
echo $partnerlist | grep -v "$Partnername" > $partners
result="[";
cat $partners | while read -r line ; do
  n=` echo $line | awk '{print $1}'`;  
  t=`echo $line | awk '{print $2}'`;
  p=`echo $line | awk '{print $3}'`;
  subres=`./jsonthis3.sh name $n type $t proxy $p`;
  result=$result$subres,
done;
result=`echo $result | rev | cut -c 2- | rev`];
echo $result >$webpartner;
resdate=`date +%s`;
res=` ./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
echo Partner1004:$Partnername > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='success_Deleting_partner:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Partner1006@@@$Partnername`;
echo Partner1006@$datenow@$timenow@$Partnername > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Partner1006@@@$Partnername $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
fi
