#!/usr/local/bin/zsh
webpartner='/var/www/html/des20/Data/Partnerslist.txt';
resweb='/var/www/html/des20/Data/Partnerslist.txtupdated'
web='/var/www/html/des20/Data/Partnersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
partners='/TopStordata/partners.txt'
Partnername=`echo $@ | awk '{print $1}'`;
type=`echo $@ | awk '{print $2}'`;
Proxy=`echo $@  | awk '{print $3}'`;
passphrase=`echo $@  | awk '{print $4}'`;
portused=`echo $@  | awk '{print $5}'`;
userreq=`echo $@  | awk '{print $6}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Parnter1000:$Partnername > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='adding_'$type'_partner:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Partner1007@@@$Partnername`;
echo Partner1007@$datenow@$timenow@$Partnername > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Partner1007@@@$Partnername $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
isthere=`cat $partners | grep "$Partnername $type" | wc -c `
isthere=$((isthere+0));
if [[ $isthere -ge 2 ]]; then
echo Partner1001:$Partnername > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='adding_'$type'_partner_already_there:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg warning user $userreq data $logdata code Partner1008@@@$Partnername`;
echo Partner1008@$datenow@$timenow@$Partnername > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow warning $userreq Partner1008@@@$Partnername $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
else
partnerlist=`cat $partners `;
istherpartners=` echo $partnerlist | wc -c`;
istherpartners=$((istherpartners+0));
if [[ $istherpartners -ge 2 ]]; then
echo $partnerlist | grep -v "$Partnername" > $partners 
fi
newtype=$type;
oldtype=`echo $partnerlist | grep "$Partnername" | awk '{print $2}'`;
if [[ $oldtype == "sender" && $type == "receiver" ]]; then newtype="DualWay";fi
if [[ $oldtype == "receiver" && $type == "sender" ]]; then newtype="DualWay";fi
echo $Partnername $newtype $Proxy $passphrase $portused >> $partners
./Partnerprep $Partnername
touch /TopStordata/$portused;
result="[";
cat $partners | while read -r line ; do
  n=` echo $line | awk '{print $1}'`; 
  t=`echo $line | awk '{print $2}'`;
  p=`echo $line | awk '{print $3}'`;
  pass=`echo $line | awk '{print $4}'`;
  subres=`./jsonthis3.sh name $n type $t proxy $p passphrase $pass`;
  result=$result$subres,
done;
result=`echo $result | rev | cut -c 2- | rev`];
echo $result >$webpartner;
resdate=`date +%s`;
res=` ./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
echo Partner1002:$Partnername:$newtype > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='success_adding_'$type'_partner:'$Partnername;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Partner1009@@@$Partnername@$newtype`;
echo Partner1009@$datenow@$timenow@$Partnername@$newtype > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Partner1009@@@$Partnername@$newtype $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging
fi
fi
