#!/usr/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/tmppartnerdel
cronthis='/TopStordata/cronthis.txt'
Partner=`echo $@ | awk '{print $1}'`;
issync=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Partner1003 info $userreq $Partner
 ./etcddel.py "" $Partner
  crontab -l | grep -v $Partner > $cronthis
  crontab $cronthis
  echo $issync | grep yes 
  if [ $? -ne 0 ];
  then
    stamp=`date +%s`;
    ./etcdput.py sync/Snapperioddel_${Partner}_${userreq}_/$myhost  $stamp
  fi
  /TopStor/logmsg.py Partner1004 info $userreq $Partner
fi
