#!/bin/sh
cd /TopStor
echo $@ > /root/tmp
privilege="User_Priv";
user=`echo $@ | awk '{print $2}'`
contrun="false";
userreq=` echo $@ | awk '{print $NF}'`;
contrun=` ./privthis.sh $privilege $userreq ` ;
if [[ $contrun == 'true' ]] 
then
web='/var/www/html/des20/Data/Privstatus.log';
userpriv='/var/www/html/des20/Data/userpriv.txt';
currentpriv='/TopStordata/userpriv.txt';
resweb='/var/www/html/des20/Data/userprivdate.txt';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='changing_Privileges_of_user:'$user;
echo Priv1000:$user  > $web
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Priv1002@@@$user`;
echo Priv1002@$datenow@$timenow@$user > ${logging}2;
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Priv1002@@@$user $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
touch $currentpriv
cat $currentpriv | grep -v "$user" > $currentpriv.tmp  2>/dev/null
mv $currentpriv.tmp $currentpriv
echo $@ >> $currentpriv
result="[";
while read -r line ; do
 subres=`./jsonthis3.sh $line`
 result=${result}$subres,
done < $currentpriv
result=`echo $result | rev | cut -c 2- | rev`];
echo $result > $userpriv;
ETCDCTL_API=3 /TopStor/Priv.py $@ 
logdata='Success_changing_UserPrivileges:'$user;
echo Priv1001:$user > $web
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Priv1003@@@$user`;
echo Priv1003@$datenow@$timenow@$user > ${logging}2;
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Priv1003@@@$user $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
resdate=`date +%s`;
res=`./jsonthis3.sh updated $resdate`;
echo $res > $resweb ;
fi
