#!/bin/sh

. /etc/rc.subr

name="QuickStor"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
rcvar=TopStor_enable
command="/TopStor/Quickstor.sh"
command_interpreter="/usr/local/bin/zsh"
load_rc_config $name
: ${QuickStor_enable:=no}
: ${TopStor_msg="QuickStor started successfully."}
QuickStor_start()
{
	echo "$TopStor_msg"
	/TopStor/Quickstor.sh &
}
QuickStor_stop()
{
	echo " it is stopped thanking God"
	pkill -HUP -f Quickstor
	touch /TopStor/txt/flag
}

run_rc_command "$1"
