#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/HostCCtmp
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
hostname=`hostname -s`
rm -rf $txtres &>/dev/null
hostip=`echo $@ | awk '{ print $1 }'`;
subnet=` echo $@ | awk '{ print $3 }'`;
oldip=`pcs resource show CC | grep Attribute | awk -F'ip=' '{print $2}' | awk '{print $1 }'`
oldsubnet=` echo $@ | awk '{ print $4 }'`;
echo hi > /root/HostCC2
echo shuttingdown 1 >> /root/HostCC2
/sbin/zpool export -a 
echo shuttingdown 2 >> /root/HostCC2
#/pace/keysend.sh $hostip
/sbin/rabbitmqctl stop_app
echo shuttingdown 3 >> /root/HostCC2
/sbin/iscsiadm --mode node --logoutall=all
echo shuttingdown 4 >> /root/HostCC2
/sbin/pcs resource update CC ip=$hostip
echo shuttingdown 5 for ip=$hostip mask=$subnet >> /root/HostCC
echo shuttingdown 6 >> /root/HostCC2
systemctl stop httpd
echo shuttingdown 7 >> /root/HostCC2
echo 127.0.0.1 localhost > /etc/hosts
echo $hostip $hostname >> /etc/hosts
echo 127.0.0.1 $hostname >> /etc/hosts
#/sbin/ip addr del ${oldip}/$oldsubnet dev $dev
echo shuttingdown 8 >> /root/HostCC2
/sbin/reboot
