#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/rebootme
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
myhost=`hostname -s`
rm -rf $txtres &>/dev/null
#hostip=`echo $@ | awk '{ print $1 }'`;
#subnet=` echo $@ | awk '{ print $3 }'`;
#oldip=`pcs resource show CC | grep Attribute | awk -F'ip=' '{print $2}' | awk '{print $1 }'`
#oldsubnet=` echo $@ | awk '{ print $4 }'`;
echo wait
echo hi > /root/HostCC2
echo shuttingdown 1 >> /root/HostCC2
echo shuttingdown 1 
mkdir /tmp/cpools 2>/dev/null
rm -rf /tmp/cpools/*
pkill zfsping
docker stop $(docker ps -aq)
cp /TopStordata/pdhc* /tmp/cpools/
/sbin/zpool export -a ;
cp /tmp/cpools/* /TopStordata/
echo shuttingdown 2 >> /root/HostCC2
echo shuttingdown 2
#/pace/keysend.sh $hostip
/sbin/rabbitmqctl stop_app
echo shuttingdown 3 >> /root/HostCC2
echo shuttingdown 3
/sbin/iscsiadm --mode node --logoutall=all
echo shuttingdown 4 >> /root/HostCC2
echo shuttingdown 4 
echo shuttingdown 6 >> /root/HostCC2
whyreboot=`echo $@ | awk '{ print $1 }'`;
echo $whyreboot | grep ipchange
if [ $? -eq 0 ];
then
 oldip=`echo $@ | awk '{ print $2 }'`;
 oldipsubnet=`echo $@ | awk '{ print $3 }'`;
 newipsubnet=`echo $@ | awk '{ print $4 }'`;
 newipsubnet=`echo $@ | awk '{ print $5 }'`;
 /TopStor/HostManualconfigCC $@
fi
pkill httpd
echo shuttingdown 8 >> /root/HostCC2
sync
sync
sync
/sbin/reboot
