#!/usr/local/bin/zsh
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
pDG=` echo $@ | awk '{print $1}'`;
snapdel=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
  /TopStor/logmsg.py Replica1048 info $userreq $snapdel
./SnapshotDelete $pDG $snapdel $userreq 
./GetSnaplist
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Replica1050 info $userreq $snapdel
 privilege="SnapShots";
 contrun=`./privthis.sh $privilege $userreq`;
 echo success
else
  /TopStor/logmsg.py Replica1049 error $userreq $snapdel
 echo failed
fi
