#!/usr/local/bin/zsh
cd /TopStor/;
websnaps='/var/www/html/des20/Data/Remoteperiodlist.txt';
resweb='/var/www/html/des20/Data/Remoteperiodlist.txtupdated';
txtres='/TopStordata/'`basename $0`$userreq'.txt'
result='[]';
crontab -l | grep -w RemoteSnapshotnowOnce > $txtres
if [ $? -eq 0 ];
then
 list=(`/usr/bin/crontab -l  2>/dev/null`);
 result='[';
 while read -r line;
 do
  line=`echo $line | awk -F "nowOnce" '{print $2}' `
  echo line=$line
  echo $line | awk '{print $3}'
  father2=`echo $line | awk '{print $3}' | awk -F/ '{print $2}' `;
  echo father=$father2
  pool=`echo $line | awk '{print $3}' | awk -F/ '{print $1}' `;
  echo pool=$pool
  stamp=`echo $line | awk -F'.' '{print $NF}'`
  partner=` echo $line | awk '{print $5}'`;
  ts=` echo $line | awk '{print $4}'`;
  period2=`echo $ts | awk -F'.' '{print $1}' `;
  t1=` echo $ts  | awk -F'.' '{print $2}'`;	 
  t2=` echo $ts | awk -F'.' '{print $3}'`;
  t3=` echo $ts | awk -F'.' '{print $4}'`;
  t4=` echo $ts | awk -F'.' '{print $5}'`;
  subres=` /usr/local/bin/zsh jsonthis3.sh stamp $stamp period $period2 pool $pool father $father2 t1 $t1 t2 $t2 t3 $t3 t4 $t4 partner $partner` 
  result=$result$subres,
 done < $txtres
 result=` echo $result | rev | cut -c 2- | rev`];
fi
echo $result > $websnaps ;
resdate=`date +%s`;
res=`./jsonthis3.sh updated $resdate`;
echo $res > $resweb;
