#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools'
glog='/var/www/html/des20/Data/TopStor.log';
echo Replica1012: > $web;
name=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
partner=` echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]];
then
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 echo Replica1013:$hostnam/$DG/$FileS:$partner > $web;
 logdata='Replicating_manually:'$hostnam/$DG/$FileS' to'$partner;
 logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1033@@@$hostnam/$DG/$FileS@$partner`;
echo Replica1033@$datenow@$timenow@$hostnam/$DG/$FileS@$partner > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Replica1033@@@$hostnam/$DG/$FileS@$partner $dtn>> $glog
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
 echo ./RemoteSnapshotnowOnce $sshost $hostnam $DG/$FileS $name. $partner  $txtres 
 ./RemoteSnapshotnowOnce $sshost $hostnam $DG/$FileS $name. $partner  $txtres; 
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 cat $txtres | grep success &>/dev/null
 if [ $? -ne 0 ]; then
	echo Replica1014:$hostnam/$DG/$FileS:${partner}:$txtres > $web ;
	logdata='Failed_Replicating_manually:'$hostnam/$DG/$FileS' to'${partner}": "$txtres;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata cdoe Replica1034@@@$hostnam/$DG/$FileS@$partner@$$txtres`;
echo Replica1034@$datenow@$timenow@$hostnam/$DG/$FileS@$partner@$txtres > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Replica1034@@@$hostnam/$DG/$FileS@$partner@$txtres $dtn>> $glog
 else 
 	echo Replica1015:$hostnam/$DG/$FileS:$partner > $web; 
	logdata='Success_Replicating_manually:'$hostnam/$DG/$FileS' to'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1035@@@$hostnam/$DG/$FileS@$partner`;
echo Replica1035@$datenow@$timenow@$hostnam/$DG/$FileS@$partner > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Replica1035@@@$hostnam/$DG/$FileS@$partner $dtn>> $glog
 fi;
 oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
./GetPoolVollist
