#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
cronthis='/TopStordata/cronthis.txt'
stime=`echo $@ | awk '{print $1}'`;
hr=`echo $stime | awk -F: '{print $1}'`;
min=`echo $stime | awk -F: '{print $2}'`;
every=`echo $@ | awk '{print $2}'` ;
k=0; keep=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
pDG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
partner=` echo $@ | awk '{print $6}'`;
userreq=` echo $@ | awk '{print $7}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Replica1019: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Weekly_Preiod:'$hostnam/$DG/$FileS'_to_'$partner;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1030@@@.`;
echo Replica1030@$datenow@$timenow@. > ${logging}2;
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Replica1030@@@. $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > $cronthis
stamp=`date +%s`
echo $min  $hr "*" "*" $every  /TopStor/pump.sh RemoteSnapshotnowOnce $sshost $hostnam $DG/$FileS Weekly.$keep.$hr.$min.$every $partner ${txtres}.$stamp  >> $cronthis
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
crontab $cronthis 2>> $txtres
if [ $? -ne 0 ]; then
	echo Replica1020: > $web;
	cat $txtres > ${web}internal;
	logdata='Failed_Creating_Weekly_Replication_Period:'$hostnam/$DG/$FileS'_for_'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Replica1031`;
echo Replica1031@$datenow@$timenow@. > ${logging}2;
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Replica1031@@@. $dtn>> $glog
else 
	echo Replica1021:Weekly.$hr.$min.$every.$keep:$partner:$hostnam/$DG/$FileS > $web; 
	logdata='Success_Creating_Weekly_Replication_Period:'$hostnam/$DG/$FileS'_for_'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata Replica1032@@@Weekly.$hr.$min.$every.$keep@$partner@$hostnam/$DG/$FileS`;
echo Replica1032@$datenow@$timenow@Weekly.$hr.$min.$every.$keep@$partner@$hostnam/$DG/$FileS > ${logging}2;
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Replica1032@@@Weekly.$hr.$min.$every.$keep@$partner@$hostnam/$DG/$FileS $dtn>> $glog
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./RemoteGetPoolperiodlist 
fi
rm -rf ${txtres}.$stamp &>/dev/null
