#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
cronthis='/TopStordata/cronthis.txt'
rm $cronthis &>/dev/null
every=0; ev=`echo $@ | awk '{print $1}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $2}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $3}'`; 
FileS=` echo $@ | awk '{print $4}'`;
partner=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Replica1016: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Minutely_Replication_Period:'$hostnam/$DG/$FileS'_to_'$partner;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1036@@@.`;
echo Replica1036@${datenow}@${timenow}@. > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Replica1036@@@. $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
crontab -l > $cronthis
stamp=`date +%s`
echo "*"/$every "*" "*" "*" "*"  /TopStor/pump.sh RemoteSnapshotnowOnce $sshost $hostnam $DG/$FileS Minutely.$keep.$every.na.na. $partner ${txtres}.$stamp  >> $cronthis
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
crontab $cronthis 2>> $txtres
if [ $? -ne 0 ]; then
	echo Replica1017: > $web;
	cat $txtres  > ${web}internal;
	logdata='Failed_Creating_Minutely_Replication_Period:'$hostnam/$DG/$FileS'_for:'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Replica1037@@@.`;
echo Replica1037@${datenow}@${timenow}@. > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Replica1037@@@. $dtn>> $glog
else 
 echo Replica1018:Minutely.$every.$keep:$partner:$hostnam/$DG/$FileS > $web; 
	logdata='Success_Creating_Minutely_Replication_Period:'$hostnam/$DG/$FileS'_for_'$partner;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Replica1038@@@@Minutely.$every.$keep@$partner@$DG/$FileS`;
echo Replica1038@${datenow}@${timenow}@Minutely.$every.$keep@$partner@$DG/$FileS > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Replica1038@@@Minutely.$every.$keep@$partner@$DG/$FileS $dtn>> $glog
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./RemoteGetPoolperiodlist
fi
rm -rf ${txtres}.$stamp &>/dev/null
