#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
cronthis='/TopStordata/cronthis.txt'
rm $cronthis &>/dev/null
every=0; ev=`echo $@ | awk '{print $1}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $2}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $3}'`; 
FileS=` echo $@ | awk '{print $4}'`;
partner=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  ETCDCTL_API=3 /TopStor/logmsg.py Replica1036 info $userreq
crontab -l > $cronthis
stamp=`date +%s`
echo "*"/$every "*" "*" "*" "*"  /TopStor/pump.sh RemoteSnapshotnowOnce $sshost $hostnam $DG/$FileS Minutely.$keep.$every.na.na. $partner ${txtres}.$stamp  >> $cronthis
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
crontab $cronthis 2>> $txtres
if [ $? -ne 0 ]; then
 ETCDCTL_API=3 /TopStor/logmsg.py Replica1037 error $userreq
else 
 ETCDCTL_API=3 /TopStor/logmsg.py Replica1038 info $userreq Minutely.$every.$keep $partner $DG/$FileS
fi;
./RemoteGetPoolperiodlist
fi
rm -rf ${txtres}.$stamp &>/dev/null
