#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
pDG=` echo $@ | awk '{print $1}'`;
snaprol=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
 ETCDCTL_API=3 /TopStor/logmsg.py Replica1042 info $userreq $snaprol
./SnapShotRollback $pDG $snaprol $userreq
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun != 'true' ]]
then
 ETCDCTL_API=3 /TopStor/logmsg.py Replica1043 error $userreq $snaprol
else 
 ETCDCTL_API=3 /TopStor/logmsg.py Replica1044 info $userreq $snaprol
fi;
./GetSnaplist
