#!/usr/local/bin/zsh
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Replicatestatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
cronthis='/TopStordata/cronthis.txt'
min=`echo $@ | awk '{print $1}'` ;
every=0; ev=`echo $@ | awk '{print $2}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
partner=` echo $@ | awk '{print $6}'`;
userreq=` echo $@ | awk '{print $7}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Replica1039 info $userreq
crontab -l > $cronthis
stamp=`date +%s`
echo $min  "*"/$every "*" "*" "*"  /TopStor/pump.sh RemoteSnapshotnowOnce $sshost $hostnam $DG/$FileS hourly.$keep.$min.$every.na. $partner ${txtres}.$stamp >> $cronthis 
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
crontab $cronthis 2>> $txtres
if [ $? -ne 0  ]; then
  /TopStor/logmsg.py Replica1040 error $userreq
else 
stamp=`date +%s`
  /TopStor/logmsg.py Replica1041 info $userreq Hourly.$min.$every.$keep $partner $hostnam/$DG/$FileS
fi
./RemoteGetPoolperiodlist &
fi
rm -rf ${txtres}.$stamp &>/dev/null
