#!/usr/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/tmppartnerdel
myhost=` ./etcdgetlocal.py clusternode`
leaderip=` ./etcdgetlocal.py leaderip`
cronthis='/TopStordata/cronthis.txt'
Partner=`echo $@ | awk '{print $1}'`;
issync=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
privilege="Replication";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Partner1003 info $userreq $Partner
  leader=`./etcdgetlocal.py leader --prefix`
  echo $leader | grep $myhost
  if [ $? -eq 0 ];
  then
   isleader=$leaderip
   islocal=''
  else
   isleader=''
   islocal='local'
  fi
  issender=`echo $Partner | awk -F'_' '{print $2}'`
  partnerinfo=`./etcdgetlocal.py Partner/${Partner}` 
  clusterip=`echo $partnerinfo | awk -F'/' '{print $1}'`
  currentkeys=`cat /root/.ssh/authorized_keys`
  currenthosts=`cat /root/.ssh/known_hosts`
  nodes=`./etcdgetlocal.py node${issender}/$clusterip --prefix | awk -F'dhcp' '{print $2}' | sed "s/')//g" | sed 's/ /\//g' `
  hosts=`./etcdgetlocal.py node${issender}/$clusterip --prefix | awk -F"', '" '{print $1}' | awk -F"/" '{print $NF}'`
  echo clusterip=$clusterip
  echo currentkeys="$currentkeys"
  echo currenthosts="$currenthosts"
  echo hosts=$hosts
  echo nodes=$nodes
  echo $issender | grep Sender
  if [ $? -eq 0 ];
  then
   echo "$nodes" | while read r;
   do
    echo r=$r
    currentkeys=`echo  "$currentkeys" | grep -v 'dhcp'$r `
    echo "$currentkeys" > /root/.ssh/authorized_keys
   done 
  else
   echo "$hosts" | while read r;
   do
    echo r=$r
    currenthosts=`echo  "$currenthosts" | grep -v $r `
    echo "$currenthosts" > /root/.ssh/known_hosts
    echo currenthosts="$currenthosts"
   done 
  fi
  echo '##########################'
  currentkeys=`cat /root/.ssh/authorized_keys`
  currenthosts=`cat /root/.ssh/known_hosts`
  echo currentkeys="$currentkeys"
  echo currenthosts="$currenthosts"
  echo hosts=$hosts
  echo nodes=$nodes
  echo '##########################'
#  echo "$currentkeys" > /root/.ssh/authorized_keys
#  echo "$currenthosts" > /root/.ssh/known_hosts
  chmod 004 /root/.ssh/authorized_keys
  chmod 004 /root/.ssh/known_hosts
  echo $issender | grep sender 
  if [ $? -eq 0 ];
  then
   pport=` echo $partnerinfo | awk -F'/' '{print $3}'`
   allpartners=`./etcdgetlocal.py Partner --prefix | grep -v $clusterip`
   echo $allpartners | grep $pport
   if [ $? -ne 0 ];
   then
    sshd=`cat /etc/ssh/sshd_config | grep -v $pport`
    echo -e "$sshd" > /etc/ssh/sshd_config
    systemctl restart sshd
   fi
  fi 
  ./etcddel.py $leaderip Partner $Partner 
  crontab -l | grep -v $Partner > $cronthis
  crontab $cronthis
  echo $issync | grep yes 
  if [ $? -ne 0 ];
  then
    stamp=`date +%s`;
    /pace/etcdput.py $leaderip sync/replipart/`basename "$0"`_${Parnter}_yes_$userreq/request/$myhost replipart_$stamp
    /pace/etcdput.py $leaderip sync/replipart/`basename "$0"`_${Parnter}_yes_$userreq/request/$myhost replipart_$stamp
  fi
  /TopStor/logmsg.py Partner1004 info $userreq $Partner
fi
