#!/bin/sh
runningpools='/pacedata/pools/runningpools'
echo $@ > /root/sambaconnect
hostnam=`cat /TopStordata/hostname`
poolis=`cat $runningpools | grep "$hostnam" | awk '{print $2}'`
mkdir -p /$poolis/$1
usermod $1 -m &>/dev/null
chmod -R 700 /$poolis/$1
chown $1 /$poolis/$1
