#!/bin/sh
echo $@ weekly > /root/tmp
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
cronthis='/TopStordata/cronthis.txt'
rm -rf $cronthis 2>/dev/null
stime=`echo $@ | awk '{print $3}'`;
ampm=`echo $@ | awk '{print $4}'`;
hr=`echo $stime | awk -F':' '{print $1}'`;
echo $ampm | grep PM
if [ $? -eq 0 ];
then
 hr=$((hr+12))
fi
min=`echo $stime | awk -F':' '{print $2}'`;
every=`echo $@ | awk '{print $5}'` ;
k=0; keep=`echo $@ | awk '{print $6}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
pDG=` echo $@ | awk '{print $1}'`; 
FileS=` echo $@ | awk '{print $2}'`;
receiver=` echo $@ | awk '{print $7}'`;
userreq=` echo $@ | awk '{print $8}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG`;
myhost=`hostname -s`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
   /TopStor/logmsg.py Snap1031 info $userreq Weekly.$hr.$min.$every.$keep $DG/$FileS
leader=`./etcdget.py leader --prefix`
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
 stamp=`date +%s`;
 local=''
 myip=''
else
 stamp=` echo $@ | awk '{print $7}'`;
 local='local'
 myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
fi
crontab -l > $cronthis
echo $min  $hr "*" "*" $every  /TopStor/Snapshotnowhost $DG/$FileS Weekly.$keep.$hr.$min.$every $stamp $receiver 2>txt/SnapshotnowSystem.txt >> $cronthis
crontab $cronthis
if [ $? -ne  0 ]; then
   /TopStor/logmsg.py Snap1032 error $userreq  $DG/$FileS
else 
  /TopStor/logmsg.py Snap1033 info $userreq Weekly.$keep.$hr.$min.$every.$stamp $DG/$FileS
  /pace/etcdput${local}.py $myip Snapperiod/Weekly/$DG/$FileS/$stamp  $min%$hr%*%*%$every%/TopStor/Snapshotnowhost%$DG/$FileS%Weekly.$keep.$hr.$min.$every%$stamp/$receiver
  if [ -z $local ];
  then
   /pace/etcdput.py sync/Snapperiod/`basename "$0"`_$@ $stamp/request/$myhost Snapperiod_$stamp
   /pace/etcdput.py sync/Snapperiod/`basename "$0"`_$@ $stamp/request Snapperiod_$stamp
  fi
fi;
 /pace/putzpool.py 
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq 
