#!/usr/local/bin/zsh
export ETCDCTL_API=3
echo $@ > /root/tmp
cd /TopStor
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
DG=` echo $@ | awk '{print $1}'`;
vol=` echo $@ | awk '{print $2}'`;
pDG=$DG;
snapdel=` echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
sshost=`hostname -s`
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Snap1022 info $userreq $vol/$snapdel
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 /sbin/zfs destroy $DG/$vol@$snapdel
 if [ $? -ne  0 ]; then
   /TopStor/logmsg.py Snap1023 error $userreq $vol/$snapdel
 else 
   /TopStor/logmsg.py Snap1025 info $userreq $vol/$snapdel
 fi;
fi
   /pace/putzpool.py &
