#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
cronthis='/TopStordata/cronthis.txt'
rm -rf $cronthis
every=0; ev=`echo $@ | awk '{print $3}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $4}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $1}'`; 
FileS=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $5}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
DG=` echo $pDG`;
myhost=`hostname -s`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Snap1034 info $userreq $FileS
stamp=`date +%s`;
crontab -l > $cronthis
echo "*"/$every "*" "*" "*" "*"  /TopStor/Snapshotnowhost $DG/$FileS Minutely.$keep.$every.na.na $stamp 2> txt/err.txt >> $cronthis
crontab $cronthis
if [ $? -ne 0  ]; then
  /TopStor/logmsg.py Snap1035 error $userreq $FileS
else 
  /TopStor/logmsg.py Snap1036 info $userreq $FileS
  /pace/etcdput.py Snapperiod/$DG/$FileS/$stamp  */$every%*%*%*%*%/TopStor/Snapshotnowhost%$DG/$FileS%Minutely.$keep.$every.na.na%$stamp
 ETCDCTL_API=3 /TopStor/broadcast.py  PeriodManage /TopStor/etctocronlocal.sh 
fi;
 /pace/putzpool.py
fi
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
