#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/currentinfo2.log2';
glog='/var/www/html/des20/Data/TopStor.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
pDG=`echo $@ | awk '{print $1}'`;
DG=`echo $@ | awk -F/ '{print $1}'`;
receiver='NoReceiver'
echo $? | grep NoReceiver
if [ $? -ne -0 ];
then
receiver=` echo $@ | awk -F'/' '{print $NF'}`
fi
echo $pDG
myhost=`hostname -s`
pp=`/sbin/zpool list | grep $DG`
echo pp=$pp
echo $pp | grep $DG
if [ $? -ne 0 ]; 
then
 echo host not owner
 /TopStor/logqueue.py `basename "$0"` stop_cancel system 
else
 /TopStor/logqueue.py `basename "$0"` running system 
 res=`./Snapshotnow $@`
 echo result is =$res
 receiver='NoReceiver'
 echo $@ | grep NoReceiver
 if [ $? -ne -0 ];
 then
  receiver=` echo $@ | awk -F'/' '{print $NF'}`
  snapshot=`echo $res | grep '_newsnap' | awk -F'_newsnap' '{print $2}' `
  params=`/TopStor/repliparams.py $snapshot`
  echo $receiver $snapshot > /root/snpshottemp
  echo snapshot=$snapshot  receiver=$receiver
  zfs set partner:receiver=$receiver $snapshot
 fi
#  /TopStor/logmsg.py Snap1045 error $userreq $newsnap 
/TopStor/logqueue.py `basename "$0"` stop system 
fi
