#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/currentinfo2.log2';
glog='/var/www/html/des20/Data/TopStor.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
pDG=`echo $@ | awk '{print $1}'`;
DG=`echo $@ | awk -F/ '{print $1}'`;
echo $pDG
myhost=`hostname -s`
/TopStor/queuethis.sh `basename "$0"` running system &
pp=`/sbin/zpool list `
echo $pp | grep $DG
if [ $? -ne 0 ]; then echo host not owner; exit; fi
  res=`./Snapshotnow $@`
#  /TopStor/logmsg.py Snap1045 error $userreq $newsnap 
/pace/putzpool.py
/TopStor/queuethis.sh `basename "$0"` finished system &
