#!/usr/local/bin/zsh
cd /TopStor
web='/usr/local/www/apache24/data/des19/Data/statusglobal.log';
rm txt/err.txt;
rm txt/cronthis.txt;
whoami > tmp 
echo operands=$@  >> tmp
oper=`echo $@ | awk '{print $8}'`;
echo search=$oper >> tmp
crontab -l > txt/cronthis.txt;
cat txt/cronthis.txt | grep -v "$oper" >> tmp;
cat txt/cronthis.txt | grep -v "$oper" > txt/cronthis.txt;
echo $@ >> txt/cronthis.txt;
crontab txt/cronthis.txt 2>txt/err.txt;
err=`wc -c  txt/err.txt | awk '{print $1}'`;
if [[ $err >  4  ]]; then
	cat txt/err.txt > $web;
else 
 echo DONE...Snapshot hourly.$day.$hr.$min is added > $web; 
fi;
./GetPoolHourlylist;
./GetPoolMinutelylist;
./GetPoolWeeklylist;
