#!/bin/sh
echo $@ > /root/tmp
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
cronthis='/TopStordata/cronthis.txt'
glog='/var/www/html/des20/Data/TopStor.log';
rm -rf $cronthis 2>/dev/null
min=`echo $@ | awk '{print $3}'` ;
every=0; ev=`echo $@ | awk '{print $4}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $5}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $1}'`; 
FileS=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $6}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=$pDG; 
myhost=`hostname -s`
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Snap1037 info $userreq  
stamp=`date +%s`;
crontab -l > $cronthis
echo $min  "*"/$every "*" "*" "*"  /TopStor/Snapshotnowhost $DG/$FileS hourly.$keep.$min.$every.na $stamp 2> txt/err.txt >> $cronthis
crontab $cronthis 2>> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
  /TopStor/logmsg.py Snap1038 error $userreq $DG/$FileS 
else 
  /TopStor/logmsg.py Snap1039 info $userreq  hourly.$keep.$min.$every.$stamp $DG/$FileS
  /pace/etcdput.py Snapperiod/Hourly/$DG/$FileS/$stamp  $min%*/$every%*%*%*%/TopStor/Snapshotnowhost%$DG/$FileS%hourly.$keep.$min.$every.na%$stamp
 ETCDCTL_API=3 /TopStor/broadcast.py  PeriodManage /TopStor/etctocronlocal.sh 
fi
 /pace/putzpool.py 
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq 
