#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
glog='/var/www/html/des20/Data/TopStor.log';
echo Snap1012: > $web;
name=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Snap1013:$hostnam/$DG/$FileS > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_Snapshot:'$hostnam/$DG/$FileS@$name;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1026@@@$hostnam/$DG/$FileS@name`;
echo Snap1026@$datenow@$timenow@$hostnam/$DG/$FileS@$name > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Snap1026@@@$hostnam/$DG/$FileS@$name $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
/TopStor/SnapshotnowOnce $sshost $hostnam $DG/$FileS $name. > $txtres
if [ $? -ne 0  ]]; then
	echo Snap1014:$hostnam/$DG/$FileS > $web;
	cat $txtres > $web;
	logdata='Failed_Creating_Snapshot:'$hostnam/$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata Snap1028@@@$hostnam/$DG/$FileS@$name`;
echo Snap1028@$datenow@$timenow@$hostnam/$DG/$FileS@$name > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Snap1028@@@$hostnam/$DG/$FileS@$name $dtn>> $glog
else 
 	echo Snap1015:$hostnam/$DG/$FileS$name.$now1 > $web; 
	logdata='Success_Creating_Snapshot:'$hostnam/$DG/$FileS@$name;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1030@@@$hostnam/$DG/$FileS@$name`;
echo Snap1030@$datenow@$timenow@$hostnam/$DG/$FileS@$name > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Snap1030@@@$hostnam/$DG/$FileS@$name $dtn>> $glog
ETCDCTL_API=3 /pace/putzpool.py
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi

