#!/usr/local/bin/zsh
echo $@> /root/tmp
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
glog='/var/www/html/des20/Data/TopStor.log';
echo Snap1012: > $web;
name=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Snap1026 info $userreq $hostnam/$DG/$FileS@$name 
/TopStor/SnapshotnowOnce $sshost $hostnam $DG/$FileS $name. > $txtres
if [ $? -ne 0  ]]; then
  /TopStor/logmsg.py Snap1028 error $userreq $hostnam/$DG/$FileS@$name 
else 
  /TopStor/logmsg.py Snap1030 info $userreq $hostnam/$DG/$FileS@$name 
 /pace/etcddel.py md --prefix
fi;
fi

