#!/usr/local/bin/zsh
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
cronthis='/TopStordata/cronthis.txt'
rm -rf $cronthis 2>/dev/null
stime=`echo $@ | awk '{print $1}'`;
hr=`echo $stime | awk -F: '{print $1}'`;
min=`echo $stime | awk -F: '{print $2}'`;
every=`echo $@ | awk '{print $2}'` ;
k=0; keep=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1; fi
pDG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=` echo $pDG | awk -F_ '{print $2}'`;
hostnam=` echo $pDG | awk -F_ '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
   /TopStor/logmsg.py Snap1031 info $userreq Weekly.$hr.$min.$every.$keep/$DG/$FileS
stamp=`date +%s`;
crontab -l > $cronthis
echo $min  $hr "*" "*" $every  /TopStor/Snapshotnowhost $hostnam/$DG/$FileS Weekly.$keep.$hr.$min.$every $stamp 2>txt/SnapshotnowSystem.txt >> $cronthis
crontab $cronthis 2>> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
   /TopStor/logmsg.py Snap1032 error $userreq Weekly.$hr.$min.$every.$keep/$DG/$FileS
else 
  /TopStor/logmsg.py Snap1033 info $userreq Weekly.$hr.$min.$every.$keep/$DG/$FileS

fi;
./GetPoolperiodlist 
 /pace/putzpool.py 
fi
