#!/bin/sh
echo $@ > /root/createhourlyperiods
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
cronthis='/TopStordata/cronthis.txt'
glog='/var/www/html/des20/Data/TopStor.log';
rm -rf $cronthis 2>/dev/null
min=`echo $@ | awk '{print $3}'` ;
every=0; ev=`echo $@ | awk '{print $4}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $5}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $1}'`; 
FileS=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=$pDG; 
myhost=`hostname -s`
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
echo contrun $contrun
if [[ $contrun == 'true' ]]
then
stamp=`date +%s`;
crontab -l > $cronthis
echo $min  "*"/$every "*" "*" "*"  /TopStor/Snapshotnowhosttrend $DG/$FileS Trend $stamp  >> $cronthis
crontab $cronthis 2>> $txtres
/pace/etcdput.py sizevol/$DG/$FileS $stamp-0 
/pace/broadcasttolocal.py sizevol/$DG/$FileS $stamp-0 
fi
