#!/bin/sh

myhost=` ./etcdgetlocal.py clusternode`
leaderip=` ./etcdgetlocal.py leaderip`
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/Snapshotperiodcreate
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
cronthis='/TopStordata/cronthis.txt'
rm -rf $cronthis
every=0; ev=`echo $@ | awk '{print $3}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $4}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $1}'`; 
FileS=` echo $@ | awk '{print $2}'`;
receiver=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
DG=` echo $pDG`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Snap1034 info $userreq $FileS
leader=`./etcdgetlocal.py leader --prefix`
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
 stamp=`date +%s`;
 local=''
 myip=$leaderip
else
 stamp=` echo $@ | awk '{print $7}'`;
 local='local'
 myip=''
fi
crontab -l > $cronthis
echo hihihihihihihihi
echo "*"/$every "*" "*" "*" "*"  /TopStor/Snapshotnowhost $DG/$FileS Minutely.$keep.$every.na.na $stamp $receiver 2> txt/err.txt >> $cronthis
crontab $cronthis
if [ $? -ne 0  ]; then
  /TopStor/logmsg.py Snap1035 error $userreq $FileS
else 
  /TopStor/logmsg.py Snap1036 info $userreq $Minutely.$keep.$every.na.na.$stamp $DG/$FileS
  echo /pace/etcdput${local}.py $myip Snapperiod/Minutely/$DG/$FileS/$stamp/$receiver  */$every%*%*%*%*%/TopStor/Snapshotnowhost%$DG/$FileS%Minutely.$keep.$every.na.na%$stamp/$receiver
  /pace/etcdput${local}.py $myip Snapperiod/Minutely/$DG/$FileS/$stamp/$receiver  */$every%*%*%*%*%/TopStor/Snapshotnowhost%$DG/$FileS%Minutely.$keep.$every.na.na%$stamp/$receiver
  if [ -z $local ];
  then
   /pace/etcdput.py $leaderip sync/Snapperiod/____/request/$myhost Snapperiod_$stamp
   /pace/etcdput.py $leaderip sync/Snapperiod/____/request Snapperiod_$stamp
  fi
fi;
 /pace/putzpool.py
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq 
