#!/usr/local/bin/zsh
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
cronthis='/TopStordata/cronthis.txt'
glog='/var/www/html/des20/Data/TopStor.log';
rm -rf $cronthis 2>/dev/null
min=`echo $@ | awk '{print $1}'` ;
every=0; ev=`echo $@ | awk '{print $2}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=` echo $pDG | awk -F_ '{print $2}'`; 
hostnam=` echo $pDG | awk -F_ '{print $1}'`; 
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
echo Snap1009: > $web;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Creating_HourlyPeriod:'$hostnam/$DG/$FileS;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1037@@@.`;
echo Snap1037@$datenow@$timenow@. > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Snap1037@@@. $dtn>> $glog

oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
stamp=`date +%s`;
crontab -l > $cronthis
echo $min  "*"/$every "*" "*" "*"  /TopStor/Snapshotnowhost $hostnam/$DG/$FileS hourly.$keep.$min.$every.na $stamp 2> txt/err.txt >> $cronthis
crontab $cronthis 2>> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
	echo Snap1010: > $web;
	cat $txtres > ${web}internal;
	logdata='Failed_Creating_HourlyPeriod:'$hostnam/$DG/$FileS;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata Snap1038@@@.`;
echo Snap1038@$datenow@$timenow@. > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Snap1038@@@. $dtn>> $glog
else 
 	echo Snap1011:hourly.$min.$every.$keep > $web; 
	logdata='Success_Creating_HourlyPeriod:'$hostnam/$DG/$FileS;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1039@@@hourly.$min.$every.$keep/$hostnam/$DG/$FileS`;
echo Snap1039@$datenow@$timenow@hourly.$min.$every.$keep/$hostnam/$DG/$FileS > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Snap1039@@@hourly.$min.$every.$keep/$hostnam/$DG/$FileS $dtn>> $glog
fi
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolperiodlist
ETCDCTL_API=3 /pace/etcddel.py run/$hostnam --prefix 
ETCDCTL_API=3 /pace/putzpool.py
fi
