#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
cronthis='/TopStordata/cronthis.txt'
rm -rf $cronthis
every=0; ev=`echo $@ | awk '{print $1}'`; every=$(($every+$ev)) ; if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $2}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $3}'`; 
FileS=` echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=` echo $pDG | awk -F_ '{print $2}'`;
hostnam=` echo $pDG | awk -F_ '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
/TopStor/logmsg.sh Snap1034 info $userreq $FileS
stamp=`date +%s`;
crontab -l > $cronthis
echo "*"/$every "*" "*" "*" "*"  /TopStor/Snapshotnowhost $hostnam/$DG/$FileS Minutely.$keep.$every.na.na $stamp 2> txt/err.txt >> $cronthis
crontab $cronthis 2>> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
 /TopStor/logmsg.sh Snap1035 error $userreq $FileS
else 
 /TopStor/logmsg.sh Snap1036 info $userreq $FileS
fi;
./GetPoolperiodlist
ETCDCTL_API=3 /pace/putzpool.py
fi
