#!/usr/local/bin/zsh
cd /TopStor
web='/var/www/html/des20/Data/Snapsstatus.log'
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
periodel=` echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $2}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
logdata='Deleting_Period:'$periodel;
logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Snap1043@@@$periodel`;
echo Snap1043@$datenow@$timenow@$periodel > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Snap1043@@@$periodel $dtn>> $glog
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
echo Snap1003:$periodel > $web
/usr/bin/crontab -l | grep -v "$periodel" | /usr/bin/crontab -  2> $txtres
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  $txtres | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
        echo Snap1004:$periodel > $web;
        cat $txtres > ${web}internal;
        logdata='Failed_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg error user $userreq data $logdata code Snap1044@@@$periodel`;
echo Snap1044@$datenow@$timenow@$periodel > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow error $userreq Snap1044@@@$periodel $dtn>> $glog
else
	 echo Snap1005:$periodel > $web;
        logdata='success_Deleting_Period:'$periodel;
	logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata Snap1045@@@$periodel`;
echo Snap1045@$datenow@$timenow@$periodel > ${logging}2
dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
echo $datenow $timenow info $userreq Snap1045@@@$periodel $dtn>> $glog
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
./GetPoolperiodlist
fi
