#!/bin/sh
export ETCDCTL_API=3
echo $@ >/root/tmp
cd /TopStor
web='/var/www/html/des20/Data/currentinfo2.log2';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
stamp=`date +%s`;
vol=`echo $@ | awk '{print $1}'`;
size=`zfs list -H $vol -o used`
./addtrend.py $vol $size $stamp
