#!/usr/local/bin/zsh
echo $@ > /root/tmp
cd /TopStor
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
DG=` echo $@ | awk '{print $1}'`;
pDG=` echo $DG | awk -F'_' '{print $2}'`;
snapdel=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
hostnam=` echo $DG | awk -F'_' '{print $1}'`;
sshost=$hostnam
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 ETCDCTL_API=3 /TopStor/logmsg.py Snap1022 info $userreq $hostnam/$snapdel
 /sbin/zfs destroy $snapdel 2> $txtres
 err=`wc -c  $txtres | awk '{print $1}'`;
 datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 if [[ $err -ge  4  ]]; then
  ETCDCTL_API=3 /TopStor/logmsg.py Snap1023 error $userreq $hostnam/$snapdel
 else 
  ETCDCTL_API=3 /TopStor/logmsg.py Snap1025 info $userreq $hostnam/$snapdel
 fi;
fi
  echo $hostnam
  ETCDCTL_API=3 /pace/etcddel.py md --prefix
