#!/usr/local/bin/zsh
cd /TopStor/
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
pDG=` echo $@ | awk '{print $1}'`;
snaprol=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm  $txtres 2>/dev/null
hostnam=` echo $pDG | awk -F_ '{print $1}'`;
sshost=` echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
/TopStor/logmsg.st Snap1040 info $userreq $snaprol
/sbin/zfs rollback -r  $snaprol  2> $txtres;
err=`wc -c  $txtres | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
 /TopStor/logmsg.st Snap1041 error $userreq $snaprol
else 
 /TopStor/logmsg.st Snap1042 info $userreq $snaprol
fi;
oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
fi
