#!/usr/bin/sh
echo $@> /root/snapshotonce
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
runningpools='/pacedata/pools/runningpools'
glog='/var/www/html/des20/Data/TopStor.log';
echo Snap1012: > $web;
name=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
FileS=` echo $@ | awk '{print $3}'`;
receiver=` echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $NF}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Snap1026 info $userreq $FileS/$name 
echo /TopStor/SnapshotnowOnce $pDG $FileS $name 
/TopStor/SnapshotnowOnce $pDG $FileS $name $receiver > $txtres
if [ $? -ne 0  ]; then
  /TopStor/logmsg.py Snap1028 error $userreq $FileS/$name 
else 
  /TopStor/logmsg.py Snap1030 info $userreq $FileS/$name 
 /pace/putzpool.py & 
fi;
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq 
