#!/bin/sh
echo $@ > /root/createhourlyperiods
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
cronthis='/TopStordata/cronthis.txt'
glog='/var/www/html/des20/Data/TopStor.log';
rm -rf $cronthis 2>/dev/null
min=`echo $@ | awk '{print $3}'` ;
every=0; ev=`echo $@ | awk '{print $4}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $5}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $1}'`; 
FileS=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=$pDG; 
myhost=`hostname -s`
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
echo contrun $contrun
if [[ $contrun == 'true' ]]
then
leader=`./etcdget.py leader --prefix`
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
 stamp=`date +%s`;
 local=''
 myip=''
else
 stamp=` echo $@ | awk '{print $7}'`;
 local='local'
 myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
fi


crontab -l > $cronthis
echo $min "*"/$every "*" "*" "*"  /TopStor/Snapshotnowhosttrend $DG/$FileS Trend $stamp  >> $cronthis
crontab $cronthis 2>> $txtres
/pace/etcdput${local}.py $myip sizevol/$DG/$FileS $stamp-0 
if [ -z $local ];
then
 #params=`echo $@ | sed 's/ /\_/g'`
 #/pace/etcdput.py sync/Snapperiod/`basename "$0"`_$@_$stamp/request/$myhost Snapperiod_$stamp
 /pace/etcdput.py sync/Snapperiod/______/request/$myhost Snapperiod_$stamp
 /pace/etcdput.py sync/Snapperiod/______/request Snapperiod_$stamp
 #/pace/etcdput.py sync/Snapperiod/`basename "$0"`_$@_$stamp/request Snapperiod_$stamp
fi
fi
