#!/bin/sh
export ETCDCTL_API=3
echo $@ > /root/tmp
cd /TopStor/
pDG=` echo $@ | awk '{print $1}'`;
vol=` echo $@ | awk '{print $2}'`;
snaprol=` echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 docker exec etcdclient /TopStor/logmsg.py Snap1040 info $userreq $vol/$snaprol
/sbin/zfs rollback -r  $pDG/$vol@$snaprol  
if [ $? -ne  0  ]; then
  docker exec etcdclient /TopStor/logmsg.py Snap1041 error $userreq $vol/$snaprol
else 
  docker exec etcdclient /TopStor/logmsg.py Snap1042 info $userreq $vol/$snaprol
fi;
fi
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
/pace/putzpool.py 
