#!/usr/local/bin/zsh
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Snapsstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
cronthis='/TopStordata/cronthis.txt'
glog='/var/www/html/des20/Data/TopStor.log';
rm -rf $cronthis 2>/dev/null
min=`echo $@ | awk '{print $1}'` ;
every=0; ev=`echo $@ | awk '{print $2}'`; every=$(($every+$ev)); if (($every < 1)); then every=1; fi
keep=0; k=`echo $@ | awk '{print $3}'`; keep=$(($keep+$k)); if (($keep < 1)); then keep=1 ; fi
pDG=` echo $@ | awk '{print $4}'`; 
FileS=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
DG=` echo $pDG | awk -F_ '{print $2}'`; 
hostnam=` echo $pDG | awk -F_ '{print $1}'`; 
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Snap1037 info $userreq  
stamp=`date +%s`;
crontab -l > $cronthis
echo $min  "*"/$every "*" "*" "*"  /TopStor/Snapshotnowhost $hostnam/$DG/$FileS hourly.$keep.$min.$every.na $stamp 2> txt/err.txt >> $cronthis
crontab $cronthis 2>> $txtres
err=`wc -c  $txtres | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
if [[ $err -ge  4  ]]; then
  /TopStor/logmsg.py Snap1038 error $userreq  
else 
  /TopStor/logmsg.py Snap1039 info $userreq  hourly.$min.$every.$keep/$hostnam/$DG/$FileS
fi
./GetPoolperiodlist
 /pace/putzpool.py 
fi
