#!/bin/sh

. /etc/rc.subr

name="SSp"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
rcvar=SSp_enable
command="/TopStor/ssperformance.sh"
command_interpreter="/usr/local/bin/zsh"
load_rc_config $name
: ${SSp_enable:=yes}
: ${SSp_msg="SSp started successfuly."}
SSp_start()
{
	echo "$SSp_msg"
	/TopStor/ssperformance.sh &
}
SSp_stop()
{
	echo " SSp is stopped thanking God"
	pkill -HUP -f ssperf 
	touch /TopStor/txt/flag
}

run_rc_command "$1"
