#!/bin/sh
cd /TopStor
echo $@ > /root/groupdel
export ETCDCTL_API=3
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Unlin1104 info $userreq $username
userdel -f  $username 
rm  key/${username}fixed
sleep 2
cat /etc/passwd |  grep $username
if [ $? -eq 0 ]; then
  /TopStor/logmsg.py Unlin1g1001 error $userreq $myhost
else
  #/TopStor/broadcast.py GroupDel /TopStor/pump.sh UnixDelGroup_sync -d$myhost $username $userreq
 echo usename=$username
 groupdel $username 
 ETCDCTL_API=3 /pace/etcdget.py usersigroup $username 
 pool=`ETCDCTL_API=3 /pace/etcdget.py usersigroup/$username | awk -F'/' '{print $2}'`
 echo Home=$pool
 echo $pool | grep pdhcp
 if [ $? -eq 0 ];
 then
 vol=`ETCDCTL_API=3 /pace/etcdget.py usersigroup/$username | awk -F'/' '{print $3}'`
 echo vol=$vol $userreq
# ./VolumeDeleteHome.py $pool $vol $userreq
 fi
 /pace/etcddel.py usersigroup $username
 /TopStor/logmsg.py Unlin1110 info $userreq $username
fi;
fi
./etcdput.py sync/group/$myhost `date +%s%N`
./broadcasttolocal.py sync/group/$myhost `date +%s%N`
./etcdput.py modified/group/$username $myhost 
./broadcasttolocal.py modified/group/$username $myhost 
/TopStor/logqueue.py `basename "$0"` stop $userreq 
