#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
myhost=`echo $@ | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
userreq=`echo $@ | awk '{print $3}'`;
echo Everyone | grep $username
if [ $? -eq 0 ];
then
 exit
fi


privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  #/TopStor/logmsg.py Unlin11044 info $userreq $username
#rm -rf /home/$username &>/dev/null
userdel -f  $username 
groupdel $username 
fi
