#!/bin/sh
echo $@ > /root/unixadduser
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
homePool=`echo $@ | awk '{print $2}'`;
usergroups=`echo $@ | awk  '{print $3}'`;
grps=`echo $grpusers | sed 's/groups//g' | sed 's/\,/ /g'`
userpass=`echo $@ | awk '{print $4}'`;
host=`echo $@ | awk '{print $5}'`;
size=`echo $@ | awk '{print $6}'`;
userreq=`echo $@  | awk '{print $7}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
myhost=`hostname -s`
echo Unlin1017:$username > $web;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unlin1018 info $userreq $username
 /pace/etcdget.py volumes --prefix | grep -w $username
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021uv warning $userreq $username
  exit
 fi
 cat /etc/passwd | grep $username
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021uu warning $userreq $username
  exit
 fi
 pas=`echo $userpass | openssl enc -e -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`
 #useradd -c"TopStor"$pas -b /p$myhost -m -p $userpass -s /usr/sbin/nologin $username 2> $txtres
 echo $homePool | grep 'NoHome'
 if [ $? -ne 0 ];
 then
  /TopStor/VolumeCreateHome.py $homePool $username $size $userreq $host
  echo /TopStor/VolumeCreateHome.py $homePool $username $size $userreq $host > /root/tmphomepool
  /pace/etcdput.py home/$homePool Active
# homedir=`ETCDCTL_API=3 /pace/etcdget.py homedir/active` 
  homedir=$homePool
  homebase='-b /'$homedir' -M'  
  /TopStor/logmsg.py Unlin1024 info  $userreq $username $homedir
 else
  homebase='-b /NoHome -M'
  /TopStor/logmsg.py Unlin1023 warning $userreq $username
 fi
 groupdel $username
 useradd -c"TopStor"$pas $homebase -p $userpass -s /usr/sbin/nologin $username 
 echo useradd \-c"TopStor"$pas $homebase \-p $userpass \-s /usr/sbin/nologin $username
 echo $homedir | grep "\-1"
 if [ $? -ne 0 ];
 then
  #rm -rf /home/$username
  #ln -s /$homedir/$username /home/$username
  chmod o-rwx /$homedir/$username -R
 fi
# /bin/smbpasswd -e $username
 /bin/smbpasswd -x $username
 ( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username 2>> $txtres
 #mkdir -p /Data/Common/$username;
 #chown $username /Data/Common/$username;
 userline=`cat /etc/passwd | grep $username`
 if [ $? -ne  0  ]; then
   /TopStor/logmsg.py Unlin1020 error $userreq $username
 else 
 # openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
  echo $userpass > key/${username}fixed
  gpg -u "QuickStor" -r"QuickStor" key/${username}fixed
  chmod 400 key/${username}fixed.gpg;
  rm -rf key/${username}fixed
  userid=`echo $userline | awk -F':' '{print $3}'`
  usergd=`echo $userline | awk -F':' '{print $4}'`
  userhome=`echo $userline | awk -F':' '{print $6}'`
  userhash=`echo $userline | awk -F':' '{print $5}' | awk -F'TopStor' '{print $2}'`
  yes | cp /etc/{passwd,group,shadow} /opt/passwds
  echo $grps | while read l;
  do
   usermod  -a -G $l $username
   cusersall=`/pace/etcdget.py usersigroup/$l`
   cusers=`echo $usersall | awk -F'/' '{print $3}'`
   cusersleft=`echo $usersall | cut -d/ -f1-2`
   cusersright=`echo $usersall | cut -d/ -f3-`
   newusers=${cusers}','$username
   /pace/etcdput.py usersigroup/$l $cusersright/$newusers/$cusersleft 
  done
  /TopStor/etcdput.py 'usersinfo/'$username $userid':'$usergd':'$userhome'/'$size'/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no'
  /TopStor/etcdput.py 'usershash/'$username $userhash
  /TopStor/broadcast.py UserAdd /TopStor/pump.sh UnixAddUser_sync -d$myhost $username $userhash $userid $usergd $userhome
  /TopStor/logmsg.py Unlin1022 info $userreq $username
 fi 
fi
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
