#!/bin/sh
cd /TopStor
echo $@ > /root/userdel
export ETCDCTL_API=3
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Unlin1004 info $userreq $username
/bin/smbpasswd -x $username;
#rm -rf /home/$username &>/dev/null
userdel -f  $username 
rm  key/${username}fixed
datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
cat /etc/passwd |  grep $username
if [ $? -eq 0 ]; then
  /TopStor/logmsg.py Unlin11001 error $userreq $myhost
else
  /TopStor/broadcast.py UserDel /TopStor/pump.sh UnixDelUser_sync -d$myhost $username $userreq
 echo usename=$username
 ETCDCTL_API=3 /pace/etcdget.py usersinfo $username 
 pool=`ETCDCTL_API=3 /pace/etcdget.py usersinfo/$username | awk -F'/' '{print $2}'`
 echo Home=$pool
 echo $pool | grep pdhcp
 if [ $? -eq 0 ];
 then
 vol=`ETCDCTL_API=3 /pace/etcdget.py usersinfo/$username | awk -F'/' '{print $3}'`
 echo vol=$vol $userreq
# ./VolumeDeleteHome.py $pool $vol $userreq
 fi
 /pace/etcddel.py users $username
 /TopStor/logmsg.py Unlin1010 info $userreq $username
fi;
fi
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
