#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
myhost=`echo $@ | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
userreq=`echo $@ | awk '{print $3}'`;
echo NoUser | grep $username
if [ $? -eq 0 ];
then
 exit
fi

privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 # /TopStor/logmsg.py Unlin10044 info $userreq $username
 currentcifs=`docker ps | awk '{print $NF}' | grep -e 'CIFS|HOME'`
 echo $currentcifs | grep -e 'CIFS|HOME'
 if [ $? -eq 0 ];
 then
  echo "$currentcifs" | while read y; do docker exec $y /bin/smbpasswd -x $username;  done; 
 fi
/bin/smbpasswd -x $username;
#rm -rf /home/$username &>/dev/null
userdel -rf  $username 
rm  key/${username}fixed
datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
#cat /etc/passwd |  grep $username
#if [ $? -eq 0 ]; then
#  /TopStor/logmsg.py Unlin110011 error $userreq $myhost
#else
#  /TopStor/logmsg.py Unlin10100 info $userreq $username
#fi;
fi
