#!/bin/sh
cd /TopStor
echo $@ > /root/usersync
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
pas=`echo $@ | awk '{print $2}'`;
userid=`echo $@ | awk '{print $3}'`;
usergd=`echo $@ | awk '{print $4}'`;
userhome=`echo $@ | awk '{print $5}'`;
userpass=`echo $pas | openssl enc -d -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`;
userreq='system';
myhost=`hostname -s`
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
cat /etc/passwd | grep $username
if [ $? -eq 0 ];
then
 /TopStor/logmsg.py Unlin10211 warning $userreq $username
 /TopStor/UnixDelUserlocal $username system
fi
/TopStor/logmsg.py Unlin10188 info $userreq $username
groupdel $username
groupadd -g $usergd $username
rm -rf /home/$username 2>/dev/null
homebase='-b /'$userhome' -m'  
echo $userhome | grep NoHome
if [ $? -eq 0 ];
then
 homebase='-b /NoHome -M'
fi
useradd -c"TopStor"$pas $homebase -g $usergd -u $userid -p $userpass -s /usr/sbin/nologin $username
echo useradd \-c"TopStor"$pas $homebase \-g $usergd \-u $userid \-p $userpass \-s /usr/sbin/nologin $username > /root/tmpuser
( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username 2>> $txtres
cat $txtres
 echo $userpass > key/${username}fixed
 gpg -u "QuickStor" -r"QuickStor" key/${username}fixed
 chmod 400 key/${username}fixed.gpg;
 rm -rf key/${username}fixed
 /pace/etcdsync.py $myip usersinfo/$username usersinfo/$username 
 /pace/etcdsync.py $myip usershash/$username usershash/$username 
 /TopStor/logmsg.py Unlin10222 info $userreq $username
fi
cd /pace
