#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/usersync
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
pas=`echo $@ | awk '{print $2}'`;
userid=`echo $@ | awk '{print $3}'`;
usergd=`echo $@ | awk '{print $4}'`;
userhome=`echo $@ | awk '{print $5}'`;
userpass=`echo $pas | openssl enc -d -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`;
userreq='system';
myhost=`hostname -s`
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
cat /etc/passwd | grep $username
if [ $? -eq 0 ];
then
 /TopStor/logmsg.py Unlin10211 warning $userreq $username
 /TopStor/UnixDelUserlocal $username system
fi
 echo syncing usersync 
 /pace/etcdsync.py $myip usersinfo/$username usersinfo/$username 
# (>&2 echo iamhere $myip)
 /pace/etcdsync.py $myip usershash/$username usershash/$username 
 /TopStor/logmsg.py Unlin10222 info $userreq $username
fi
cd /pace
