#!/bin/sh
echo $@ > /root/unixchangegroup
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
groupname=`echo $@ | awk '{print $1}'`;
groupusers=`echo $@ | awk  '{print $2}' | sed 's/users//g' `
allusres=`echo $groupusers | sed 's/\,/ /g'`;
allusersel=`echo $allusers | wc -w`;
groupusersn=`echo $groupusers | wc -c `
if [ $groupusersn -le 2 ];
then
 groupusers='NoUser'
fi
userreq=`echo $@  | awk '{print $3}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
myhost=`hostname -s`
stableuser="na"
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unst1025 info $userreq $groupname
 echo $groupusers | grep NoUser
 if [ $? -ne 0 ];
 then
#### getting users need to removed
  originalgroup=`/pace/etcdget.py usersigroup/$groupname`
  originalusers=`echo $originalgroup | awk -F'/' '{print $3}'`
  memoryallusers=$originalusers
  oldusers=$originalusers','
  oldusersel=` echo ${oldusers} | sed 's/,/ /g' | wc -w`
  while [ $oldusersel -gt 0 ];
  do
   l=`echo $oldusers |  cut -d, -f 1`
   lsn=`echo $l | wc -c `
   oldusers=`echo $oldusers | sed 's/ /,/g' | cut -d, -f2-`
   oldusers=$oldusers','
   oldusersel=`echo ${oldusers} | sed 's/,/ /g' | wc -w`
   if [ $lsn -le 2 ];
   then
    continue
   fi
   echo $groupusers | grep -w $l
   if [ $? -ne 0 ];
   then
    gpasswd -d $l $groupname
    originalusers=`echo $originalusers| sed "s/$l//g" | sed 's/^,//g' | sed 's/,,/,/g' | sed 's/,$//g'` 
   else
    stableuser=$stableuser' '$l
   fi 
  done 
  echo originalusers=$originalusers
  sleep 3
  echo $originalusers | grep $memoryallusers 
  if [ $? -ne 0 ];
  then
   cusersleft=`echo $originalgroup | cut -d/ -f1-2`
   cusersright=`echo $originalgroup | cut -d/ -f4-`
   newusers=$originalusers
   newop=$cusersleft'/'$newusers'/'$cusersright
   groupres=`echo ${newop}`
   /pace/etcdput.py usersigroup/$groupname  $groupres 
  fi 
  usersall=`echo $groupusers`','
  usersl=` echo ${usersall} | sed 's/,/ /g' | wc -w`
  while [ $usersl  -gt 0 ];
  do
   l=`echo $usersall |  cut -d, -f 1`
   usersall=`echo $usersall | sed 's/ /,/g' | cut -d, -f2-`
   usersall=$usersall','
   usersl=`echo ${usersall} | sed 's/,/ /g' | wc -w`
   echo $stableuser | grep  -w $l
   if [ $? -eq 0 ];
   then
    continue
   fi
   usergroups=`id -Gn $l | sed 's/ /,/g' | sed "s/$l,//g" | sed "s/$groupname//g" | sed "s/Everyone//g" | sed "s/,,/,/g" | sed 's/,,,/,/g' | sed 's/,,,,/,/g' | sed 's/^,//g' | sed 's/,$//g' `
   usergroupsn=`echo $usergroups | wc -c`
   if [ $usergroupsn -le 2 ];
   then
    usergroups=$groupname
   else
    usergroups=$usergroups','$groupname
   fi 
   echo /TopStor/UnixChangeUser $l groups$usergroups $userreq 
   /TopStor/UnixChangeUser $l groups$usergroups $userreq 2&>/root/UnixChangeUser
  done 
 else
   /TopStor/UnixChangeUser NoUser groups$groupname $userreq 2&>/root/UnixChangeUser
 fi 
 /TopStor/broadcast.py GroupChange /TopStor/pump.sh UnixChangeGroup_sync -d$myhost $@ 
 /TopStor/logmsg.py Unsu1025 info $userreq $groupname
fi 
./etcdput.py sync/group/$myhost `date +%s%N`
./broadcasttolocal.py sync/group/$myhost `date +%s%N`
./broadcasttolocal.py modified/group/$groupname $myhost 
/TopStor/logqueue.py `basename "$0"` stop $userreq 
