#!/bin/sh
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
/bin/smbpasswd -d $username;
rm -rf /home/$username &>/dev/null
userdel -r  $username 2>/dev/null;
rm key/$username 2>/dev/null
fi
