#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Unlin10044 info $userreq $username
/bin/smbpasswd -d $username;
#rm -rf /home/$username &>/dev/null
userdel -rf  $username 
rm  key/${username}fixed
datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
cat /etc/passwd |  grep $username
if [ $? -eq 0 ]; then
  /TopStor/logmsg.py Unlin110011 error $userreq $myhost
else
  /TopStor/logmsg.py Unlin10100 info $userreq $username
fi;
fi
