#!/bin/sh
cd /TopStor
echo $@ > /root/usersync
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
pas=`echo $@ | awk '{print $2}'`;
userid=`echo $@ | awk '{print $3}'`;
usergd=`echo $@ | awk '{print $4}'`;
userhome=`echo $@ | awk '{print $5}'`;
userpass=`echo $pas | openssl enc -d -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`;
userreq='system';
myhost=`hostname -s`
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
groupadd -g $usergd $username
useradd -c"TopStor"$pas -d $userhome -M -g $usergd -u $userid -p $userpass -s /usr/sbin/nologin $username 2> $txtres
echo $userhome | grep NoHome
if [ $? -ne 0 ];
then
 rm -rf /home/$username
 ln -s /$userhome /home/$username
 chmod o-rwx /$userhome -R
fi
( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username 2>> $txtres
cat $txtres
 echo $userpass > key/${username}fixed
 gpg -u "QuickStor" -r"QuickStor" key/${username}fixed
 chmod 400 key/${username}fixed.gpg;
 rm -rf key/${username}fixed
fi
cd /pace
