#!/bin/sh
cd /TopStor
echo $@ > /root/userdel
export ETCDCTL_API=3

leaderip=`echo $@  | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
userreq=`echo $@ | awk '{print $3}'`;
echo NoUser | grep $username
if [ $? -eq 0 ];
then
 exit
fi
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then

	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
  docker exec etcdclient /TopStor/logmsg.py Unlin1004 info $userreq $username
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
	fi
 #echo "$currentcifs" | while read y; do docker exec $y /bin/smbpasswd -x $username;  done; 
 #/bin/smbpasswd -x $username;
 #rm -rf /home/$username &>/dev/null
 userdel -f  $username 
 datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
 cat /etc/passwd |  grep $username
 if [ $? -eq 0 ]; then
   docker exec etcdclient /TopStor/logmsg.py Unlin11001 error $userreq $myhost
 else
  #/TopStor/broadcast.py UserDel /TopStor/pump.sh UnixDelUser_sync -d$myhost $username $userreq
  echo usename=$username
  cgrps=`/pace/etcdget.py $etcd usersigroup $username`
  cgrpsl=${#cgrps}
  while [ $cgrpsl  -gt 4 ];
  do
   l=`echo "${cgrps[@]}" | tail -1 `
   cgrps=`echo "${cgrps[@]}" | sed '$d'`
   cgrpsl=${#cgrps}
   cgrp=`echo $l | sed "s/('usersigroup\///g" | awk -F"'" '{print $1}' `  
   usersall=`/pace/etcdget.py $etcd usersigroup/$cgrp`
   cusers=`echo $usersall | awk -F'/' '{print $3}'`
   cusersleft=`echo $usersall | cut -d/ -f1-2`
   cusersright=`echo $usersall | cut -d/ -f4-`
   newusers=`echo ${cusers} | sed "s/,$username//g" | sed "s/$username,//g"`
   resusers=${#newusers}
   if [ $resusers -le 2 ];
   then
    newusers='no'
   fi
   newop=$cusersleft'/'$newusers'/'$cusersright
   groupres=`echo ${newop} | sed "s/$username,//g" | sed "s/,$username//g" `
   echo to remove : $cgrp to be $groupres
   /pace/etcdput.py $etcd usersigroup/$cgrp $groupres 
  done
  pool=`ETCDCTL_API=3 /pace/etcdget.py $etcd usersinfo/$username | awk -F'/' '{print $2}'`
  echo Home=$pool
  echo $pool | grep pdhcp
  if [ $? -eq 0 ];
  then
  vol=`ETCDCTL_API=3 /pace/etcdget.py $etcd usersinfo/$username | awk -F'/' '{print $3}'`
  echo vol=$vol $userreq
 # ./VolumeDeleteHome.py $pool $vol $userreq
  fi
  /pace/etcddel.py $etcd users $username
  docker exec etcdclient /TopStor/logmsg.py Unlin1010 info $userreq $username
 fi;
fi
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
	stamp=`date +%s%N`
	/pace/etcdput.py $etcd sync/user/syncfn_oneusersync_Del_${username}/request/$myhost user_$stamp
	/pace/etcdput.py $etcd sync/user/syncfn_oneusersync_Del_${username}/request user_$stamp
fi
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
