#!/bin/sh
cd /TopStor/key;
export ETCDCTL_API=3
echo $@ > /root/UnixchkUser
web='/var/www/html/des20/Data/isuser.txt';
resulting="not found";
username=`echo $@ | awk '{print $1}'`;
userchk=`echo $@ | awk '{print $2}'`;
userpass=`echo $@ | awk '{print $3}'`;
rm -rf ${username}fixed
gpg --batch --passphrase YousefNadody ${username}fixed.gpg
pass1=`cat ${username}fixed`
echo $pass1 | grep -w $userpass
if [[ $? -eq 0 ]]; then
 resulting="ok";
 stamp=`date +%s`;
 /pace/etcdput.py logged/$username $stamp
 /pace/etcdput.py updlogged/$username $stamp
else
 oldstamp=`/pace/etcdget.py logged/$username`
 if [ $oldstamp -ne 1 ];
 then
  /pace/etcdput.py logged/$username 1 
 else
  /pace/etcdput.py logged/$username 0 
 fi
fi;
