#!/bin/sh
echo $@ > /root/unixchangeuser
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
usergroups=`echo $@ | awk  '{print $2}' | sed 's/groups//g' `;
userreq=`echo $@  | awk '{print $3}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
myhost=`hostname -s`
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
stablegrp=""
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unst1124 info $userreq $username
# cgrps=`id -Gn $username | sed "s/$username//g"` 
 usermod -G $usergroups $username
 cgrps=`/pace/etcdget.py usersigroup $username`
 cgrpsl=${#cgrps}
 while [ $cgrpsl  -gt 4 ];
 do
  l=`echo "${cgrps[@]}" | tail -1 `
  cgrps=`echo "${cgrps[@]}" | sed '$d'`
  cgrpsl=${#cgrps}
  cgrp=`echo $l | sed "s/('usersigroup\///g" | awk -F"'" '{print $1}' `  
  echo $usergroups | grep -w $cgrp  &>/dev/null
  if [ $? -ne 0 ];
  then
   usersall=`/pace/etcdget.py usersigroup/$cgrp`
   cusers=`echo $usersall | awk -F'/' '{print $3}'`
   cusersleft=`echo $usersall | cut -d/ -f1-2`
   cusersright=`echo $usersall | cut -d/ -f4-`
   newusers=`echo ${cusers} | sed "s/$username//g" | sed 's/,,/,/g'`
   resusers=${#newusers}
   if [ $resusers -le 2 ];
   then
    newusers='no'
   fi
   newop=$cusersleft'/'$newusers'/'$cusersright
   groupres=`echo ${newop} | sed "s/$username//g" | sed 's/,,/,/g' | sed 's/\/,/\//g' | sed 's/,\//\//g'`
   echo to remove : $cgrp to be $groupres
   /pace/etcdputlocal.py  $myip usersigroup/$cgrp $groupres 
  else
   stablegrp=${stablegrp}${cgrp}',';
   echo to keep : $cgrp
  fi
 done
 echo the stable=$stablegrp
 usergropus=$usergroups','
 grpsl=` echo ${usergroups} | sed 's/,/ /g' | wc -w`
 while [ $grpsl -gt 0 ]; 
 do
  l=`echo $usergroups |  cut -d, -f 1`
  usergroups=`echo $usergroups | sed 's/ /,/g' | cut -d, -f2-`
  usergroups=$usergroups','
  grpsl=` echo ${usergroups} | sed 's/,/ /g' | wc -w`
  echo l=$l
  echo usrgroups=$usergroups
  echo grpsl=$grpsl
  echo $stablegrp | grep -w $l >/dev/null
  if [ $? -ne 0 ];
  then
   usersall=`/pace/etcdget.py usersigroup/$l`
   cusers=`echo $usersall | awk -F'/' '{print $3}'`
   cusersleft=`echo $usersall | cut -d/ -f1-2`
   cusersright=`echo $usersall | cut -d/ -f4-`
   echo $cusers | grep -w no
   if [ $? -ne 0 ];
   then
    newusers=${cusers}','$username
    newop=$cusersleft'/'$newusers'/'$cusersright
    groupres=`echo ${newop}`
    echo appending $l to be $groupres
    /pace/etcdputlocal.py $myip usersigroup/$l $groupres 
   else 
    newusers=$username
    newop=$cusersleft'/'$newusers'/'$cusersright
    groupres=`echo ${newop}`
    echo adding $l to be $groupres
    /pace/etcdputlocal.py $myip usersigroup/$l $groupres 
   fi
  fi
 done
 /TopStor/logmsg.py Unsu1124 info $userreq $username
fi 
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
