#!/bin/sh
echo $@ > /root/unixchangegroup
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
leaderip=`echo $@  | awk '{print $1}'`;
groupname=`echo $@ | awk '{print $2}'`;
groupusers=`echo $@ | awk  '{print $3}' | sed 's/users//g' `
allusres=`echo $groupusers | sed 's/\,/ /g'`;
allusersel=`echo $allusers | wc -w`;
leaderip=` ./etcdgetlocal.py leaderip `
myhost=`/TopStor/etcdgetlocal.py clusternode`
groupusersn=`echo $groupusers | wc -c `
if [ $groupusersn -le 2 ];
then
 groupusers='NoUser'
fi
userreq=`echo $@  | awk '{print $3}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
stableuser="na"
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unst1025 info $userreq $groupname
leader=`./etcdgetlocal.py leader `
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
 stamp=`date +%s`;
 local=''
 myip=$leaderip
else
 stamp=` echo $@ | awk '{print $7}'`;
 local='local'
 myip=''
fi

 echo $groupusers | grep NoUser
 if [ $? -ne 0 ];
 then
#### getting users need to removed
  originalgroup=`/pace/etcdget${local}.py $myip usersigroup/$groupname`
  originalusers=`echo $originalgroup | awk -F'/' '{print $3}'`
  memoryallusers=$originalusers
  oldusers=$originalusers','
  oldusersel=` echo ${oldusers} | sed 's/,/ /g' | wc -w`
  while [ $oldusersel -gt 0 ];
  do
   l=`echo $oldusers |  cut -d, -f 1`
   lsn=`echo $l | wc -c `
   oldusers=`echo $oldusers | sed 's/ /,/g' | cut -d, -f2-`
   oldusers=$oldusers','
   oldusersel=`echo ${oldusers} | sed 's/,/ /g' | wc -w`
   if [ $lsn -le 2 ];
   then
    continue
   fi
   echo $groupusers | grep -w $l
   if [ $? -ne 0 ];
   then
    gpasswd -d $l $groupname
    originalusers=`echo $originalusers| sed "s/$l//g" | sed 's/^,//g' | sed 's/,,/,/g' | sed 's/,$//g'` 
   else
    stableuser=$stableuser' '$l
   fi 
  done 
  echo originalusers=$originalusers
  sleep 3
  echo $originalusers | grep $memoryallusers 
  if [ $? -ne 0 ];
  then
   cusersleft=`echo $originalgroup | cut -d/ -f1-2`
   cusersright=`echo $originalgroup | cut -d/ -f4-`
   newusers=$originalusers
   newop=$cusersleft'/'$newusers'/'$cusersright
   groupres=`echo ${newop}`
   /pace/etcdput${local}.py $myip usersigroup/$groupname  $groupres 
  fi 
  usersall=`echo $groupusers`','
  usersl=` echo ${usersall} | sed 's/,/ /g' | wc -w`
  while [ $usersl  -gt 0 ];
  do
   l=`echo $usersall |  cut -d, -f 1`
   usersall=`echo $usersall | sed 's/ /,/g' | cut -d, -f2-`
   usersall=$usersall','
   usersl=`echo ${usersall} | sed 's/,/ /g' | wc -w`
   echo $stableuser | grep  -w $l
   if [ $? -eq 0 ];
   then
    continue
   fi
   usergroups=`id -Gn $l | sed 's/ /,/g' | sed "s/$l,//g" | sed "s/$groupname//g" | sed "s/Everyone//g" | sed "s/,,/,/g" | sed 's/,,,/,/g' | sed 's/,,,,/,/g' | sed 's/^,//g' | sed 's/,$//g' `
   usergroupsn=`echo $usergroups | wc -c`
   if [ $usergroupsn -le 2 ];
   then
    usergroups=$groupname
   else
    usergroups=$usergroups','$groupname
   fi 
   echo /TopStor/UnixChangeUser $l groups$usergroups $userreq 
   /TopStor/UnixChangeUser $l groups$usergroups $userreq 2&>/root/UnixChangeUser
  done 
 else
   /TopStor/UnixChangeUser NoUser groups$groupname $userreq 2&>/root/UnixChangeUser
 fi 
 #/TopStor/broadcast.py GroupChange /TopStor/pump.sh UnixChangeGroup_sync -d$myhost $@ 
 /TopStor/logmsg.py Unsu1025 info $userreq $groupname
fi 
if [ -z $local ];
then
 /pace/etcdput.py $myip sync/user/`basename "$0"`_$@ $stamp/request/$myhost UsrChange_$stamp
 /pace/etcdput.py $myip sync/user/`basename "$0"`_$@ $stamp/request UsrChange_$stamp
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq 
