#!/bin/sh
echo $@ > /root/unixadduser
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@  | awk '{print $2}'`;
myhost=`hostname -s`
echo Unlin1017:$username > $web;
/TopStor/queuethis.sh `basename "$0"` running $userreq
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unlin1118 info $userreq $username
 /pace/etcdget.py volumes --prefix | grep -w $username
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021gv warning $userreq $username
  exit
 fi
 cat /etc/passwd | grep $username
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021gg warning $userreq $username
  exit
 fi
 groupdel $username
 homebase='-b /NoHome -M'
 userpass=${RANDOM}$RANDOM;
 pas=`echo $userpass | openssl enc -e -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`
 useradd -c"TopStorGroup"$pas $homebase -p $userpass -s /usr/sbin/nologin $username 
# /bin/smbpasswd -e $username
 sleep 2;
 userline=`cat /etc/passwd | grep $username`
 if [ $? -ne  0  ]; then
   /TopStor/logmsg.py Unlin1120 error $userreq $username
 else 
  userid=`echo $userline | awk -F':' '{print $3}'`
  usergd=`echo $userline | awk -F':' '{print $4}'`
  /TopStor/etcdput.py 'usersigroup/'$username $userid':'$usergd':'nogrouphome/nogroupsize'/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no'
  /TopStor/broadcast.py GroupAdd /TopStor/pump.sh UnixAddGroup_sync -d$myhost $username $userid $usergd
  /TopStor/logmsg.py Unlin1122 info $userreq $username
 fi 
fi
/TopStor/queuethis.sh `basename "$0"` finished $userreq
