#!/usr/local/bin/zsh
web='/var/www/html/des20/Data/isuser.txt';
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py UnixPrepUser start system &
fi
cd /TopStor
rm key/*chk 2>/dev/null
rm $web 2>/dev/null
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py UnixPrepUser stop system &
fi
