#!/bin/sh
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 ETCDCTL_API=3 /TopStor/logmsg.py Unlin1004 info $userreq $username
/bin/smbpasswd -d $username;
rm -rf /home/$username &>/dev/null
userdel -r  $username 2>txt/${0:2}$userreq.txt;
rm key/$username;
err=`wc -c txt/${0:2}$userreq.txt | awk '{print $1}'`;
datenow=`date +%m/%d/%Y`;timenow=`date +%T`;
if [[ $err -ge 3 ]]; then
 ETCDCTL_API=3 /TopStor/logmsg.py Unlin11001 error $userreq $hostnam/$DG/$name
else
 ETCDCTL_API=3 /TopStor/logmsg.py Unlin1010 info $userreq $username
fi;
ETCDCTL_API=3 /pace/etcddel.py md --prefix
fi
rm txt/${0:2}$userreq.txt
