#!/bin/sh
echo $@ > /root/unixchangegroup
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
groupname=`echo $@ | awk '{print $1}'`;
groupusers=`echo $@ | awk  '{print $2}' | sed 's/users//g' `;
userreq=`echo $@  | awk '{print $3}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
myhost=`hostname -s`
stableuser=""
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unst1025 info $userreq $groupname
 usersall=`/pace/etcdget.py usersigroup/$groupname`
 cusers=`echo $usersall | awk -F'/' '{print $3}' `
 echo $cusers | grep -w no >/dev/null
 if [ $? -ne 0 ];
 then
  cusersl=` echo ${cusers} | sed 's/,/ /g' | wc -w`
  while [ $cusersl  -gt 0 ];
  do
   l=`echo $cusers |  cut -d, -f 1`
   cusers=`echo $cusers | sed 's/ /,/g' | cut -d, -f2-`','
   cusersl=` echo ${cusers} | sed 's/,/ /g' | wc -w`
   echo $groupusers | grep -w $l >/dev/null 
   if [ $? -ne 0 ];
   then
    usergroups=`id -Gn $l | sed 's/ /,/g' | sed "s/$l,//g" | sed "s/$groupname,//g" | sed "s/,$groupname//g" | sed "s/$groupname//g"`
    echo Users to remove $l $usergroups
    echo /TopStor/UnixChangeUser $l groups$usergroups $userreq 
    /TopStor/UnixChangeUser $l groups$usergroups $userreq 2&>/root/UnixChangeUser
   else
    stableuser=${stableuser}$l','
    echo Users to keep ${stableuser}
   fi
  done
 fi
 groupusersl=`echo $groupusers | sed 's/,/ /g' | wc -w`
 while [ $groupusersl -gt 0 ];
 do
  l=`echo $groupusers |  cut -d, -f 1`
  groupusers=`echo $groupusers | cut -d, -f2-`','
  groupusersl=` echo ${groupusers} | sed 's/,/ /g' | wc -w`
  echo l=$l
  echo groupusers=$groupusers
  echo grpsl=$groupusersl
  echo $stableuser | grep -w $l >/dev/null
  if [ $? -ne 0 ];
  then
   usergroups=`id -Gn $l `
   usergroupsl=`echo $usergroups | wc -w`
   if [ $usergroupsl -lt 2 ];
   then
    usergroups=$groupname
   else
    usergroups=`echo $usergroups | sed 's/ /,/g' | sed "s/$l,//g"`','$groupname
   fi
   echo User to add $l $usergroups
   echo /TopStor/UnixChangeUser $l groups$usergroups $userreq 
   /TopStor/UnixChangeUser $l groups$usergroups $userreq  2&>/root/UnixChangeUser
  fi
 done
 /TopStor/broadcast.py GroupChange /TopStor/pump.sh UnixChangeGroup_sync -d$myhost $@ 
 /TopStor/logmsg.py Unsu1025 info $userreq $username
fi 
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
