#!/bin/sh
echo $@ > /root/tmp
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
resweb='/var/www/html/des20/Data/userpass.txtupdated';
logthis='/TopStordata/logthis.log'
glog='/var/www/html/des20/Data/TopStor.log';
passchange='/TopStordata/passchange'
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
txtres='/TopStordata/'`basename $0`'.txt'
cd /TopStor
rm -rf $txtres 2>/dev/null
userpass=`echo $@ | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
/TopStor/logmsg.py Unlin1012 info $userreq $username
myhost=`hostname -s`
cp $logthis $logging 2>/dev/null ; rm -rf $logthis 2>/dev/null;
usermod  -p $userpass $username
pas=`echo $userpass | openssl enc -e -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`
echo __1
isleader=`/TopStor/etcdget.py leader --prefix `
echo $isleader | grep $myip
if [ $? -eq 0 ];
then
 echo __1.5
 /TopStor/etcdput.py 'usershash/'$username $pas
else
 echo __1.6
 /TopStor/etcdputlocal.py $myip 'usershash/'$username $pas 2>/dev/null
fi
echo __3
echo $username | grep -w admin
if [ $? -eq 0 ];
then
 echo __3.5
 usermod $username -c"AdminStor"$pas
else
 echo __3.6
 usermod $username -c"TopStor"$pas
fi
echo __4
cp /TopStor/smbuserfix.sh /etc/
currentcifs=`pcs resource | grep cifs | awk '{print $1}'`
echo "$currentcifs" | while read y; do echo __4.5 $y; docker exec $y  sh /hostetc/smbuserfix.sh  e $username $userpass;  done; 
( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username 2>> $txtres
cat $txtres >> $passchange 
cat $txtres 
err=`wc -c  $txtres | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
  /TopStor/logmsg.py Unlin1013 error $userreq $username
else 
 echo $userpass > key/${username}fixed
 rm -rf key/${username}fixed.gpg
 gpg -e -u "QuickStor" -r "QuickStor" key/${username}fixed
 chmod 400 key/${username}fixed.gpg;
 rm -rf key/${username}fixed
 if [[ $username == "admin" ]]; then
  rm -rf factory/${username}fixed.gpg
  cp key/${username}fixed.gpg factory/;
 fi
  /TopStor/logmsg.py Unlin1015 info $userreq $username
fi 
resdate=`date +%s`;
resjson=`./jsonthis3.sh updated $resdate`;
echo $resjson > $resweb;
echo $isleader | grep $myhost 
if [ $? -eq 0 ];
then
 /pace/etcdput.py sync/passwd/UnixChkUser:UnixChangePass_${userpass}_${pas}_$userreq/request/$myhost passwd_$stamp
 /pace/etcdput.py sync/passwd/UnixChkUser:UnixChangePass_${userpass}_${pas}_$userreq/request passwd_$stamp
fi
/TopStor/logqueue.py `basename "$0"` finish $userreq 
