#!/usr/local/bin/zsh
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
userpass=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
myhost=`hostname -s`
echo Unlin1017:$username > $web;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py Unlin1018 info $userreq $username
pas=`echo $userpass | openssl enc -e -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`
useradd -c"TopStor"$pas -b /p$myhost -m -p $userpass -s /usr/sbin/nologin $username 2> $txtres
ln -s /p$myhost/$username /home/$username
chmod o-rwx /p$myhost/$username -R
( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username 2>> $txtres
#mkdir -p /Data/Common/$username;
#chown $username /Data/Common/$username;
err=`wc -c  $txtres | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
  /TopStor/logmsg.py Unlin1020 error $userreq $username
else 
# openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
 echo $userpass > key/${username}fixed
 gpg -u "QuickStor" -r"QuickStor" key/${username}fixed
 chmod 400 key/${username}fixed.gpg;
 rm -rf key/${username}fixed
  /TopStor/logmsg.py Unlin1022 info $userreq $username
fi 
 /pace/etcddel.py md --prefix
fi
