#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
myip=`pcs resource show CC | grep Attribute | awk '{print $2}' | awk -F'=' '{print $2 }'`
if [[ $contrun == 'true' ]]
then
/TopStor/UnixDelUserlocal $username $userreq
fi
cat /etc/passwd | grep $username
if [ $? -ne 0 ];
then
 /pace/etcddellocal.py $myip users $username 
fi
