#!/bin/sh
export ETCDCTL_API=3
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
resweb='/var/www/html/des20/Data/userpass.txtupdated';
logthis='/TopStordata/logthis.log'
glog='/var/www/html/des20/Data/TopStor.log';
passchange='/TopStordata/passchange'
txtres='/TopStordata/'`basename $0`'.txt'
cd /TopStor
rm -rf $txtres 2>/dev/null
pas=`echo $@ | awk '{print $1}'`;
userpass=`echo $pas | openssl enc -d -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`;
username=`echo $@ | awk '{print $2}'`;
userreq='system';
 /TopStor/logmsg.py Unlin1012 info $userreq $username
usermod  -p $userpass $username 2> $txtres
echo $username | grep -w admin
if [ $? -eq 0 ];
then
 usermod $username -c"AdminStor"$pas
else
 usermod $username -c"TopStor"$pas
fi
( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username 2>> $txtres
cat $txtres >> $passchange 
cat $txtres 
err=`wc -c  $txtres | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
  /TopStor/logmsg.py Unlin1013 error $userreq $username
else 
# openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
 echo $userpass > key/${username}fixed
 rm -rf key/${username}fixed.gpg
 gpg -e -u "QuickStor" -r "QuickStor" key/${username}fixed
 chmod 400 key/${username}fixed.gpg;
 rm -rf key/${username}fixed
 if [[ $username == "admin" ]]; then
  rm -rf factory/${username}fixed.gpg
  cp key/${username}fixed.gpg factory/;
 fi
  /TopStor/logmsg.py Unlin1015 info $userreq $username
fi 
resdate=`date +%s`;
resjson=`./jsonthis3.sh updated $resdate`;
echo $resjson > $resweb;
