#!/bin/sh
echo $@ > /root/unixchangeuser
export ETCDCTL_API=3
cd /TopStor
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
username=`echo $@ | awk '{print $1}'`;
usergroups=`echo $@ | awk  '{print $2}' | sed 's/groups//g' `;
grps=`echo $usergroups | sed 's/\,/ /g'`
userreq=`echo $@  | awk '{print $3}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
myhost=`hostname -s`
stablegrp=","
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logmsg.py Unst1024 info $userreq $username
# cgrps=`id -Gn $username | sed "s/$username//g"` 
 usermod -G $usergroups $username
 cgrps=`/pace/etcdget.py usersigroup $username`
 echo cgrps=$cgrps
 echo "${cgrps[@]}" | while read l;
 do
  cgrp=`echo $l | sed "s/('usersigroup\///g" | awk -F"'" '{print $1}' `  
  echo $usergroups | grep -w $cgrp 
  if [ $? -ne 0 ];
  then
   usersall=`/pace/etcdget.py usersigroup/$cgrp`
   cusers=`echo $usersall | awk -F'/' '{print $3}'`
   cusersleft=`echo $usersall | cut -d/ -f1-2`
   cusersright=`echo $usersall | cut -d/ -f3-`
   newusers=`echo ${cusers} | sed "s/$username//g" | sed 's/,,/,/g' | sed 's/\/,/\//g' | sed 's/,\//\//g'`
   resusers=`echo $newusers | grep wc -c`
   if [ $resusers -le 2 ];
   then
    newusers='no'
   fi
   newop=$cusersleft'/'$newusers'/'$cusersright
   groupres=`echo ${newop} | sed "s/$username//g" | sed 's/,,/,/g' | sed 's/\/,/\//g' | sed 's/,\//\//g'`
   echo to remove : $cgrp $newusers
  else
   stablegrp=$stablegrp','$cgrp;
   echo to keep : $cgrp   and $stablegrp
  fi
 done
 stablegrp=$stablegrp',''his'
 echo the stable=$stablegrp
 echo $grps | while read l;
 do
  cgrp=`echo $l | sed "s/('usersigroup\///g" | awk -F"'" '{print $1}' `  
  echo stab=$stablegrp and $cgrp
  echo $stablegrp | grep -w $cgrp
  if [ $? -ne 0 ];
  then
   usersall=`/pace/etcdget.py usersigroup/$l`
   cusers=`echo $usersall | awk -F'/' '{print $3}'`
   cusersleft=`echo $usersall | cut -d/ -f1-2`
   cusersright=`echo $usersall | cut -d/ -f3-`
   if echo $cusers | grep -w no
   echo [ $? -ne 0 ];
   then
    newusers=${cusers}','$username
   else 
    newusers=$username
   fi
  fi
  echo to add : $cgrp $newusers
 done
 exit
  /pace/etcdput.py usersigroup/$l $cusersright/$newusers/$cusersleft 
 /TopStor/etcdput.py 'usersinfo/'$username $userid':'$usergd':'$userhome'/'$size'/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no'
 /TopStor/etcdput.py 'usershash/'$username $userhash
 /TopStor/broadcast.py UserAdd /TopStor/pump.sh UnixAddUser_sync -d$myhost $username $userhash $userid $usergd $userhome
 /TopStor/logmsg.py Unlin1022 info $userreq $username
fi 
fi
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
