#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
myhost=`hostname -s`
ips='0'

run=`echo $@ | awk -F'run=' '{print $2}' | awk '{print $1}'`;
#echo $run | grep yes
#if [ $? -ne 0 ];
#then 
# exit
#fi

echo $@ > /root/volactivateImportparamHome
privilege="HOME";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo starting Volume Home activation for the pool $pool >> /root/volactivateImportparamHome
 ls /$pool | grep 'smb\.' 
 if [ $? -eq 0 ];
 then
  echo there is metadata about volumes in the  $pool.
  vols=`ls /$pool | grep 'smb\.' `
  echo "${vols[@]}" | while read l;
  do
   registry=`cat /$pool/$l | grep HOME | grep SUMMARY | awk '{print $NF}'`
   regn=`echo $registry | wc -c`
   if [ $regn -gt 10 ];
   then
    name=` echo $registry | awk -F'/' '{print $2}'`
    ipaddr=` echo $registry | awk -F'/' '{print $8}'`
    ipsubnet=` echo $registry | awk -F'/' '{print $9}'`
    /pace/etcdput.py volumes/HOME/$myhost/$pool/$name $registry
    /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet Home 
   fi
  done
 fi
fi
