#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
echo $@ > /root/VolumeDeleteHOME 
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $3}'`;
leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
pro=`echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
DG=`echo $pDG `;
privilege='HOME';
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi

  docker exec etcdclient /TopStor/logmsg.py NFS1000 info $userreq $volname
 cd /TopStor
 clearvol=`./prot.py clearvol $volname | awk -F'result=' '{print $2}'`
 if [ $clearvol != '-1' ];
 then
  docker stop $clearvol 
  docker container rm $clearvol 
  /sbin/pcs resource delete --force $clearvol  2>/dev/null
  rm /etc/samba/smb.$ipaddr;
 fi
 redvol=`./prot.py redvol $volname | awk -F'result=' '{print $2}'`
 if [ $redvol != '-1' ];
 then
  redipaddr=`echo $redvol | awk -F'/' '{print $1}' | awk -F'-' '{print $NF}'`
  /TopStor/delblock.py start${volname}_only stop${volname}_only /TopStordata/smb.${redipaddr}  ;
  cp /TopStordata/smb.${redipaddr}.new /TopStordata/smb.${redipaddr};
  echo redvol=$redvol
  resname=`echo $redvol | awk -F'/' '{print $1}'`
  newright=$redvol 
  mounts=`echo $newright |sed 's/\// /g'| awk '{$1=""; print}'`
  mount=''
  rm -rf /TopStordata/tempsmb.$redipaddr
  for x in $mounts; 
  do
   mount=$mount'-v /'$pool'/'$x':/'$pool'/'$x':rw '
   cat /TopStordata/smb.$x >>  /TopStordata/tempsmb.$redipaddr
  done
  cp /TopStordata/tempsmb.$redipaddr  /TopStordata/smb.$redipaddr
  rm -rf /TopStordata/tempsmb.$redipaddr
  docker stop $resname
  docker rm $resname
  docker run -d $mount --privileged \
   -e "HOSTIP=$redipaddr"  \
   -p $redipaddr:135:135 \
   -p $redipaddr:137-138:137-138/udp \
   -p $redipaddr:139:139 \
   -p $redipaddr:445:445 \
   -v /etc/localtime:/etc/localtime:ro \
   -v /TopStordata/smb.${redipaddr}:/config/smb.conf:rw \
   -v /opt/passwds/passwd:/etc/passwd:rw \
   -v /opt/passwds/group:/etc/group:rw \
   -v /opt/passwds/shadow:/etc/shadow:rw \
   -v /var/lib/samba/private:/var/lib/samba/private:rw \
   --name $resname 10.11.11.124:5000/smb
 fi
 rm /etc/samba/smb.$volname;
 echo $DG/$volname
 /sbin/zfs destroy -rf $DG/$volname 
 if [ $? -ne 0  ]; then
   docker exec etcdclient /TopStor/logmsg.py NFS1001 error $userreq $volname
   echo /sbin/zfs destroy -rf $DG/$volname >/root/errorVolumeDeleteHOME
 else
  rm -rf /$DG/smb.$volname
  /pace/etcddel.py $leaderip volume $volname
  stamp=`date +%s`
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
  /TopStor/SnapShotPeriodDelete $volname $userreq
  #/pace/delbroadcastlocal.py volume $volname
  /pace/putzpool.py $leaderip
  docker exec etcdclient /TopStor/logmsg.py NFS1002 info  $userreq $volname
 fi
 rm -rf /$DG/smb.$volname
fi
