#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/volchange
leaderip=` ./etcdgetlocal.py leaderip `
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py VolumeChangeCIFS start system 
fi
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
writev=`echo $@ | awk '{print $4}'`;
ipaddr=`echo $@ | awk '{print $5}'`;
ipsubnet=`echo $@ | awk '{print $6}'`;
active=`echo $@ | awk '{print $7}'`;
myhost=`echo $@ | awk '{print $8}'`;
userreq=` echo $@ | awk '{print $9}'`;
domain=` echo $@ | awk '{print $10}'`;
domainsrvn=` echo $@ | awk '{print $11}'`;
domainsrvi=` echo $@ | awk '{print $12}'`;
domadm=` echo $@ | awk '{print $13}'`;
dompass=` echo $@ | awk '{print $14}'`;
DG=`echo $pDG `;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/logqueue.py `basename "$0"` running $userreq
 if [ $writev != 'nogroup' ];
 then
  writev=`echo $writev | sed 's/nogroup//g'`
 fi
 echo $pDG $name $quota $writev $ipaddr $ipsubnet $myhost $userreq $extraparms>> /root/volchange
 /TopStor/logmsg.py VolCst01 info $userreq $name
 echo name=$name
 myhost=`hostname -s`
 older=`ETCDCTL_API=3 /pace/etcdgetlocal.py volumes $name `
 echo $older | grep DOMAIN
 if [ $? -ne 0 ];
 then
  extraparms=''
 else
  isparams=`echo $domain | wc -c`
  if [ $isparams -ge 3 ];
  then 
   extraparms='/'$domain'/'$domainsrvn'/'$domainsrvi'/'$domadm'/'$dompass
  else
    extraparms='/'`echo $older | awk -F'/' '{for(i=NF-4;i<=NF;i++) printf $i"/"; print ""}' | sed "s/')\///g"`
  fi
 fi
 echo /pace/etcdput.py $leaderip volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$oldipaddr/${oldipsubnet}$extraparms/$active >> /root/volchange
 oldipaddr=`zfs get -H ip:addr $DG/$name | awk '{print $3}'`
 oldipsubnet=`zfs get -H ip:subnet $DG/$name | awk '{print $3}'`
 ETCDCTL_API=3 /pace/etcddel.py $leaderip volumes $name
 ETCDCTL_API=3 /pace/etcdput.py $leaderip volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/${ipsubnet}$extraparms/$active
 stamp=`date +%s`
 leader=` ./etcdgetlocal.py leader `
 ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
 ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
 /TopStor/VolumefixChangeCIFS $pDG $name CIFS $oldipaddr $userreq 
 /TopStor/VolumeDockerChange.py /$DG/$name $ipaddr
 sed -i "s/$oldipaddr/$ipaddr/g" /$DG/smb.$name
 sed -i "s/$oldipsubnet/$ipsubnet/g" /$DG/smb.$name
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 /sbin/zfs set status:mount=$active $DG/$name
 echo $writev | grep DOMAIN
 if [ $? ne 0 ];
 then
  /TopStor/VolumeActivateCIFS vol=$name user=$userreq
 else 
   /TopStor/VolumeActivateCIFSdom vol=$name user=$userreq
 fi
 /pace/putzpool.py 
 /TopStor/logmsg.py VolCsu01 info $userreq $name
 echo ready ;
fi
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py VolumeChangeCIFS stop system 
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq
