#!/bin/sh
echo $@ >/root/volcreatenfs
cd /TopStor
export ETCDCTL_API=3
myhost=`hostname -s`
web='/var/www/html/des20/Data/NFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
shortname=`echo $@ | awk '{print $2}'`;
nameid=$RANDOM$RANDOM
name=${shortname}_$nameid
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
writev=`echo $@ | awk '{print $4}'`;
ipaddr=`echo $@ | awk '{print $5}'`;
ipsubnet=`echo $@ | awk '{print $6}'`;
active=`echo $@ | awk '{print $7}'`;
userreq=` echo $@ | awk '{print $7}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG`;
txtres='/TopStordata'`basename $0`'.txt'
rm -rf $txtres 2>/dev.null
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
/TopStor/logqueue.py `basename "$0"` running $userreq 
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /pace/etcdget.py volumes --prefix | grep $shortname
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021vv warning $userreq $shortname
  /TopStor/logqueue.py `basename "$0"` stop_canceled $userreq 
  exit
 fi
 /pace/etcdget.py usersinfo --prefix | grep $shortname
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021vu warning $userreq $name
  /TopStor/logqueue.py `basename "$0"` stop_canceled $userreq 
  exit
 fi
 oldname=` /sbin/zfs list | grep "$shortname" `;
 if [ $? -eq 0 ];
 then
   /TopStor/logmsg.py NFS1003 warning  $userreq $name
 else
  /TopStor/logmsg.py NFS1004 info  $userreq $name
 fi
 cd /TopStor
 /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o atime=off -o redundant_metadata=most -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name 2> $txtres
 /sbin/zfs set prot:kind=NFS $DG/$name 
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 /sbin/zfs set status:mount=$active $DG/$name

 oct1=`echo $ipaddr | awk -F'.' '{print $1}'`
 oct2=`echo $ipaddr | awk -F'.' '{print $2}'`
 oct3=`echo $ipaddr | awk -F'.' '{print $3}'`

 who=$oct1'.'$oct2'.'$oct3'.*'
 ETCDCTL_API=3 /pace/etcdput.py volumes/NFS/$myhost/$DG/$name $DG/$name/$who/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet/$active
 ETCDCTL_API=3 /pace/broadcasttolocal.py volumes/NFS/$myhost/$DG/$name $DG/$name/$who/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet/$active
 /TopStor/SnapshotCreateHourlytrend $DG $name 0 24 7 system 
 /TopStor/VolumeActivateNFS vol=$name user=$userreq
 ls /$DG/ | grep $name
 if [ $? -ne 0 ];
 then
  /TopStor/logmsg.py NFS1005 error  $userreq $name
 else 
  ETCDCTL_API=3 /pace/etcdput.py volumes/NFS/$myhost/$DG/$name $DG/$name/$who/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet/$active
 ETCDCTL_API=3 /pace/broadcasttolocal.py volumes/NFS/$myhost/$DG/$name $DG/$name/$who/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet/$active
  /TopStor/logmsg.py NFS1007 info $userreq $name
 fi;
 /pace/putzpool.py &
fi
echo ready ;
/TopStor/logqueue.py `basename "$0"` stop $userreq 
