#!/bin/sh
echo $@ >/root/Activatetmp
cd /TopStor
export ETCDCTL_API=3
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
host=`echo $@ | awk -F'host=' '{print $2}' | awk '{print $1}'`;
vol=`echo $@ | awk -F'vol=' '{print $2}' | awk '{print $1}'`;
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
myhost=`hostname -s`
ips='0'

privilege="NFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 stathost=`echo $host | wc -c`
 if [ $stathost -le 1 ]; then host=$myhost; fi
 statpool=`echo $pool | wc -c`
 if [ $statpool -le 1 ]; then statpool=0; else statpool=1; fi
 statvol=`echo $vol | wc -c`
 if [ $statvol -le 1 ]; then statvol=0; else statvol=1; fi
 stat=${statpool}${statvol}
 case $stat in
  01)
   echo volume only  for  $vol
    declare  vols=`/pace/etcdget.py volumes/NFS $vol`
   ;;
  10)
   echo pool only $pool
    declare  ips=`/pace/etcdget.py ipaddr $pool`
    declare  vols=`/pace/etcdget.py volumes/NFS  $pool`
   ;;
  11)
   echo 'volume and pool only'
    declare  vols=`/pace/etcdget.py volumes/NFS/$host/$pool/$vol`
   ;;
  00)
   echo 'host only'
   declare  vols=`/pace/etcdget.py volumes/NFS/$host --prefix`
 esac
 echo vols="${vols[@]}"
 volsc=`echo $vols | wc -c`
 if [ $volsc -le 2 ];
 then
  echo No Volumes
  exit
 fi
 echo "${vols[@]}" |  grep "\-1"
 if [ $? -eq 0 ];
 then
  echo No Volumes -1
  exit
 fi
 modprobe nfs
 modprobe nfsd
 systemctl start nfs-server
 ispoolonly=`echo $ips | wc -c `
 if [ $ispoolonly -gt 5 ];
 then
  echo "${ips[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read i;
  do
   ip=`echo $i | awk -F'-' '{print $3}' | awk -F'/' '{print $1}'`
   rm -rf /TopStordata/exports.$ip
   declare ipvol=`echo $i |  cut -d/ -f2-`
   echo "${ipvol[@]}" | sed 's/\//\n/g' | while read v;
   do
    l=`echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | grep $v` 
    lc=`echo $l | wc -c `
    if [ $lc -lt 3 ];
    then
     continue
    fi
    pool=`echo $l | awk -F'/' '{print $1}'`
    name=`echo $l | awk -F'/' '{print $2}'`
    echo $name
    path='/'${pool}'/'${name}
    shortname=`echo ${name} | rev | cut -d_ -f2- | rev`
   # ln '/'${pool}'/'${name} '/'${pool}'/'${shortname}
    #path='/'${pool}'/'${shortname}
    who=`echo $l | awk -F'/' '{print $3}'`
    access=`echo $l | awk -F'/' '{print $4}'`
    sync=`echo $l | awk -F'/' '{print $5}'`
    secure=`echo $l | awk -F'/' '{print $6}'`
    squash=`echo $l | awk -F'/' '{print $7}'`
    subtree=`echo $l | awk -F'/' '{print $8}'`
    writev=`echo $l | awk -F'/' '{print $9}'`
    ipaddr=`echo $l | awk -F'/' '{print $10}'`
    ipsubnet=`echo $l | awk -F'/' '{print $11}'`
    active=`echo $l | awk -F'/' '{print $12}'`
    writev=`echo $writev | sed 's/\,/ /g' `;
    echo $ipsubnet > /TopStordata/NFStmp
    echo $path' '$who'('$access','$sync','$secure','$squash','$subtree')' > /TopStordata/exports.$name 
    echo '# SUMMARY' $l  >> /TopStordata/exports.${name}
    yes | cp /TopStordata/exports.$name /$pool/exports.$name
    yes | cp /TopStordata/exports.$name /$pool/
    cat /TopStordata/exports.$name >> /TopStordata/exports.$ip
   done
   ipc=`cat /TopStordata/exports.$ip | wc -c`
   if [ $ipc -lt 10 ];
   then
     continue
   fi
   ipsubnet=`cat /TopStordata/NFStmp`
   rm -rf  /TopStordata/NFStmp
   echo running nfspoolonly
   /TopStor/nfspoolonly.sh $pool $i $ip $ipsubnet
  done
 else
  cp /etc/exports /TopStordata/exports.confcurrent
  echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
  do
   modprobe nfs
   modprobe nfsd
   systemctl start nfs-server
   echo l=$l;
   pool=`echo $l | awk -F'/' '{print $1}'`
   name=`echo $l | awk -F'/' '{print $2}'`
   path='/'${pool}'/'${name}
   shortname=`echo ${name} | rev | cut -d_ -f2- | rev`
   #ln '/'${pool}'/'${name} '/'${pool}'/'${shortname}
   #path='/'${pool}'/'${shortname}
   who=`echo $l | awk -F'/' '{print $3}'`
   access=`echo $l | awk -F'/' '{print $4}'`
   sync=`echo $l | awk -F'/' '{print $5}'`
   secure=`echo $l | awk -F'/' '{print $6}'`
   squash=`echo $l | awk -F'/' '{print $7}'`
   subtree=`echo $l | awk -F'/' '{print $8}'`
   writev=`echo $l | awk -F'/' '{print $9}'`
   ipaddr=`echo $l | awk -F'/' '{print $10}'`
   ipsubnet=`echo $l | awk -F'/' '{print $11}'`
   active=`echo $l | awk -F'/' '{print $12}'`
   writev=`echo $writev | sed 's/\,/ /g' `;
   echo $path' '$who'('$access','$sync','$secure','$squash','$subtree')' > /TopStordata/exports.$name 
    echo '# SUMMARY' $l  >> /TopStordata/exports.${name}
    yes | cp /TopStordata/exports.$name /$pool/exports.$name
   chmod 770 /$pool/$name
   setfacl -b /$pool/$name
   echo $writev | grep -w nogroup
   if [ $? -ne 0 ];
   then 
    for grp in $writev; do setfacl -m g:$grp:rwx /$pool/$name; done
   fi
   echo running nfs $pool $name $ipaddr $ipsubnet
   /TopStor/nfs.sh $pool $name $ipaddr $ipsubnet
   zfs set status:mount=$active $pool/$name
   echo $active | grep active
   if [ $? -eq 0 ];
    zfs mount $pool/$name
   else
    zfs unmount $pool/$name
   fi
  done
 fi
# /sbin/exportfs -ra
 echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
 do
  pool=`echo $l | awk -F'/' '{print $1}'`
  name=`echo $l | awk -F'/' '{print $2}'`
  writev=`echo $l | awk -F'/' '{print $9}'`
  writev=`echo $writev | sed 's/\,/ /g' `;
  volhost=`/pace/etcdget.py volumes/NFS/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdget.py volumes/NFS/$volhost/$pool/$name`
  volhost=`/pace/etcdget.py volumes/NFS/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdget.py volumes/NFS/$volhost/$pool/$name`
  ls /$pool/$name -lisah
  if [ $? -ne 0 ];
  then
   continue
  fi
  chmod 770 /$pool/$name
  sleep 1 
  setfacl -b /$pool/$name
  echo $writev | grep -w nogroup
  if [ $? -ne 0 ];
  then 
   for grp in $writev; do  setfacl -m g:$grp:rwx /$pool/$name; done
  fi
  /pace/etcdput.py volumes/NFS/$myhost/$pool/$name $volsvalue
  if [ $volhost != $myhost ];
  then
   /pace/etcddel.py volumes/NFS/$volhost/$pool/$name
  fi
 done
fi
