#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
myhost=`hostname -s`
ips='0'

run=`echo $@ | awk -F'run=' '{print $2}' | awk '{print $1}'`;
#echo $run | grep yes
#if [ $? -ne 0 ];
#then 
# exit
#fi

echo $@ > /root/volactivateImportparamHome
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo starting Volume CIFS activation for the pool $pool >> /root/volactivateImportparamHome
 ls /$pool | grep 'smb\.' 
 if [ $? -eq 0 ];
 then
  echo there is metadata about volumes in the  $pool.
  vols=`ls /$pool | grep 'smb\.' `
  echo "${vols[@]}" | while read l;
  do
   registry=`cat /$pool/$l | grep SUMMARY | awk '{print $3}'`
   name=` $l | awk -F'/' '{print $2}'`
   ipaddr=` $l | awk -F'/' '{print $8}'`
   ipsubnet=` $l | awk -F'/' '{print $9}'`
   /pace/etcdput.py volumes/Home/$myhost/$pool/$name $registry
   yes | cp /$pool/$l /TopStordata/smb.$ipaddr
   echo /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet cifs
   /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet Home 
  done
 fi
fi
# else
#  echo the $pool has no metadata for any volume 
#  declare  ips=`/pace/etcdget.py ipaddr $pool`
#  declare  vols=`/pace/etcdget.py volumes/CIFS  $pool`
#  echo the $pool has some known  volumes in the registery.
#  echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
#  do
#   pool=`echo $l | awk -F'/' '{print $1}'`
#   name=`echo $l | awk -F'/' '{print $2}'`
#   path='/'${pool}'/'${name}
#   readv=`echo $l | awk -F'/' '{print $3}'`
#   browsable=`echo $l | awk -F'/' '{print $4}'`
#   ipaddr=`echo $l | awk -F'/' '{print $8}'`
#   ipsubnet=`echo $l | awk -F'/' '{print $9}'`
#   writev=`echo $l | awk -F'/' '{print $5}'`
#   writev=`echo $writev | sed 's/\,/ /g' `;
#   admin=`echo $l | awk -F'/' '{print $6}'`
##   writeable=`echo $l | awk -F'/' '{print $7}'`
#   sed -i "s/SHORTNAME/$shortname/g"  /TopStordata/smb.${name}
#   sed -i "s/NAMECIFS/$name/g"  /TopStordata/smb.${name}
#   sed -i "s/POOL/$pool/g" /TopStordata/smb.${name}
#   sed -i "s/no/$readv/g" /TopStordata/smb.${name}
#   sed -i "s/yes/$browsable/g" /TopStordata/smb.${name}
#   sed -i "s/\@everyone/$writev/g" /TopStordata/smb.${name}
#   sed -i "s/administrator/$admin/g" /TopStordata/smb.${name}
#   sed -i "s/Yes/$writeable/g" /TopStordata/smb.${name}
#   sed -i "s/IPADDRESS/$ipaddr/g" /TopStordata/smb.${name}
#   sed -i "s/IPSUBNET/$ipsubnet/g" /TopStordata/smb.${name}
#   chmod 770 /$pool/$name
#   yes | cp /TopStordata/smb.$name /$pool/
#   /pace/etcdput.py volumes/CIFS/$myhost/$pool/$name $pool/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet
#   echo running cifs.sh=$pool $name $ipaddr $ipsubnet >> /root/volactivateparam
#   echo /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet
#   /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet cifs
#   echo finished cifs.sh >> /root/volactivateparam
#  done
#fi
# runvol=`./etcdget.py volumes/CIFS $pool` 
# vols=`zfs list -H -o name,prot:kind | grep CIFS | grep $pool | awk '{print $1}' | sed "s/$pool\///g" | grep -v $pool`
# echo spanning the volumes in the pool $pool  metadata
## echo "${vols[@]}" | while read name;
# do
#  echo  $runvol | grep $name
#  if [ $? -ne 0 ];
#  then
#   echo the volume $name is not listed in the registery 
#   echo $name | grep \_
#   if [ $? -ne 0 ];
#   then
#    continue
#   fi
#   echo activating vol=$pool/$name >> /root/volactivateparam
#   echo activating vol=$pool/$name 
#   ipaddr=`zfs get -H ip:addr $pool/$name | awk '{print $3}'`
#   echo got ip $ipaddr
#   ipsubnet=`zfs get -H ip:subnet $pool/$name | awk '{print $3}'`
#   echo got ip $ipsubnet
#   admin=$userreq
#   writeable='Yes'
#   yes | cp sharecifs.txt /TopStordata/smb.${name}
#   shortname=`echo ${name} | rev | cut -d_ -f2- | rev`
#   sed -i "s/SHORTNAME/$shortname/g"  /TopStordata/smb.${name}
#   sed -i "s/NAMECIFS/$name/g"  /TopStordata/smb.${name}
#   sed -i "s/POOL/$pool/g" /TopStordata/smb.${name}
#   sed -i "s/no/no/g" /TopStordata/smb.${name}
#   sed -i "s/yes/yes/g" /TopStordata/smb.${name}
#   sed -i "s/\@everyone/\@everyone/g" /TopStordata/smb.${name}
#   sed -i "s/administrator/administrator/g" /TopStordata/smb.${name}
#   sed -i "s/Yes/$writeable/g" /TopStordata/smb.${name}
#   sed -i "s/IPADDRESS/$ipaddr/g" /TopStordata/smb.${name}
#   sed -i "s/IPSUBNET/$ipsubnet/g" /TopStordata/smb.${name}
#   chmod 770 /$pool/$name
#   yes | cp /TopStordata/smb.$name /$pool/
#   /pace/etcdput.py volumes/CIFS/$myhost/$pool/$name $pool/$name/no/yes/@everyone/administrator/yes/$ipaddr/$ipsubnet
#   echo running cifs.sh=$pool $name $ipaddr $ipsubnet >> /root/volactivateparam
#   echo /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet
#   /TopStor/cifs.sh $pool $name $ipaddr $ipsubnet cifs
#   echo finished cifs.sh >> /root/volactivateparam
#  fi
# done
#fi
