#!/bin/sh
echo $@ >/root/tmp
cd /TopStor
export ETCDCTL_API=3
myhost=`hostname -s`
web='/var/www/html/des20/Data/NFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
writev=`echo $@ | awk '{print $4}'`;
ipaddr=`echo $@ | awk '{print $5}'`;
ipsubnet=`echo $@ | awk '{print $6}'`;
userreq=` echo $@ | awk '{print $7}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG`;
txtres='/TopStordata'`basename $0`'.txt'
rm -rf $txtres 2>/dev.null
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
/TopStor/queuethis.sh `basename "$0"` running $userreq &
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /pace/etcdget.py volumes --prefix | grep -w $name
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021vv warning $userreq $name
  /TopStor/queuethis.sh `basename "$0"` canceled $userreq &
  exit
 fi
 /pace/etcdget.py usersinfo --prefix | grep -w $name
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py Unlin1021vu warning $userreq $name
  /TopStor/queuethis.sh `basename "$0"` canceled $userreq &
  exit
 fi
 oldname=` /sbin/zfs list | grep -w "$name" `;
 if [ $? -eq 0 ];
 then
   /TopStor/logmsg.py NFS1003 warning  $userreq $name
 else
  /TopStor/logmsg.py NFS1004 info  $userreq $name
 fi
 cd /TopStor
 /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o atime=off -o redundant_metadata=most -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name 2> $txtres
 /sbin/zfs set prot:kind=NFS $DG/$name 
 ETCDCTL_API=3 /pace/etcdput.py volumes/NFS/$myhost/$DG/$name $DG/$name/*/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet
 /TopStor/VolumeActivateNFS vol=$name user=$userreq
 ls /$DG/ | grep $name
 if [ $? -ne 0 ];
 then
  /TopStor/logmsg.py NFS1005 error  $userreq $name
 else 
  ETCDCTL_API=3 /pace/etcdput.py volumes/NFS/$myhost/$DG/$name $DG/$name/*/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet
  /TopStor/logmsg.py NFS1007 info $userreq $name
 fi;
 /pace/putzpool.py &
fi
fi
echo ready ;
/TopStor/queuethis.sh `basename "$0"` finished $userreq &
