#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
echo $@ > ~/homedel
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
userreq=` echo $@ | awk '{print $3}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG `;
txtres='/TopStordata/'`basename $0`$userreq
rm -rf $txtres &>/dev/null
echo CIFS1005:$hostnam/$volname > $web;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py NFS1000 info $userreq $volname
cd /TopStor
/sbin/zfs destroy -rf $DG/$volname  &> $txtres
if [ $? -ne 0  ]; then
  /TopStor/logmsg.py NFS1001 error $userreq $volname
  exit
fi
cp /etc/samba/smb.conf /TopStordata/smb.confcurrent;
 rm /TopStordata/$volname;
 /TopStor/delblock.py start${volname}_only stop${volname}_only /TopStordata/smb.confcurrent  ;
 /TopStor/delblock.py start${volname}_only stop${volname}_only /TopStordata/CIFSshares.txt  ;
 cp /TopStordata/smb.confcurrent.new /etc/samba/smb.conf;
 /pace/etcddel.py volumes $volname
 /pace/delbroadcastlocal.py volumes $volname
 /TopStor/SnapShotPeriodDelete $volname $userreq
 systemctl restart smb
 /pace/putzpool.py 
 /TopStor/logmsg.py NFS1002 info  $userreq $volname
fi
