#!/bin/sh
cd /TopStor/
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;

echo CIFS1001:$hostnam/$DG/$name > $web;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
oldname=` ssh $sshost /sbin/zfs list | grep -w "$name" | wc -c `;
if [[ $oldname -ge 4 ]];
then 
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1004 info $userreq $hostnam/$DG/$name
else
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1004 info $userreq $hostnam/$DG/$name
g=`ssh $sshost cat /TopStor/smb.confcurrent | grep ${name}_only | wc -c`; 
if [[ g -ge 4 ]];
then
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1005 warning $userreq $hostnam/$DG/$name
else
ssh $sshost " cd /TopStor &&
 /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o redundant_metadata=most -o atime=off -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name 2> $txtres  &&
 /sbin/zfs set prot:kind=CIFS $DG/$name &&
 cp /etc/samba/smb.conf /TopStordata/smb.confcurrent &&
 cp sharecifs.txt /TopStordata/$name.txt
 sed -i "s/NAMECIFS/$name/g"  /TopStordata/$name.txt &&
 sed -i "s/POOL/$DG/g" /TopStordata/$name.txt &&
 cat /TopStordata/$name.txt >> /TopStordata/smb.confcurrent &&
 cat /TopStordata/$name.txt >> /TopStordata/CIFSshares.txt &&
 cat /TopStordata/$name.txt >> /etc/samba/smb.conf &&
 chmod 777 /$DG/$name
 systemctl stop smb &&
 systemctl start smb " 
scp $sshost:$txtres $txtres
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
err=`wc -c  $txtres  | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1005 error $userreq $hostnam/$DG/$name
else 
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1006 info $userreq $hostnam/$DG/$name
fi;
fi
fi
fi
echo ready ;
ETCDCTL_API=3 /pace/etcddel.py md --prefix
