#!/bin/sh
echo $@ >/root/Activatetmp
cd /TopStor
export ETCDCTL_API=3
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
myip=`echo $@ | awk '{print $1}'`;
host=`echo $@ | awk -F'host=' '{print $2}' | awk '{print $1}'`;
vol=`echo $@ | awk -F'vol=' '{print $2}' | awk '{print $1}'`;
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
leaderip=` ./etcdgetlocal.py leaderip `
myhost=`/TopStor/etcdgetlocal.py clusternode`
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 stathost=`echo $host | wc -c`
 if [ $stathost -le 1 ]; then host=$myhost; fi
 statpool=`echo $pool | wc -c`
 if [ $statpool -le 1 ]; then statpool=0; else statpool=1; fi
 statvol=`echo $vol | wc -c`
 if [ $statvol -le 1 ]; then statvol=0; else statvol=1; fi
 stat=${statpool}${statvol}
 case $stat in
  01)
   echo volume only  for  $vol
    declare  vols=`/pace/etcdgetlocal.py volumes/NFS $vol`
   ;;
  10)
   echo pool only $pool
    declare  ips=`/pace/etcdgetlocal.py ipaddr $pool`
    declare  vols=`/pace/etcdgetlocal.py volumes/NFS  $pool`
   ;;
  11)
   echo 'volume and pool only'
    declare  vols=`/pace/etcdgetlocal.py volumes/NFS/$host/$pool/$vol`
   ;;
  00)
   echo 'host only'
   declare  vols=`/pace/etcdgetlocal.py volumes/NFS/$host --prefix`
 esac
 echo vols="${vols[@]}"
 volsc=`echo $vols | wc -c`
 if [ $volsc -le 2 ];
 then
  echo No Volumes
  exit
 fi
 echo "${vols[@]}" |  grep "\-1"
 if [ $? -eq 0 ];
 then
  echo No Volumes -1
  exit
 fi
 modprobe nfs
 modprobe nfsd
 echo "${ips[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read i;
 do
  ip=`echo $i | awk -F'-' '{print $3}' | awk -F'/' '{print $1}'`
  rm -rf /TopStordata/exports.$ip
  declare ipvol=`echo $i |  cut -d/ -f2-`
  echo "${ipvol[@]}" | sed 's/\//\n/g' | while read v;
  do
   l=`echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | grep $v` 
   lc=`echo $l | wc -c `
   if [ $lc -lt 3 ];
   then
    continue
   fi
   pool=`echo $l | awk -F'/' '{print $1}'`
   name=`echo $l | awk -F'/' '{print $2}'`
   echo $name
   path='/'${pool}'/'${name}
   who=`echo $l | awk -F'/' '{print $3}'`
   access=`echo $l | awk -F'/' '{print $4}'`
   sync=`echo $l | awk -F'/' '{print $5}'`
   secure=`echo $l | awk -F'/' '{print $6}'`
   squash=`echo $l | awk -F'/' '{print $7}'`
   subtree=`echo $l | awk -F'/' '{print $8}'`
   writev=`echo $l | awk -F'/' '{print $9}'`
   ipaddr=`echo $l | awk -F'/' '{print $10}'`
   ipsubnet=`echo $l | awk -F'/' '{print $11}'`
   writev=`echo $writev | sed 's/\,/ /g' `;
   echo $path' '$who'('$access','$sync','$secure','$squash','$subtree')' > /TopStordata/exports.$name 
   cat /TopStordata/exports.$name >> /TopStordata/exports.$ip
   yes | cp /TopStordata/exports.$name /$pool/
  done
  ipc=`cat /TopStordata/exports.$ip | wc -c`
  if [ $ipc -lt 10 ];
  then
    continue
  fi
  /TopStor/nfslocal.sh $myip $pool $i $ip $ipsubnet
 done
 echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
 do
  pool=`echo $l | awk -F'/' '{print $1}'`
  name=`echo $l | awk -F'/' '{print $2}'`
  writev=`echo $l | awk -F'/' '{print $9}'`
  writev=`echo $writev | sed 's/\,/ /g' `;
  volhost=`/pace/etcdgetlocal.py volumes/NFS/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdgetlocal.py volumes/NFS/$volhost/$pool/$name`
  volhost=`/pace/etcdgetlocal.py volumes/NFS/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdgetlocal.py volumes/NFS/$volhost/$pool/$name`
  /pace/etcdput.py $leaderip volumes/NFS/$myhost/$pool/$name $volsvalue
  if [ $volhost != $myhost ];
  then
   /pace/etcddel.py $leaderip volumes/NFS/$volhost/$pool/$name
  fi
 done
  stamp=`date +%s`
  leader=` ./etcdgetlocal.py leader `
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request/$leader volumes_$stamp
 
fi
