#!/bin/sh
echo $@ >/root/tmp
cd /TopStor
export ETCDCTL_API=3
myhost=`hostname -s`
web='/var/www/html/des20/Data/NFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
writev=`echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG`;
txtres='/TopStordata'`basename $0`'.txt'
rm -rf $txtres 2>/dev.null
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
/TopStor/logmsg.py VolCst01 info $userreq $name $writev
ETCDCTL_API=3 /pace/etcdput.py volumes/NFS/$myhost/$DG/$name $DG/$name/*/rw/sync/insecure/no_root_squash/no_all_squash/$writev
/TopStor/VolumeActivateNFS vol=$name user=$userreq
/TopStor/logmsg.py VolCsu01 info $userreq $name $writev
fi;
 /pace/putzpool.py &
echo ready ;
