#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
#pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
#userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
dockern=`docker ps | grep 445 | wc -l`
pcsn=`pcs resource | grep pdhcp | grep -v nfs | wc -l`
etcdn=`./etcdget.py vol --prefix | grep -v NFS | wc -l`
smbs=` ls /pdhcp*/smb.* | grep _ | wc -l`
if [[ $dockern$pcsn$etcdn == $smbs$smbs$smbs ]];
then
  echo all is good
  exit
fi
myhost=`hostname -s`
ips='0'
pools=`ls -1 / | grep pdhcp `
echo "${pools[@]}" | while read pool;
do
 echo '############' $pool '##############'
 ips=`cat /$pool/smb.* | grep SUMMARY | awk '{print $NF}' | awk -F'/' '{print $8}'`
 echo "${ips[@]}" | while read ip;
 do
  echo '############' $ip '##############'
  docker ps | grep $ip  >/dev/null
  if [ $? -ne 0 ];
  then
   echo $ip
   #./etcddel.py vol $ip
   #/sbin/pcs resource delete cifs-$pool-$ip 
   #/sbin/pcs resource delete Home-$pool-$ip 
   echo '############' deleted $ip '##############'
  fi
 done
  sleep 2
  echo activatinggggggggggggggggggggggg
  /TopStor/VolumeActivateCIFSImport pool=$pool user=system
  /TopStor/VolumeActivateHomeImport pool=$pool user=system
 ips=`cat /$pool/exports.* | grep SUMMARY | awk '{print $NF}' | awk -F'/' '{print $10}'`
 echo "${ips[@]}" | while read ip;
 do
  cat /etc/exports | grep $ip >/dev/null 
  if [ $? -ne 0 ];
  then
   ./etcddel.py vol $ip
   pcs resource delete nfs-$pool-$ip
   /TopStor/VolumeActivateNFSImport pool=$pool user=system
  fi
 done
done
