#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/volcreatehome
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
shortname=`echo $@ | awk '{print $2}'`;
nameid=$RANDOM$RANDOM
name=${shortname}_$nameid
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
writev=`echo $@ | awk '{print $4}'`;
ipaddr=`echo $@ | awk '{print $5}'`;
ipsubnet=`echo $@ | awk '{print $6}'`;
userreq=` echo $@ | awk '{print $7}'`;
DG=$pDG;
hi=`whoami`
echo start $hi $userreq > /root/volcreate
ETCDCTL_API=3 /TopStor/logqueue.py VolumeCreateHome running $userreq 
echo queuedrunning >> /root/volcreate

privilege="CIFS";
./privthis.sh $privilege $userreq | grep true ;
if [ $? -eq 0 ];
then
 echo privileged $name >> /root/volcreate
# /pace/etcdget.py volumes --prefix | grep $shortname
# if [ $? -eq 0 ];
# then
#  echo here >> /root/volcreate
#  /TopStor/logmsg.py Unlin1021vv warning $userreq $shortname
#  /TopStor/logqueue.py `basename "$0"` stop_canceled $userreq 
#  exit
# fi
#  echo aftervolumes >> /root/volcreate
# /pace/etcdget.py usersinfo --prefix | grep $shortname
# if [ $? -eq 0 ];
# then
#  echo here2 >> /root/volcreate
#  /TopStor/logmsg.py Unlin1021vu warning $userreq $shrotname
#  /TopStor/logqueue.py VolumeCreateHome stop_canceled $userreq 
#  exit
# fi
 echo afterusersinfo >> /root/volcreate
 echo name=$name
 /sbin/zfs list | grep  "$shortname" 
 if [ $? -eq 0  ];
 then 
  /TopStor/logmsg.py NFS1003 warning $userreq $DG/$name
 fi
 echo afterzfslist info $userreq $DG/$name >> /root/volcreate
 /TopStor/logmsg.py NFS1004 info $userreq $DG/$name
 echo here4 >> /root/volcreate
 /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o redundant_metadata=most -o atime=off -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name  
 if [ $? -ne 0 ];
 then
  echo here5 >> /root/volcreate
  /TopStor/logmsg.py NFS1006 error $userreq $DG/$name
  /TopStor/logqueue.py `basename "$0"` stop_canceled $userreq 
  exit
 fi
 /sbin/zfs set prot:kind=Home $DG/$name
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 myhost=`hostname -s`
 echo /pace/etcdput.py volumes/Home/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes >> /root/volcreate
 ETCDCTL_API=3 /pace/etcdput.py volumes/Home/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet
 /pace/broadcasttolocal.py volumes/Home/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet 
 ./VolumeActivateHome vol=$name user=$userreq
 /pace/putzpool.py 
 /TopStor/logmsg.py NFS1007 info $userreq $DG/$name
 echo ready ;
fi
/TopStor/logqueue.py `basename "$0"` stop $userreq 
