#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/volhome
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
name=`echo $@ | awk '{print $2}'`;
#nameid=$RANDOM$RANDOM
#name=${name}_$nameid
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
ipaddr=` echo $@ | awk '{print $5}'`;
subnet=` echo $@ | awk '{print $6}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;

echo CIFS1001:$hostnam/$DG/$name > $web;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo name=$name
 /sbin/zfs list | grep -w "$name" 
 if [ $? -eq 0  ];
 then 
  /TopStor/logmsg.py NFS1003 warning $userreq $DG/$name
 fi
 /TopStor/logmsg.py NFS1004 info $userreq $DG/$name
 cd /TopStor
 /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o redundant_metadata=most -o atime=off -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name  
 if [ $? -ne 0 ];
 then
  /TopStor/logmsg.py NFS1006 error $userreq $DG/$name
  echo error
  exit
 fi
 usern=` echo $name | awk -F'_' '{print $1}'`
 /sbin/zfs set prot:kind=HOMe $DG/$name
 /sbin/zfs set ip:addr=na $DG/$name
 /sbin/zfs set ip:subnet=na $DG/$name
 /sbin/zfs set ip:user=$usern $DG/$name
 sleep 1 
 x=1
 while [ $x -gt 0 ]; 
 do
  ls -l /$pDG |  awk '{print $3}' | grep -w $name
  if [ $? -ne 0 ];
  then
   echo here
   /bin/chown  $name /$pDG/$name
   /bin/chmod 700 /$DG/$name
   sleep 1
  else 
   echo neer
   x=0
  fi
 done
 
 myhost=`hostname -s`
 echo /pace/etcdput.py volumes/HOMe/$myhost/$DG/$name $DG/$name/no/yes/@everyone/administrator/yes >> /root/volhome
 ETCDCTL_API=3 /pace/etcdput.py volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet
 /pace/broadcasttolocal.py volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet 
 /TopStor/VolumeActivateHome vol=$name user=$userreq
 /pace/putzpool.py 
 /TopStor/logmsg.py NFS1007 info $userreq $DG/$name
 echo ready ;
fi
