#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $2}'| awk -F'/' '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG `;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo $@ > /root/VolumeDestroy
 /TopStor/logmsg.py NFS1000 info $userreq $volname
 prop=`/pace/etcdget.py volumes/CIFS/$myhost/$pDG/$volname`
 ipaddr=`echo $prop | awk -F'/' '{print $8}'`
 ipaddrvol=`/pace/etcdget.py ipaddr/$ipaddr`
 count=`echo $ipaddrvol | awk -F'/' '{print $1}'`
 if [ $count -lt 2 ];
 then
  /pace/etcddel.py ipaddr/$ipaddr
  /pace/delbroadcastlocal.py ipaddr $ipaddr
  docker stop nfs-$DG-$volname
  docker container rm nfs-$DG-$volname
  /sbin/pcs resource delete --force ip-$volname  2>/dev/null
  /sbin/zfs destroy -r $DG/$volname
  if [ $? -ne 0  ]; then
   /TopStor/logmsg.py NFS1001 error $userreq $volname
  else 
   rm -rf /etc/exports.$volname
   rm -rf /etc/exports.$ipaddr
   /pace/etcddel.py volumes $volname
   /pace/delbroadcastlocal.py volumes $volname
   /TopStor/SnapShotPeriodDelete $volname $userreq
   /TopStor/logmsg.py NFS1002 info $userreq $volname
   rm -rf /$DG/$volname
  fi
 else
  /sbin/zfs destroy -rf $DG/$volname 
  if [ $? -ne 0  ]; then
    /TopStor/logmsg.py NFS1001 error $userreq $volname
  else
   newcount=$((count-1));
   origvol=`echo $ipaddrvol | awk -F'/' '{print $2}'`
   /pace/etcdput.py ipaddr/$ipaddr $newcount/$origvol
   /pace/broadcasttolocal.py ipaddr/$ipaddr $newcount/$origvol 
   rm /TopStordata/$volname;
   /TopStor/delblock.py ${volname} ${volname} /TopStordata/exports.$ipaddr ;
   cp /TopStordata/exports.${ipadrr}.new /TopStordata/exports.$ipaddr
   docker exec -it nfs-$pool-$origvol exportfs -ra 
   /pace/etcddel.py volume $volname
   /TopStor/SnapShotPeriodDelete $volname $userreq
   /pace/delbroadcastlocal.py volume $volname
   /pace/putzpool.py 
   /TopStor/logmsg.py NFS1002 info  $userreq $volname
  fi
 fi;
fi
 /pace/putzpool.py &
