#!/bin/sh
cd /TopStor
echo $@ > ~/`basename "$0"`
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
leaderip=`echo $@ | awk '{print $1}'`;
volname=`echo $@ | awk '{print $3}'`;
pDG=`echo $@ | awk '{print $2}'`;
pro=`echo $@ | awk '{print $4}'`;
volip=`echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
DG=pDG;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 /TopStor/cifsremove.sh $leaderip $pDG $volname $volip cifs 2>/root/errcifsremove
fi
