#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
myhost=`hostname -s`
ips='0'

run=`echo $@ | awk -F'run=' '{print $2}' | awk '{print $1}'`;
echo $run | grep yes
if [ $? -ne 0 ];
then 
 exit
fi
echo $@ > /root/volactivateImportparamNFS
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo starting Volume NFS activation for the pool $pool >> /root/volactivateImportparam
 declare  ips=`/pace/etcdget.py ipaddr $pool`
 declare  vols=`/pace/etcdget.py volumes/NFS  $pool`
 echo $vols | grep $pool
 if [ $? -ne 0 ]; 
 then
  ls /$pool | grep smb\. 
  if [ $? -eq 0 ];
  then
    vols=`ls /$pool | grep smb\. `
  fi
 else
  echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
  do
   pool=`echo $l | awk -F'/' '{print $1}'`
   name=`echo $l | awk -F'/' '{print $2}'`
   echo $name
   path='/'${pool}'/'${name}
   shortname=`echo ${name} | rev | cut -d_ -f2- | rev`
  # ln '/'${pool}'/'${name} '/'${pool}'/'${shortname}
   #path='/'${pool}'/'${shortname}
   who=`echo $l | awk -F'/' '{print $3}'`
   access=`echo $l | awk -F'/' '{print $4}'`
   sync=`echo $l | awk -F'/' '{print $5}'`
   secure=`echo $l | awk -F'/' '{print $6}'`
   squash=`echo $l | awk -F'/' '{print $7}'`
   subtree=`echo $l | awk -F'/' '{print $8}'`
   writev=`echo $l | awk -F'/' '{print $9}'`
   ipaddr=`echo $l | awk -F'/' '{print $10}'`
   ipsubnet=`echo $l | awk -F'/' '{print $11}'`
   writev=`echo $writev | sed 's/\,/ /g' `;
   echo $ipsubnet > /TopStordata/NFStmp
   echo $path' '$who'('$access','$sync','$secure','$squash','$subtree')' > /TopStordata/exports.$name 
   yes | cp /TopStordata/exports.$name /$pool/
   cat /TopStordata/exports.$name >> /TopStordata/exports.$ip
   /TopStor/nfs.sh $pool $name $ipaddr $ipsubnet
  done
 fi
 runvol=`./etcdget.py volumes/NFS $pool` 
 vols=`zfs list -H -o name,prot:kind | grep NFS | grep $pool | awk '{print $1}' | sed "s/$pool\///g" | grep -v $pool`
 echo "${vols[@]}" | while read vol;
 do
  echo  $runvol | grep $vol 
  if [ $? -ne 0 ];
  then
   oct123='10.15.15.'
   oct4=10
   while [ $noip -eq 1 ];
   do
    oct4=$((oct4+1))
    ip a | grep ${oct123}${oct4}
    if [ $? -ne 0 ];
    then
     noip=0
    fi
   done  
   ipaddr=${oct123}${oct4}
   ipsubnet='255.255.255.0'
   path='/'${pool}'/'${name}
   echo $path' 10.15.15.*\(rw,sync,insecure,no_root_squash,no_all_squash\)' > /TopStordata/exports.$name 
   admin=$userreq
   yes | cp /TopStordata/exports.$name /$pool/
   /pace/etcdput.py volumes/NFS/$myhost/$pool/$name $volsvalue
   /TopStor/nfs.sh $pool $name $ipaddr $ipsubnet
  fi
 done
fi
