#!/bin/sh
cd /TopStor
echo $@ > ~/`basename "$0"`
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $3}'`;
leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
pro=`echo $@ | awk '{print $4}'`;
volip=`echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
DG=pDG;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
		echo hihih
 		etcd=$myhostip
	else
		echo nono
 		etcd=$leaderip
 	fi
 echo etcd=$etcd
 docker exec etcdlient /TopStor/logmsg.py NFS1000 info $userreq $pDG/$volname
 docker exec etcdlient TopStor/logqueue.py `basename "$0"` running $userreq
 ipaddr=`/TopStor/etcdget.py $etcd ipaddr $volname | sed "s/$volname\///g" | sed "s/\/$volname//g"`
 ipaddrleft=` echo $ipaddr | awk -F"'," '{print $1}' | awk -F"'" '{print $2}'`
 ipaddrright=` echo $ipaddr | awk -F"'," '{print $2}' | awk -F"'" '{print $2}'`
 echo ip=$ipaddr
 echo ipright=$ipaddrright
 echo $ipaddrright | grep '/'
 if [ $? -ne 0 ];
 then
  echo $ipaddrleft | grep '/'
  if [ $? -eq 0 ];
  then
   ./etcddel.py $leaderip $ipaddrleft
  fi
 else
  ./etcdput.py $leaderip $ipaddrleft $ipaddrright
 fi
  stamp=`date +%s`
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pDG}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pDG}_$name/request/$leader volumes_$stamp
 /TopStor/cifsremove.sh $leaderip $pDG $volname $volip cifs 2>/root/errcifsremove
 /TopStor/SnapShotPeriodDelete $leaderip $volname $userreq
 echo /sbin/zfs destroy -rf $pDG/$volname 
 /sbin/zfs unmount -f $pDG/$volname 
 /sbin/zfs destroy -rf $pDG/$volname 
 if [ $? -ne 0  ]; then
   docker exec etcdlient /TopStor/logmsg.py NFS1001 error $userreq $volname
   echo /sbin/zfs destroy -rf $pDG/$volname >/root/errorVolumeDeleteHOME
   docker exec etcdlient /TopStor/logqueue.py `basename "$0"` stop $userreq
   exit
 fi
 rm -rf $pDG/$volname 
 echo rm -rf $pDG/$volname 
 docker exec etcdlient /TopStor/logmsg.py NFS1002 info $userreq $pDG/$volname
 docker exec etcdlient /TopStor/logqueue.py `basename "$0"` stop $userreq
fi
 docker exec etcdlient /TopStor/logqueue.py `basename "$0"` stop $userreq
