#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $2}'| awk -F'/' '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG `;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo $@ > /root/VolumeDestroy
 /TopStor/logmsg.py NFS1000 info $userreq $volname
 clearvol=`./prot.py clearvol $volname | awk -F'result=' '{print $2}'`
 if [ $clearvol != '-1' ];
 then
  docker stop $clearvol 
  docker container rm $clearvol 
  /sbin/pcs resource delete --force $clearvol  2>/dev/null
  rm /etc/samba/exports.$ipaddr;
 fi
 redvol=`./prot.py redvol $volname | awk -F'result=' '{print $2}'`
 if [ $redvol != '-1' ];
 then
  redipaddr=`echo $redvol | awk -F'/' '{print $1}' | awk -F'-' '{print $NF}'`
  /TopStor/delblock.py ${volname} ${volname} /TopStordata/exports.${redipaddr}  ;
  cp /TopStordata/smb.${redipaddr}.new /TopStordata/smb.${redipaddr};
  echo redvol=$redvol
  resname=`echo $redvol | awk -F'/' '{print $1}'`
  newright=$redvol 
  mounts=`echo $newright |sed 's/\// /g'| awk '{$1=""; print}'`
  mount=''
  for x in $mounts; 
  do
   mount=$mount'-v /'$pool'/'$x':/'$pool'/'$x':rw '
  done
  docker stop $resname
  docker rm $resname
  docker run -d $mount -v /TopStordata/exports.$redipaddr:/etc/exports:ro \
  --cap-add SYS_ADMIN -p $redipaddr:2049:2049  -p $redipaddr:2049:2049/udp \
  -p $redipaddr:32765:32765 -p $redipaddr:32765:32765/udp \
  -p $redipaddr:111:111 -p $redipaddr:111:111/udp \
  -p $redipaddr:32767:32767 -p $redipaddr:32767:32767/udp \
  -v /opt/passwds/passwd:/etc/passwd:rw \
  -v /opt/passwds/group:/etc/group:rw \
  -v /opt/passwds/shadow:/etc/shadow:rw \
  --name $resname 10.11.11.124:5000/nfs
 fi  
 rm -rf /etc/exports.$volname
 /sbin/zfs destroy -r $DG/$volname
 if [ $? -ne 0  ]; then
  /TopStor/logmsg.py NFS1001 error $userreq $volname
 else 
  /pace/etcddel.py volumes $volname
  /pace/delbroadcastlocal.py volumes $volname
  /TopStor/SnapShotPeriodDelete $volname $userreq
  /TopStor/logmsg.py NFS1002 info $userreq $volname
  rm -rf /$DG/$volname
 fi
fi
 /pace/putzpool.py &
