#!/usr/local/bin/zsh
cd /TopStor
echo $@ > ~/tmp
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG | awk -F_ '{print $2}'`;
hostnam=`echo $pDG | awk -F_ '{print $1}'`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
#sshost=`cat $runningpools | grep $hostnam | awk '{print $1}'`;
txtres='/TopStordata/'`basename $0`$userreq
rm -rf $txtres &>/dev/null
echo CIFS1005:$hostnam/$DG/$volname > $web;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1000 info $userreq $hostnam/$DG/$volname
ssh $sshost " cd /TopStor &&
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
 /sbin/zfs destroy -rf $DG/$volname"  &> $txtres
if [ $? -ne 0  ]; then
else 
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1001 error $userreq $hostnam/$DG/$volname
cp /etc/samba/smb.conf /TopStordata/smb.confcurrent;
 rm /TopStordata/$volname.txt;
 ./delblock.sh start${volname}_only stop${volname}_only /TopStordata/smb.confcurrent  ;
 ./delblock.sh start${volname}_only stop${volname}_only /TopStordata/CIFSshares.txt  ;
 cp /TopStordata/smb.confcurrent /etc/samba/smb.conf;
 systemctl restart smb
 ETCDCTL_API=3 /TopStor/logmsg.py NFS1002 info  $userreq $hostnam/$DG/$volname
fi;
./GetPoolVollist
fi
ETCDCTL_API=3 /pace/etcddel.py md --prefix
