#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/volactivateparam
leaderip=`echo $@ | awk '{print $1}'`;
host=`echo $@ | awk -F'host=' '{print $2}' | awk '{print $1}'`;
vol=`echo $@ | awk -F'vol=' '{print $2}' | awk '{print $1}'`;
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
ips='0'
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then

	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi

 echo starting Volume CIFS activation for  $vol >> /root/volactivateparam

    /TopStor/cifs.py $leader $leaderip $myhost $myhostip $etcd $pool $name $ipaddr $ipsubnet CIFS 
   else
    zfs unmount $pool/$name
   fi
   echo finished cifs.sh >> /root/volactivateparam
   echo writve=$writev
   setfacl -b /$pool/$name
   echo $writev | grep -w nogroup
   if [ $? -ne 0 ];
   then
    for grp in $writev ;do  setfacl -m g:$grp:rwx /$pool/$name; done
   fi
  done
 fi
 echo setting volumes registry >> /root/volactivateparam
 echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
 do
  pool=`echo $l | awk -F'/' '{print $1}'`
  name=`echo $l | awk -F'/' '{print $2}'`
  writev=`echo $l | awk -F'/' '{print $5}'`
  writev=`echo $writev | sed 's/\,/ /g' `;
  volhost=`/pace/etcdget.py $etcd volumes/CIFS/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdget.py $etcd volumes/CIFS/$volhost/$pool/$name`
  chmod 770 /$pool/$name
  sleep 1 
  setfacl -b /$pool/$name
  echo $writev | grep -w nogroup
  if [ $? -ne 0 ];
  then
   for grp in $writev; do setfacl -m g:$grp:rwx /$pool/$name; done
  fi
  /pace/etcdput.py $leaderip volumes/CIFS/$myhost/$pool/$name $volsvalue
  if [ $volhost != $myhost ];
  then
   /pace/etcddel.py $leaderip volumes/CIFS/$volhost/$pool/$name
  fi
 done
 stamp=`date +%s`
 ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request volumes_$stamp
 ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request/$leader volumes_$stamp
 
 echo finished setting volumes regestry >> /root/volactivateparam
fi
