#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/volactivate 
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
myip=`echo $@ | awk '{print $1}'`;
host=`echo $@ | awk -F'host=' '{print $2}' | awk '{print $1}'`;
vol=`echo $@ | awk -F'vol=' '{print $2}' | awk '{print $1}'`;
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;

leaderip=` ./etcdgetlocal.py leaderip `
myhost=`/TopStor/etcdgetlocal.py clusternode`
privilege="ISCSI";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo stating $host $pool
 stathost=`echo $host | wc -c`
 if [ $stathost -le 1 ]; then host=$myhost; fi
 statpool=`echo $pool | wc -c`
 if [ $statpool -le 1 ]; then statpool=0; else statpool=1; fi
 statvol=`echo $vol | wc -c`
 if [ $statvol -le 1 ]; then statvol=0; else statvol=1; fi
 stat=${statpool}${statvol}
 case $stat in
  01)
   echo volume only  for  $vol
    declare  vols=`/pace/etcdgetlocal.py volumes/ISCSI $vol`
   ;;
  10)
   echo pool only $pool
    declare  ips=`/pace/etcdgetlocal.py ipaddr $pool`
    declare  vols=`/pace/etcdgetlocal.py volumes/ISCSI  $pool`
    echo done
   ;;
  11)
   echo 'volume and pool only'
    declare  vols=`/pace/etcdgetlocal.py volumes/ISCSI/$host/$pool/$vol`
   ;;
  00)
   echo 'host only'
   declare  vols=`/pace/etcdgetlocal.py volumes/ISCSI/$host --prefix`
 esac
 echo vols="${vols[@]}"
 volsc=`echo $vols | wc -c`
 if [ $volsc -le 2 ];
 then
  echo No Volumes
  exit
 fi
 echo "${vols[@]}" |  grep "\-1"
 if [ $? -eq 0 ];
 then
  echo No Volumes -1
  exit
 fi
 echo "${ips[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read i;
 do
  ip=`echo $i | awk -F'-' '{print $3}' | awk -F'/' '{print $1}'`
  rm -rf /TopStordata/iscsi.$ip
  declare ipvol=`echo $i |  cut -d/ -f2-`
  echo "${ipvol[@]}" | sed 's/\//\n/g' | while read v;
  do
   l=`echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | grep $v` 
   lc=`echo $l | wc -c `
   if [ $lc -lt 3 ];
   then
    continue
   fi
   pool=`echo $l | awk -F'/' '{print $1}'`
   name=`echo $l | awk -F'/' '{print $2}'`
   path='/'${pool}'/'${name}
   ipaddr=`echo $l | awk -F'/' '{print $3}'`
   ipsubnet=`echo $l | awk -F'/' '{print $4}'`
   portalport=`echo $l | awk -F'/' '{print $5}'`
   targetiqn=`echo $l | awk -F'/' '{print $6}'`
   chapuser=`echo $l | awk -F'/' '{print $7}'`
   chappas=`echo $l | awk -F'/' '{print $8}'`
   yes | cp shareiscsi.txt /TopStordata/iscsi.${name}
   sed -i "s/NAMECIFS/$name/g"  /TopStordata/iscsi.${name}
   sed -i "s/POOL/$pool/g" /TopStordata/iscsi.${name}
   cat /TopStordata/iscsi.${name} >> /TopStordata/iscsi.$ip
   yes | cp /TopStordata/iscsi.$name /$pool/
  done
  ipc=`cat /TopStordata/iscsi.$ip | wc -l`
  if [ $ipc -lt 4 ];
  then
    continue
  fi
  echo i=$i
  echo ipc=$ipc for $ip
  echo ipvol=$ipvol
  /TopStor/iscsilocal.sh $myip $pool $i $ip $ipsubnet $portalport $targtiqn $chapuser $chappas
 done
 echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
 do
  pool=`echo $l | awk -F'/' '{print $1}'`
  name=`echo $l | awk -F'/' '{print $2}'`
  volhost=`/pace/etcdgetlocal.py volumes/ISCSI/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdgetlocal.py volumes/ISCSI/$volhost/$pool/$name`
  /pace/etcdput.py $leaderip volumes/ISCSI/$myhost/$pool/$name $volsvalue
  if [ $volhost != $myhost ];
  then
   /pace/etcddel.py $leaderip volumes/ISCSI/$volhost/$pool/$name
  fi
 done
 stamp=`date +%s`
 leaderall=` ./etcdgetlocal.py leader --prefix `
 leader=`echo $leaderall | awk -F'/' '{print $2}' | awk -F"'" '{print $1}'`
 ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request volumes_$stamp
 ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request/$leader volumes_$stamp
 
fi
