#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/volchange
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
writev=`echo $@ | awk '{print $4}'`;
ipaddr=`echo $@ | awk '{print $5}'`;
ipsubnet=`echo $@ | awk '{print $6}'`;
userreq=` echo $@ | awk '{print $7}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG`;
sshost=`echo $pDG | awk -F_ '{print $1}'`;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 if [ $writev != 'nogroup'];
 then
  writev=`echo $writev | sed 's/nogroup//g'`
 fi
 /TopStor/logmsg.py VolCst01 info $userreq $name
 echo name=$name
 myhost=`hostname -s`
 older=`ETCDCTL_API=3 /pace/etcdget.py volumes $name `
 echo /pace/etcdput.py volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes >> /root/volchange
 ETCDCTL_API=3 /pace/etcdput.py volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet
 /pace/broadcasttolocal.py volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/$writev/administrator/yes/$ipaddr/$ipsubnet 
 echo $older | grep $ipaddr/$ipsubnet
 if [ $? -ne 0 ];
 then 
  /TopStor/VolumeActivateCIFS vol=$name user=$userreq
 fi
 /pace/putzpool.py 
 /TopStor/logmsg.py VolCsu01 info $userreq $name
 echo ready ;
fi
