#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $2}'| awk -F'/' '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
userreq=` echo $@ | awk '{print $4}'`;
DG=`echo $pDG `;
hostnam=`echo $pDG `;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
/TopStor/logmsg.py NFS1000 info $userreq $volname
/sbin/zfs destroy -r $DG/$volname
if [ $? -ne 0  ]; then
 dtn=`date +%s -d $dt`;
  /TopStor/logmsg.py NFS1001 error $userreq $volname
else 
 cp /etc/exports /TopStordata/exports.confcurrent;
 /TopStor/delblock.py ${volname} ${volname} /TopStordata/exports.confcurrent  ;
 cp /TopStordata/exports.confcurrent.new /etc/exports;
 /pace/etcddel.py volumes $volname
 /pace/delbroadcastlocal.py volumes $volname
 /sbin/exportfs -ra
 /TopStor/logmsg.py NFS1002 info $userreq $volname
fi;
fi
 /pace/putzpool.py &
