#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/volcreateiscsi
shortname=`echo $@ | awk '{print $2}'`;
nameid=$RANDOM$RANDOM
name=${shortname}_$nameid
pDG=`echo $@ | awk '{print $1}'`;
quota=`echo $@ | awk '{print $3}'`;
ipaddr=`echo $@ | awk '{print $4}'`;
ipsubnet=`echo $@ | awk '{print $5}'`;
portalport=`echo $@ | awk '{print $6}'`;
targetiqn=`echo $@ | awk '{print $7}'`;
chapuser=`echo $@ | awk '{print $8}'`;
chappas=`echo $@ | awk '{print $9}'`;
active=`echo $@ | awk '{print $10}'`;
userreq=` echo $@ | awk '{print $11}'`;
DG=$pDG;
hi=`whoami`

leaderip=` ./etcdgetlocal.py leaderip `
myhost=`/TopStor/etcdgetlocal.py clusternode`
echo start $hi $userreq > /root/volcreate
ETCDCTL_API=3 /TopStor/logqueue.py VolumeCreateISCSI running $userreq 
echo queuedrunning >> /root/volcreate

privilege="ISCSI";
./privthis.sh $privilege $userreq | grep true ;
if [ $? -eq 0 ];
then
 echo privileged $name >> /root/volcreate
 /pace/etcdgetlocal.py volumes --prefix | grep $shortname
 if [ $? -eq 0 ];
 then
  echo here >> /root/volcreate
  /TopStor/logmsg.py Unlin1021vv warning $userreq $shortname
  /TopStor/logqueue.py `basename "$0"` stop_canceled $userreq 
  exit
 fi
  echo aftervolumes >> /root/volcreate
 /pace/etcdgetlocal.py usersinfo --prefix | grep $shortname
 if [ $? -eq 0 ];
 then
  echo here2 >> /root/volcreate
  /TopStor/logmsg.py Unlin1021vu warning $userreq $shrotname
  /TopStor/logqueue.py VolumeCreateISCSI stop_canceled $userreq 
  exit
 fi
 echo afterusersinfo >> /root/volcreate
 echo name=$name
 /sbin/zfs list | grep  "$shortname" 
 if [ $? -eq 0  ];
 then 
  /TopStor/logmsg.py NFS1003 warning $userreq $DG/$name
 fi
 pcs resource | grep -v iscsi | grep $ipaddr
 if [ $? -eq 0 ];
 then
  /TopStor/logmsg.py ISCSIwa01 warning $userreq $ipaddr 
  /TopStor/logqueue.py VolumeCreateISCSI stop_canceled $userreq 
  exit
 fi
 echo afterzfslist info $userreq $DG/$name >> /root/volcreate
 /TopStor/logmsg.py NFS1004 info $userreq $DG/$name
 echo here4 >> /root/volcreate
echo  /sbin/zfs create -V $quota -o dedup=on -o compression=lz4  $DG/$name  
/sbin/zfs create -V $quota -o dedup=on -o compression=lz4  $DG/$name  
# /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o redundant_metadata=most -o atime=off -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name  
 if [ $? -ne 0 ];
 then
  echo here5 >> /root/volcreate
  /TopStor/logmsg.py NFS1006 error $userreq $DG/$name
  /TopStor/logqueue.py `basename "$0"` stop_canceled $userreq 
  exit
 fi
 /sbin/zfs set prot:kind=ISCSI $DG/$name
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 /sbin/zfs set ip:portalport=$portalport $DG/$name
 /sbin/zfs set status:mount=$active $DG/$name
 echo /pace/etcdput.py $leaderip volumes/ISCSI/$myhost/$DG/$name $DG/$name/$ipaddr/$ipsubnet/$portalport/$targetiqn/$chapuser/$chappas/$active >> /root/volcreate
 /pace/etcdput.py $leaderip volumes/ISCSI/$myhost/$DG/$name $DG/$name/$ipaddr/$ipsubnet/$portalport/$targetiqn/$chapuser/$chappas/$active
#/pace/broadcasttolocal.py volumes/ISCSI/$myhost/$DG/$name $DG/$name/$ipaddr/$ipsubnet/$portalport/$targetiqn/$chapuser/$chappas/$active
 ./VolumeActivateISCSI vol=$name user=$userreq 
 /pace/putzpool.py 
 /TopStor/logmsg.py NFS1007 info $userreq $DG/$name
 echo ready ;
fi
#/TopStor/SnapshotCreateHourlytrend $DG $name 0 24 7 system 
/TopStor/logqueue.py `basename "$0"` stop $userreq 
