#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/volactivate 
web='/var/www/html/des20/Data/CIFSstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres 2>/dev/null
myip=`echo $@ | awk '{print $1}'`;
host=`echo $@ | awk -F'host=' '{print $2}' | awk '{print $1}'`;
vol=`echo $@ | awk -F'vol=' '{print $2}' | awk '{print $1}'`;
pool=`echo $@ | awk -F'pool=' '{print $2}' | awk '{print $1}'`;
userreq=`echo $@ | awk -F'user=' '{print $2}' | awk '{print $1}'`;
myhost=`/TopStor/etcdgetlocal.py clusternode`
leaderip=`/TopStor/etcdgetlocal.py leaderip`

privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 echo stating $host $pool
 stathost=`echo $host | wc -c`
 if [ $stathost -le 1 ]; then host=$myhost; fi
 statpool=`echo $pool | wc -c`
 if [ $statpool -le 1 ]; then statpool=0; else statpool=1; fi
 statvol=`echo $vol | wc -c`
 if [ $statvol -le 1 ]; then statvol=0; else statvol=1; fi
 stat=${statpool}${statvol}
 case $stat in
  01)
   echo volume only  for  $vol
    declare  vols=`/pace/etcdgetlocal.py volumes/CIFS $vol`
   ;;
  10)
   echo pool only $pool
    declare  ips=`/pace/etcdgetlocal.py ipaddr $pool`
    declare  vols=`/pace/etcdgetlocal.py volumes/CIFS  $pool`
    echo done
   ;;
  11)
   echo 'volume and pool only'
    declare  vols=`/pace/etcdgetlocal.py volumes/CIFS/$host/$pool/$vol`
   ;;
  00)
   echo 'host only'
   declare  vols=`/pace/etcdgetlocal.py volumes/CIFS/$host --prefix`
 esac
 echo vols="${vols[@]}"
 volsc=`echo $vols | wc -c`
 if [ $volsc -le 2 ];
 then
  echo No Volumes
  exit
 fi
 echo "${vols[@]}" |  grep "\-1"
 if [ $? -eq 0 ];
 then
  echo No Volumes -1
  exit
 fi
 echo "${ips[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read i;
 do
  ip=`echo $i | awk -F'-' '{print $3}' | awk -F'/' '{print $1}'`
  rm -rf /TopStordata/smb.$ip
  declare ipvol=`echo $i |  cut -d/ -f2-`
  echo "${ipvol[@]}" | sed 's/\//\n/g' | while read v;
  do
   l=`echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | grep $v` 
   lc=`echo $l | wc -c `
   if [ $lc -lt 3 ];
   then
    continue
   fi
   pool=`echo $l | awk -F'/' '{print $1}'`
   name=`echo $l | awk -F'/' '{print $2}'`
   path='/'${pool}'/'${name}
   readv=`echo $l | awk -F'/' '{print $3}'`
   browsable=`echo $l | awk -F'/' '{print $4}'`
   ipaddr=`echo $l | awk -F'/' '{print $8}'`
   ipsubnet=`echo $l | awk -F'/' '{print $9}'`
   writev=`echo $l | awk -F'/' '{print $5}'`
   writev=`echo $writev | sed 's/\,/ /g' `;
   admin=`echo $l | awk -F'/' '{print $6}'`
   writeable=`echo $l | awk -F'/' '{print $7}'`
   yes | cp sharecifs.txt /TopStordata/smb.${name}
   sed -i "s/NAMECIFS/$name/g"  /TopStordata/smb.${name}
   sed -i "s/POOL/$pool/g" /TopStordata/smb.${name}
   sed -i "s/no/$readv/g" /TopStordata/smb.${name}
   sed -i "s/yes/$browsable/g" /TopStordata/smb.${name}
   sed -i "s/administrator/$admin/g" /TopStordata/smb.${name}
   sed -i "s/Yes/$writeable/g" /TopStordata/smb.${name}
   sed -i "s/\@everyone/$writev/g" /TopStordata/smb.${name}
   cat /TopStordata/smb.${name} >> /TopStordata/smb.$ip
   yes | cp /TopStordata/smb.$name /$pool/
  done
  ipc=`cat /TopStordata/smb.$ip | wc -l`
  if [ $ipc -lt 4 ];
  then
    continue
  fi
  echo i=$i
  echo ipc=$ipc for $ip
  echo ipvol=$ipvol
  /TopStor/cifslocal.sh $myip $pool $i $ip $ipsubnet
 done
 echo "${vols[@]}" | awk '{print $2}' | sed "s/'//g" | sed "s/)//g" | sed "s/(//g"  | while read l;
 do
  pool=`echo $l | awk -F'/' '{print $1}'`
  name=`echo $l | awk -F'/' '{print $2}'`
  writev=`echo $l | awk -F'/' '{print $5}'`
  writev=`echo $writev | sed 's/\,/ /g' `;
  volhost=`/pace/etcdgetlocal.py volumes/CIFS/ $name | awk -F'/' '{print $3}'`
  volsvalue=`/pace/etcdgetlocal.py volumes/CIFS/$volhost/$pool/$name`
  /pace/etcdput.py $leaderip volumes/CIFS/$myhost/$pool/$name $volsvalue
  if [ $volhost != $myhost ];
  then
   /pace/etcddel.py $leaderip volumes/CIFS/$volhost/$pool/$name
  fi
  stamp=`date +%s`
  leaderall=` ./etcdgetlocal.py leader --prefix `
  leader=`echo $leaderall | awk -F'/' '{print $2}' | awk -F"'" '{print $1}'`
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${pool}_$name/request/$leader volumes_$stamp
 
 done
fi
