#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
leaderip=` ./etcdgetlocal.py leaderip `
echo $@ > /root/VolumeDeleteISCSI 
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $3}'`;
leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
pro=`echo $@ | awk '{print $4}'`;
volip=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $6}'`;
DG=`echo $pDG `;
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi


  docker exec etcdclient /TopStor/logmsg.py NFS1000 info $userreq $volname
 cd /TopStor
 echo $DG/$volname
 disk=`ls -l /dev/zvol/$DG/$volname | awk -F'/' '{print $NF}'`
 echo $disk
 echo targetcli backstores/block delete ${disk}-${myhost}-$volname
 targetcli backstores/block delete ${disk}-${myhost}-$volname
 /sbin/zfs destroy -rf $DG/$volname 
 if [ $? -ne 0  ]; then
   docker exec etcdclient /TopStor/logmsg.py NFS1001 error $userreq $volname
   echo /sbin/zfs destroy -rf $DG/$volname >/root/errorVolumeDeleteISCSI
 else
  rm -rf /$DG/iscsi.$volname
  /pace/etcddel.py $leaderip volume $volname
  stamp=`date +%s`
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
  /TopStor/SnapShotPeriodDelete $leaderip $volname $userreq
  #/pace/delbroadcastlocal.py volume $volname
  /pace/putzpool.py $leaderip
  docker exec etcdclient /TopStor/logmsg.py NFS1002 info  $userreq $volname
 fi
 rm -rf /$DG/iscsi.$volname
fi
