#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
leaderip=` ./etcdgetlocal.py leaderip `
echo $@ > /root/VolumeDeleteISCSI 
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py VolumeDeleteISCSI start system 
fi
logging='/var/www/html/des20/Data/currentinfo2.log'
glog='/var/www/html/des20/Data/TopStor.log';
runningpools='/pacedata/pools/runningpools'
datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
volname=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $1}'`;
pro=`echo $@ | awk '{print $3}'`;
volip=` echo $@ | awk '{print $4}'`;
userreq=` echo $@ | awk '{print $5}'`;
DG=`echo $pDG `;
myhost=`hostname -s`
txtres='/TopStordata/'`basename $0`$userreq
rm -rf $txtres &>/dev/null
privilege=$pro;
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  /TopStor/logmsg.py NFS1000 info $userreq $volname
 cd /TopStor
 echo $DG/$volname
 disk=`ls -l /dev/zvol/$DG/$volname | awk -F'/' '{print $NF}'`
 echo $disk
 echo targetcli backstores/block delete ${disk}-${myhost}-$volname
 targetcli backstores/block delete ${disk}-${myhost}-$volname
 /sbin/zfs destroy -rf $DG/$volname 
 if [ $? -ne 0  ]; then
   /TopStor/logmsg.py NFS1001 error $userreq $volname
   echo /sbin/zfs destroy -rf $DG/$volname >/root/errorVolumeDeleteISCSI
 else
  rm -rf /$DG/iscsi.$volname
  /pace/etcddel.py $leaderip volume $volname
  stamp=`date +%s`
  leader=` ./etcdgetlocal.py leader `
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
  /TopStor/SnapShotPeriodDelete $volname $userreq
  #/pace/delbroadcastlocal.py volume $volname
  /pace/putzpool.py 
  /TopStor/logmsg.py NFS1002 info  $userreq $volname
 fi
 rm -rf /$DG/iscsi.$volname
fi
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py VolumeDeleteISCSI stop system 
fi
