#!/bin/sh
export ETCDCTL_API=3
echo $@ > /root/Zpoolparam
pool=`echo $@ | awk '{print $3}' | awk -F'/' '{print $3}'`
x=`pgrep Zpool2 -c`
if [ $x -gt 1 ];
then
 exit
fi
echo $pool >> /root/Zpooltmp
success=1;
myhost=`hostname`
ETCDCTL_API=3 /pace/etcdget.py cannotimport/$myhost |  grep $pool
if [ $? -eq 0 ];
then
 ETCDCTL_API=3 /pace/etcddel.py lockedpools/$pool
 exit
fi
echo starting to zpool the $pool > /root/Zpool
#/sbin/zpool import -c /TopStordata/$pool -am
/sbin/zpool import $pool -am
echo ran the import >> /root/Zpool
/sbin/zpool status | grep $pool
if [ $? -ne 0 ];
then
 /sbin/zpool import $pool
 /sbin/zpool status | grep $pool
 if [ $? -ne 0 ];
 then
  echo the pool $pool is not imported >> /root/Zpool
  success=0
  ETCDCTL_API=3 /TopStor/logmsg.py Zpfa02 warning system $pool
  echo cannot import it  >> /root/Zpool
  myhost=`hostname`
  slash='/'
  cannotimport=`ETCDCTL_API=3 /pace/etcdget.py cannotimport/$myhost`
  if [ -z $cannotimport ];
  then
   cannotimport=''
   slash=''
  fi
  if [ $cannotimport -eq -1 ];
  then
   cannotimport=''
   slash=''
  fi
  echo preparing to set the cannotimport=$cannotimport  >> /root/Zpool
  ETCDCTL_API=3 /pace/etcdput.py cannotimport/$myhost ${cannotimport}${slash}${pool}
  ETCDCTL_API=3 /pace/etcddel.py poolsnxt/$pool
  echo added it  >> /root/Zpool
 else
  success=1
  echo pool $pool is hardly imported >> /root/Zpool
 fi
else
  success=1;
 echo pool $pool is imported   >> /root/Zpool
fi
if [ $success -eq 1 ]; 
then
 ETCDCTL_API=3 /TopStor/logmsg.py Zpsu02 info system $pool
 /sbin/zpool set cachefile=$3 $pool
 ETCDCTL_API=3 /pace/etcdput.py pools/$pool $myhost
 ETCDCTL_API=3 /pace/broadcasttolocal pools/$pool $myhost
 /pace/putzpool.py
 #ETCDCTL_API=3 /pace/syncpools.py thispool $pool.
 ETCDCTL_API=3 /pace/etcddel.py poolsnxt/$pool
 ETCDCTL_API=3 /pace/etcddel.py cannot $pool
fi 
ETCDCTL_API=3 /pace/etcddel.py lockedpools/$pool
