#!/bin/sh
export ETCDCTL_API=3
echo $@ > /root/Zpoolclrrun
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py Zpoolclrrun start system 
fi
#x=` ETCDCTL_API=3 /TopStor/etcdget.py cleareddisk/$@`
x=get('clusternode')
y=`ETCDCTL_API=3 /TopStor/etcdgetlocal.py clearplsdisk/$@`
myhost=`hostname`
err=''
echo y=$y
echo $myhost | grep $y 
if [ $? -eq 0 ];
then
 /sbin/zpool  labelclear /dev/disk/by-id/$@ -f  2> /TopStordata/Zpoolclrrunerr
 err=`cat /TopStordata/Zpoolclrrunerr`
 echo $err | grep pool
 if [ $? -ne 0 ];
 then
  echo $pool
 /sbin/zpool  labelclear $vdevdisk -f 
 /sbin/zpool  labelclear $@ -f 
 fi
 echo err=$err
 /pace/etcdputlocal.py cleareddisk/$@ $myhost
fi
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/logqueue.py Zpoolclrrun stop system 
fi
