#!/bin/sh
export ETCDCTL_API=3
echo $@ > /root/Zpoolparam
echo starting zpooldeadhost
pool=`echo $@ | awk '{print $3}' | awk -F'/' '{print $3}'`
#x=`pgrep Zpool2 -c`
#if [ $x -gt 1 ];
#then
# exit
#fi
success=1;
myhost=`hostname`
echo importing the $pool nicely 
echo starting to zpool the $pool > /root/Zpooldeadhost
/sbin/zpool import -c /TopStordata/$pool -am
echo ran the import >> /root/Zpooldeadhost
/sbin/zpool status | grep $pool
if [ $? -ne 0 ];
then
 /sbin/zpool import $pool
 echo hardly importing and waiting for leader >> /root/Zpooldeadhost
 while true;
 do
  echo starting checking leaderetcd=$?
  leaderall=` ./etcdget.py leader --prefix 2>&1`
  echo $leaderall | grep Error  &>/dev/null
  if [ $? -ne 0 ];
  then
   break
  else
   sleep 1
  fi
 done
 /sbin/zpool status | grep $pool
 if [ $? -ne 0 ];
 then
  echo the pool $pool is not imported >> /root/Zpooldeadhost
  success=0
  

  ETCDCTL_API=3 /TopStor/logmsg.py Zpfa02 warning system $pool
  echo cannot import it  >> /root/Zpool
  myhost=`hostname`
  slash='/'
  cannotimport=`ETCDCTL_API=3 /pace/etcdget.py cannotimport/$myhost`
  if [ -z $cannotimport ];
  then
   cannotimport=''
   slash=''
  fi
  if [ $cannotimport -eq -1 ];
  then
   cannotimport=''
   slash=''
  fi
  echo preparing to set the cannotimport=$cannotimport  >> /root/Zpool
  ETCDCTL_API=3 /pace/etcdput.py cannotimport/$myhost ${cannotimport}${slash}${pool}
  ETCDCTL_API=3 /pace/etcddel.py poolsnxt/$pool
  echo added it  >> /root/Zpool
 else:
  success=1
  echo pool $pool is hardly imported >> /root/Zpooldeadhost
 fi
else
 echo pool $pool is imported  nicely.. waiting for leader >> /root/Zpooldeadhost
 while true;
 do
  echo starting checking leaderetcd=$?
  leaderall=` ./etcdget.py leader --prefix 2>&1`
  echo $leaderall | grep Error  &>/dev/null
  if [ $? -ne 0 ];
  then
   break
  else
   sleep 1
  fi
 done
 success=1;
fi
if [ $success -eq 1 ]; 
then
 ETCDCTL_API=3 /TopStor/logmsg.py Zpsu02 info system $pool
 /sbin/zpool set cachefile=$3 $pool
 ETCDCTL_API=3 /pace/etcdput.py pools/$pool $myhost
 ETCDCTL_API=3 /pace/broadcasttolocal pools/$pool $myhost
 /pace/putzpool.py
 ETCDCTL_API=3 /pace/syncpools.py thispool $pool.
 ETCDCTL_API=3 /pace/etcddel.py poolsnxt/$pool
 ETCDCTL_API=3 /pace/etcddel.py cannot $pool
fi 
