#!/bin/sh
export ETCDCTL_API=3
echo $@ > /root/Zpoolclrrun
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/queuethis.sh Zpoolclrrun start system &
fi
x=` ETCDCTL_API=3 /pace/etcget.py cleareddisk/$@`
y=`ETCDCTL_API=3 /pace/etcget.py clearplsdisk/$@`
echo $x | grep $y 
if [ $? -ne 0 ];
then
 myhost=`hostname`
 /sbin/zpool  labelclear -f $@
 /pace/etcdput.py cleareddisk/$@ $myhost
#/pace/etcddel.py clearplsdisk/$@ 
fi
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 /TopStor/queuethis.sh Zpoolclrrun stop system &
fi
